// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hero-variants/BoldNavy.tsx": () => import("../components/mockups/hero-variants/BoldNavy.tsx"),
  "./components/mockups/hero-variants/SavingsFirst.tsx": () => import("../components/mockups/hero-variants/SavingsFirst.tsx"),
  "./components/mockups/hero-variants/SplitLight.tsx": () => import("../components/mockups/hero-variants/SplitLight.tsx")
};
