export const STATIC_BLOG_SLUGS = [
  "how-to-read-credit-card-processing-statement",
  "cash-discount-vs-surcharging",
  "hidden-fees-payment-processing-guide",
  "how-to-switch-payment-processors",
  "best-payment-processing-restaurants-2025",
  "interchange-plus-vs-flat-rate",
  "pci-compliance-checklist-small-business",
  "how-much-does-credit-card-processing-cost",
  "what-is-interchange-plus-pricing",
  "emv-chip-cards-explained",
  "contactless-payments-nfc-apple-pay-google-pay",
  "understanding-chargebacks-prevention-response-recovery",
  "ach-vs-credit-card-processing",
  "what-is-a-payment-gateway-how-it-works",
  "level-2-level-3-processing-b2b-savings",
  "keyed-vs-swiped-transactions-entry-method-matters",
  "payment-processing-ecommerce-complete-guide",
  "mobile-payment-solutions-field-service",
  "accept-payments-trade-shows-pop-up-events",
  "restaurant-payment-processing-tips-pos-savings",
  "healthcare-payment-processing-hipaa-compliance",
  "salon-spa-payment-solutions-booking-tips-recurring",
  "auto-repair-shop-payment-processing-invoicing",
  "construction-industry-payments-progress-billing",
  "pci-dss-4-what-changed-merchants",
  "how-to-prevent-credit-card-fraud-business",
  "tokenization-vs-encryption-payment-data",
  "tcpa-compliance-merchant-services-text-call-rules",
  "ada-website-compliance-payment-pages",
  "surcharging-laws-by-state",
  "data-breach-response-plan-small-business",
  "understanding-pci-self-assessment-questionnaire-saq",
  "how-to-negotiate-lower-credit-card-processing-rates",
  "dual-pricing-vs-cash-discount-which-program-is-right",
  "true-cost-of-free-payment-processing-offers",
  "when-to-switch-payment-processors-warning-signs",
  "processing-volume-tiers-how-higher-volume-gets-better-rates",
  "same-day-vs-next-day-funding-settlement-speed-explained",
  "merchant-account-reserves-what-they-are-how-to-avoid",
  "annual-fee-pci-fee-statement-fee-breaking-down-monthly-charges",
  "pos-system-buying-guide-2025",
  "virtual-terminal-vs-payment-gateway",
  "recurring-billing-subscription-payment-processing",
  "payment-processing-for-nonprofits",
  "multi-location-payment-processing",
  "international-payment-processing",
  "payment-processing-trends-2025",
  "how-to-read-effective-rate",
  "integrated-vs-non-integrated-payments",
  "buy-now-pay-later-for-merchants-bnpl",
  "cheapest-credit-card-processing-restaurants",
  "how-to-avoid-payment-processing-fees",
  "best-pos-system-auto-repair-shops",
  "credit-card-processing-fees-explained-2025",
  "dental-office-payment-processing-guide",
  "merchant-services-for-small-business-florida",
  "payment-processing-for-med-spas",
  "law-firm-credit-card-processing-trust-accounts",
  "gym-membership-billing-payment-processing",
  "hotel-payment-processing-pre-authorization-guide",
  "what-is-dual-pricing-complete-guide",
  "accounting-firm-payment-processing-guide",
  "how-to-read-your-merchant-processing-statement",
  "good-credit-card-processing-rate-for-my-business",
  "interchange-plus-vs-flat-rate-pricing-comparison",
  "complete-guide-to-interchange-fees",
  "cash-discount-vs-surcharging-what-is-legal",
  "how-to-implement-cash-discount-program",
  "how-to-fight-a-chargeback-and-win",
  "chargeback-prevention-restaurants-retailers",
  "best-credit-card-terminals-small-business-2025",
  "square-vs-dedicated-merchant-account-when-to-upgrade",
];

export const INDUSTRY_SLUGS = [
  "restaurant-payment-processing",
  "retail-payment-processing",
  "healthcare-payment-processing",
  "salon-spa-payment-processing",
  "auto-repair-payment-processing",
  "professional-services-payment-processing",
  "ecommerce-payment-processing",
  "construction-payment-processing",
  "dental-payment-processing",
  "med-spa-payment-processing",
  "legal-payment-processing",
  "accounting-payment-processing",
  "fitness-payment-processing",
  "hospitality-payment-processing",
];

export const LOCATION_CITIES = [
  "miami", "fort-lauderdale", "tampa", "orlando", "jacksonville",
  "miami-beach", "boca-raton", "west-palm-beach", "pompano-beach", "hollywood-fl",
  "coral-springs", "plantation", "hialeah", "sarasota", "st-petersburg",
  "clearwater", "cape-coral", "fort-myers", "gainesville", "pensacola",
  "houston", "dallas", "atlanta", "las-vegas", "phoenix",
  "nashville", "charlotte", "denver", "austin", "chicago",
];
export const LOCATION_VERTICALS = [
  "restaurant", "auto-repair", "healthcare", "salon", "retail",
  "dental", "fitness", "hotel", "barbershop", "contractor",
];
