export interface GhlRouteMutationCallSite {
  file: string;
  lineContains: string;
  occurrence?: number;
  gateContains: string;
  maxLinesBetween: number;
  disposition: "reject_503" | "skip_auxiliary";
  reason: string;
  reviewDate: string;
}

export const GHL_ROUTE_MUTATION_FUNCTIONS = [
  "upsertGhlContact",
  "createGhlTask",
  "updateCustomFields",
  "addNote",
  "addTag",
  "disableConversationAi",
  "enrollInGhlWorkflowCompliant",
  "enrollContactInGhlWorkflow",
] as const;

/**
 * Reviewed C-04 route-level GHL mutation sites (#1629).
 *
 * This list is enforcement input, not a bypass: compliance-scan requires the
 * named gate before every named occurrence and exits non-zero if either side
 * disappears or moves outside the reviewed control-flow window.
 */
export const GHL_ROUTE_MUTATION_ALLOWLIST: readonly GhlRouteMutationCallSite[] = [
  {
    file: "server/routes/sdr.ts",
    lineContains: "await upsertGhlContact(contact)",
    occurrence: 1,
    gateContains: "if (contact?.ghlContactId && !(await requireGhlRouteMutationAllowed(res))) return;",
    maxLinesBetween: 25,
    disposition: "reject_503",
    reason: "kept-ghl conflict resolution is gated before local and GHL writes.",
    reviewDate: "2026-08-18",
  },
  {
    file: "server/routes/sdr.ts",
    lineContains: "await upsertGhlContact(contact)",
    occurrence: 2,
    gateContains: "if (contact?.ghlContactId && !(await requireGhlRouteMutationAllowed(res))) return;",
    maxLinesBetween: 36,
    disposition: "reject_503",
    reason: "kept-internal conflict resolution shares the single reviewed route authorization.",
    reviewDate: "2026-08-18",
  },
  {
    file: "server/routes/admin.ts",
    lineContains: "const result = await upsertGhlContact(contact)",
    gateContains: "if (!(await requireGhlRouteMutationAllowed(res))) return;",
    maxLinesBetween: 3,
    disposition: "reject_503",
    reason: "Admin retry checks configuration, contact existence, then pause authority before upsert.",
    reviewDate: "2026-08-18",
  },
  {
    file: "server/routes/underwriting.ts",
    lineContains: "createGhlTask({",
    occurrence: 1,
    gateContains: "if (!(await requireGhlRouteMutationAllowed(res))) return;",
    maxLinesBetween: 20,
    disposition: "reject_503",
    reason: "Approve override authorizes before the local override and its GHL task.",
    reviewDate: "2026-08-18",
  },
  {
    file: "server/routes/underwriting.ts",
    lineContains: "createGhlTask({",
    occurrence: 2,
    gateContains: "if (!(await requireGhlRouteMutationAllowed(res))) return;",
    maxLinesBetween: 30,
    disposition: "reject_503",
    reason: "Reject override authorizes before the local override and its GHL task.",
    reviewDate: "2026-08-18",
  },
  {
    file: "server/routes/deals.ts",
    lineContains: "await updateCustomFields(contact.ghlContactId, fields)",
    gateContains: "if (!(await requireGhlRouteMutationAllowed(res))) return;",
    maxLinesBetween: 3,
    disposition: "reject_503",
    reason: "Analysis sync rejects before the custom-field/workflow mutation sequence.",
    reviewDate: "2026-08-18",
  },
  {
    file: "server/routes/deals.ts",
    lineContains: "await enrollInGhlWorkflowCompliant({",
    gateContains: "if (!(await requireGhlRouteMutationAllowed(res))) return;",
    maxLinesBetween: 5,
    disposition: "reject_503",
    reason: "The same authorization covers workflow enrollment in the analysis-sync sequence.",
    reviewDate: "2026-08-18",
  },
  {
    file: "server/routes/documents.ts",
    lineContains: "await addNote({ contactId: contact.ghlContactId",
    gateContains: "const pauseDecision = await authorizeGhlRouteMutation();",
    maxLinesBetween: 5,
    disposition: "skip_auxiliary",
    reason: "Rejected-document note re-authorizes inside deferred work; the route also rejects an already-active pause before changing status.",
    reviewDate: "2026-08-18",
  },
  {
    file: "server/routes/partners.ts",
    lineContains: "await addTag({ contactId: contact.ghlContactId",
    gateContains: "const pauseDecision = await authorizeGhlRouteMutation();",
    maxLinesBetween: 20,
    disposition: "skip_auxiliary",
    reason: "Fire-and-forget referral enrollment re-authorizes before its GHL sequence.",
    reviewDate: "2026-08-18",
  },
  {
    file: "server/routes/partners.ts",
    lineContains: "await addNote({",
    gateContains: "const pauseDecision = await authorizeGhlRouteMutation();",
    maxLinesBetween: 25,
    disposition: "skip_auxiliary",
    reason: "The referral note shares the single deferred-work authorization.",
    reviewDate: "2026-08-18",
  },
  {
    file: "server/routes/partners.ts",
    lineContains: "const result = await enrollContactInGhlWorkflow({",
    gateContains: "const pauseDecision = await authorizeGhlRouteMutation();",
    maxLinesBetween: 40,
    disposition: "skip_auxiliary",
    reason: "The referral workflow enrollment is part of the same authorized sequence.",
    reviewDate: "2026-08-18",
  },
  {
    file: "server/routes/partner-orgs.ts",
    lineContains: "addNote({ contactId: contact!.ghlContactId",
    occurrence: 1,
    gateContains: "const pauseDecision = await authorizeGhlRouteMutation();",
    maxLinesBetween: 6,
    disposition: "skip_auxiliary",
    reason: "Public proposal GET preserves its read response but skips auxiliary GHL mutations while paused.",
    reviewDate: "2026-08-18",
  },
  {
    file: "server/routes/partner-orgs.ts",
    lineContains: "addTag({ contactId: contact!.ghlContactId",
    occurrence: 1,
    gateContains: "const pauseDecision = await authorizeGhlRouteMutation();",
    maxLinesBetween: 7,
    disposition: "skip_auxiliary",
    reason: "Viewed tag shares the single proposal-view authorization.",
    reviewDate: "2026-08-18",
  },
  {
    file: "server/routes/partner-orgs.ts",
    lineContains: "enrollInGhlWorkflowCompliant({",
    occurrence: 1,
    gateContains: "const pauseDecision = await authorizeGhlRouteMutation();",
    maxLinesBetween: 8,
    disposition: "skip_auxiliary",
    reason: "Viewed workflow enrollment shares the single proposal-view authorization.",
    reviewDate: "2026-08-18",
  },
  {
    file: "server/routes/partner-orgs.ts",
    lineContains: "addNote({ contactId: contact!.ghlContactId",
    occurrence: 2,
    gateContains: "if (contact?.ghlContactId && isSdrGhlConfigured() && !(await requireGhlRouteMutationAllowed(res))) return;",
    maxLinesBetween: 25,
    disposition: "reject_503",
    reason: "Proposal acceptance authorizes before acceptedAt and the provider mutation sequence.",
    reviewDate: "2026-08-18",
  },
  {
    file: "server/routes/partner-orgs.ts",
    lineContains: "addTag({ contactId: contact!.ghlContactId",
    occurrence: 2,
    gateContains: "if (contact?.ghlContactId && isSdrGhlConfigured() && !(await requireGhlRouteMutationAllowed(res))) return;",
    maxLinesBetween: 26,
    disposition: "reject_503",
    reason: "Accepted tag shares the pre-local-write route authorization.",
    reviewDate: "2026-08-18",
  },
  {
    file: "server/routes/partner-orgs.ts",
    lineContains: "enrollInGhlWorkflowCompliant({",
    occurrence: 2,
    gateContains: "if (contact?.ghlContactId && isSdrGhlConfigured() && !(await requireGhlRouteMutationAllowed(res))) return;",
    maxLinesBetween: 27,
    disposition: "reject_503",
    reason: "Accepted workflow enrollment shares the pre-local-write route authorization.",
    reviewDate: "2026-08-18",
  },
  {
    file: "server/routes/partner-orgs.ts",
    lineContains: "enrollInGhlWorkflowCompliant({",
    occurrence: 3,
    gateContains: "if (isSdrGhlConfigured() && !(await requireGhlRouteMutationAllowed(res))) return;",
    maxLinesBetween: 3,
    disposition: "reject_503",
    reason: "The separately exposed admin workflow-enrollment route was found by the post-audit inventory and is explicitly gated.",
    reviewDate: "2026-08-18",
  },
  {
    file: "server/routes/conversation-ai-config.ts",
    lineContains: "await addTag({ contactId: contact.ghlContactId",
    gateContains: "if (!(await requireGhlRouteMutationAllowed(res))) return;",
    maxLinesBetween: 3,
    disposition: "reject_503",
    reason: "Human takeover rejects before its three-step GHL mutation sequence.",
    reviewDate: "2026-08-18",
  },
  {
    file: "server/routes/conversation-ai-config.ts",
    lineContains: "await updateCustomFields(contact.ghlContactId",
    gateContains: "if (!(await requireGhlRouteMutationAllowed(res))) return;",
    maxLinesBetween: 4,
    disposition: "reject_503",
    reason: "Human-takeover custom fields share the single route authorization.",
    reviewDate: "2026-08-18",
  },
  {
    file: "server/routes/conversation-ai-config.ts",
    lineContains: "await disableConversationAi(contact.ghlContactId)",
    gateContains: "if (!(await requireGhlRouteMutationAllowed(res))) return;",
    maxLinesBetween: 5,
    disposition: "reject_503",
    reason: "Previously omitted AI-disable mutation is covered by the same route authorization.",
    reviewDate: "2026-08-18",
  },
] as const;
