import assert from "node:assert/strict";
import {randomUUID} from "node:crypto";
import {stage3BHttpFixture} from "./fixtures/stage3-b-http";
let extractionCalls=0;
const h=await stage3BHttpFixture(async app=>{
  const {registerActivityRoutes}=await import("../server/routes/activity");
  const {registerContactsRoutes}=await import("../server/routes/contacts");
  const {registerCrmOperationsRoutes}=await import("../server/routes/crm-operations");
  registerActivityRoutes(app);registerContactsRoutes(app);
  registerCrmOperationsRoutes(app,{relationshipExtractor:async()=>{extractionCalls++;throw new Error("fake extraction failure");}});
});
try {
  const makeContact=async(role:string)=>(await h.pool.query(`INSERT INTO contacts(first_name,last_name,email,phone,assigned_to,record_class)
    VALUES('Context','Fixture',$1,$2,$3,'production') RETURNING id`,[`${randomUUID()}@example.test`,
    `+1${String(Date.now()+Math.floor(Math.random()*999999)).slice(-10)}`,h.email(role)])).rows[0].id;
  const own=await makeContact("agent"),foreign=await makeContact("other");
  const deal=(await h.pool.query(`INSERT INTO deals(name,owner,record_class) VALUES('Foreign fixture',$1,'production') RETURNING id`,[h.email("other")])).rows[0].id;
  const envelope=(role="agent",fields:any={})=>({commandId:randomUUID(),expectedActorId:h.userId(role),expectedAccountVersion:1,...fields});
  const create=envelope("agent",{entityType:"contact",entityId:own,content:"retained note"});
  assert.equal((await h.request("anonymous","POST","/api/notes",create)).status,401);
  for(const role of ["merchant","affiliate","partner"]) assert.equal((await h.request(role,"GET",`/api/notes?entityType=contact&entityId=${own}`)).status,403);
  assert.equal((await h.request("agent","POST","/api/notes",create,false)).status,403);
  assert.equal((await h.request("agent","POST","/api/notes",{...create,authorId:h.userId("other")})).status,400);
  assert.equal((await h.request("agent","POST","/api/notes",{...create,entityId:foreign})).status,404);
  assert.equal((await h.request("agent","POST","/api/notes",{...create,entityType:"deal",entityId:deal})).status,404);
  assert.equal((await h.request("agent","GET",`/api/notes?entityType=arbitrary&entityId=${own}`)).status,400);
  assert.equal((await h.request("agent","GET",`/api/notes?entityType=contact&entityId=${own}.5`)).status,400);
  const saved=await h.request("agent","POST","/api/notes",create);assert.equal(saved.status,201,JSON.stringify(saved.body));
  const id=saved.body.id;assert.equal(saved.body.authorId,h.userId("agent"));assert.equal(saved.body.version,1);
  assert.equal((await h.request("agent","POST","/api/notes",create)).body.id,id);
  assert.equal((await h.request("agent","POST","/api/notes",{...create,content:"retry changed"})).status,409);
  const edit=envelope("agent",{expectedVersion:1,content:"new note body"});
  const concurrent=await Promise.all([h.request("agent","PATCH",`/api/notes/${id}`,edit),h.request("agent","PATCH",`/api/notes/${id}`,edit)]);
  assert.ok(concurrent.every(row=>row.status===200),JSON.stringify(concurrent));assert.equal(concurrent[0].body.note.version,2);
  assert.equal((await h.request("other","PATCH",`/api/notes/${id}`,edit)).status,409,"wrong actor envelope fails before effects");
  assert.equal((await h.request("other","PATCH",`/api/notes/${id}`,envelope("other",{content:"foreign",expectedVersion:2}))).status,404);
  assert.equal((await h.request("agent","PATCH",`/api/notes/${id}`,{...edit,entityId:foreign})).status,400);
  assert.equal((await h.request("agent","PATCH",`/api/notes/${id}`,envelope("agent",{content:"stale",expectedVersion:1}))).status,409);
  const pin=envelope("agent",{expectedVersion:2,pinned:true});
  assert.equal((await h.request("agent","PATCH",`/api/contacts/${foreign}/notes/${id}/pin`,pin)).status,404);
  const pinned=await h.request("agent","PATCH",`/api/contacts/${own}/notes/${id}/pin`,pin);
  assert.equal(pinned.status,200,JSON.stringify(pinned.body));assert.equal(pinned.body.note.pinned,true);
  const read=await h.request("agent","GET",`/api/notes?entityType=contact&entityId=${own}`);
  assert.equal(read.body[0].content,"new note body");assert.equal(read.body[0].version,3);
  const deletion=envelope("agent",{expectedVersion:3});
  assert.equal((await h.request("agent","DELETE",`/api/notes/${id}`,deletion)).status,200);
  assert.equal((await h.request("agent","DELETE",`/api/notes/${id}`,deletion)).body.replayed,true);
  assert.equal((await h.request("agent","GET",`/api/notes?entityType=contact&entityId=${own}`)).body.length,0);
  assert.equal((await h.pool.query("SELECT count(*)::int n FROM notes WHERE id=$1 AND deleted_at IS NOT NULL",[id])).rows[0].n,1);
  assert.equal((await h.pool.query("SELECT count(*)::int n FROM note_command_receipts WHERE note_id=$1",[id])).rows[0].n,4);
  const company=await h.request("agent","POST","/api/companies",{legalName:"Owned company fixture"});
  assert.equal(company.status,201,JSON.stringify(company.body));assert.equal(company.body.createdByUserId,h.userId("agent"));
  const foreignCompany=(await h.pool.query(`INSERT INTO companies(legal_name,created_by_user_id) VALUES('Foreign company fixture',$1) RETURNING id`,[h.userId("other")])).rows[0].id;
  assert.equal((await h.request("agent","POST",`/api/contacts/${own}/companies`,{companyId:foreignCompany})).status,404);
  assert.equal((await h.request("agent","GET",`/api/companies/${foreignCompany}`)).status,404);
  assert.equal((await h.request("agent","PUT",`/api/companies/${foreignCompany}`,{dba:"forged"})).status,404);
  const linkBody={companyId:company.body.id,role:"Owner",isPrimary:false};
  const links=await Promise.all([h.request("agent","POST",`/api/contacts/${own}/companies`,linkBody),h.request("agent","POST",`/api/contacts/${own}/companies`,linkBody)]);
  assert.ok(links.every(row=>[200,201].includes(row.status)),JSON.stringify(links));assert.equal(links[0].body.id,links[1].body.id);
  assert.equal(links[0].body.extractionState,"management_review_required");assert.equal(extractionCalls,0);
  const accepted=await h.request("manager","POST",`/api/contacts/${own}/companies`,linkBody);
  assert.equal(accepted.status,200);assert.equal(accepted.body.extractionState,"failed");assert.equal(extractionCalls,1);
  await h.pool.query("INSERT INTO contact_companies(contact_id,company_id) VALUES($1,$2)",[foreign,company.body.id]);
  const members=await h.request("agent","GET",`/api/companies/${company.body.id}/contacts`);
  assert.equal(members.status,200);assert.deepEqual(members.body.map((row:any)=>row.id),[own]);
  assert.equal((await h.request("agent","GET",`/api/contacts/${foreign}/companies`)).status,404);
  assert.equal((await h.request("agent","DELETE","/api/contact-companies/2147483647")).status,404);
  assert.equal((await h.request("other","DELETE",`/api/contact-companies/${links[0].body.id}`)).status,404);
  assert.equal((await h.request("agent","DELETE",`/api/contact-companies/${links[0].body.id}`)).status,200);
  assert.equal((await h.pool.query("SELECT count(*)::int n FROM contact_companies WHERE company_id=$1 AND contact_id=$2",[company.body.id,own])).rows[0].n,0);
  assert.equal(h.externalCalls(),0);
  console.log("PASS actual contextual notes/company handlers, persisted sessions/CSRF, stored-target/author/version/retry/soft-removal/pin, both endpoint denial, creator/relationship company policy, foreign-membership projection, serialized duplicate links, accepted link with truthful fake extraction failure, missing unlink response, zero external effects.");
} finally {await h.close();}
