/**
 * Contact Reconciliation Runner — admin-triggered, read-mostly scan of census members.
 *
 * Safety guarantees:
 *  - Zero external provider calls
 *  - Zero writes to canonical contact/business/deal tables during classification
 *  - BACKGROUND_JOB_PROFILE must be 'off' to start a run
 *  - All writes are scoped to reconciliation tables only
 *
 * Single-run ownership — DB-enforced:
 *  - census_recon_one_active partial unique index allows at most one row with
 *    status IN ('pending','running') across ALL application instances.
 *  - Lease owner/expires pattern mirrors census runner.
 *
 * Source of truth:
 *  - Iterates contact_census_members for the source_census_run_id, joining
 *    contacts to get current values. Bounded to the census watermark.
 *
 * Org aggregation:
 *  - Groups by LOWER(TRIM(company_name)) into contact_organization_candidates.
 *  - Both inserts use ON CONFLICT DO NOTHING (idempotent).
 *
 * Duplicate clusters:
 *  - One cluster row per unique phone that is shared across >1 company.
 *  - N member rows per cluster — never N×(N−1)/2 pairs.
 *  - Uses ON CONFLICT DO NOTHING.
 *
 * Normalization proposals:
 *  - Generated by generateProposals() (pure function).
 *  - Stores contact_updated_at for CAS guard at approval time.
 *  - Does NOT write to contacts table; that is done by reconciliation-approval.ts.
 */

import os from "os";
import pg from "pg";
import { pool } from "../db";
import {
  classifyReconciliation,
  generateProposals,
  type ReconciliationContactRow,
} from "./reconciliation-classifier";
import { leaseOwnerTag as censusLeaseOwnerTag } from "./contact-census-runner";
import {
  classifyContactQuality,
  buildQualityRunContext,
  normalizeNanpPhone,
  type QualityContactInput,
  type QualityRunContext,
} from "./contact-quality-signals";

const { Client } = pg;

// Re-export for route use
export function leaseOwnerTag(): string {
  return `${os.hostname()}:${process.pid}`;
}

// ──────────────────────────────────────────────────────────────────────────────
// Constants
// ──────────────────────────────────────────────────────────────────────────────
const RULES_VERSION = "1.0.0";
const QUALITY_RULES_VERSION = "quality-v1";
const BATCH_SIZE = 200;
const LEASE_DURATION_SECS = 120;
const LEASE_REFRESH_EVERY_N = 10;
const HEALTH_CHECK_EVERY_N = 10;
const POOL_PRESSURE_BACKOFF_MS = 5_000;
const BATCH_TIMEOUT_MS = 30_000;

// ──────────────────────────────────────────────────────────────────────────────
// CAS run update
// ──────────────────────────────────────────────────────────────────────────────
function toSnake(s: string): string {
  return s.replace(/([A-Z])/g, m => `_${m.toLowerCase()}`);
}

async function casUpdateRun(
  runId: string,
  leaseOwner: string,
  fields: Record<string, unknown>,
): Promise<boolean> {
  const keys = Object.keys(fields);
  if (keys.length === 0) return true;
  const sets = keys.map((k, i) => `"${toSnake(k)}" = $${i + 3}`).join(", ");
  const values = [runId, leaseOwner, ...Object.values(fields)];
  // Predicate also on status='running' so casUpdateRun cannot mutate a
  // paused or cancelled run even during initialization.
  const r = await pool.query(
    `UPDATE contact_reconciliation_runs SET ${sets}, updated_at = now()
     WHERE id = $1 AND lease_owner = $2 AND status = 'running'`,
    values,
  );
  return (r.rowCount ?? 0) > 0;
}

async function refreshLease(runId: string, leaseOwner: string): Promise<boolean> {
  const r = await pool.query(
    `UPDATE contact_reconciliation_runs
     SET lease_expires_at = now() + interval '${LEASE_DURATION_SECS} seconds', updated_at = now()
     WHERE id = $1 AND lease_owner = $2 AND status = 'running'`,
    [runId, leaseOwner],
  );
  return (r.rowCount ?? 0) > 0;
}

function poolMetrics() {
  return {
    totalCount: (pool as any).totalCount ?? 0,
    idleCount: (pool as any).idleCount ?? 0,
    waitingCount: (pool as any).waitingCount ?? 0,
    at: new Date().toISOString(),
  };
}

async function isLoginHealthy(): Promise<boolean> {
  try {
    const r = await pool.query("SELECT 1");
    return r.rowCount != null && r.rowCount > 0;
  } catch { return false; }
}

// ──────────────────────────────────────────────────────────────────────────────
// Load shared-phone data from census run context (legacy raw-string approach)
// ──────────────────────────────────────────────────────────────────────────────
async function loadSharedPhoneData(
  client: pg.PoolClient,
  censusRunId: string,
): Promise<Map<string, number>> {
  // phone → distinct company count (from census members for this census run)
  const r = await client.query(`
    SELECT
      c.phone,
      COUNT(DISTINCT LOWER(TRIM(c.company_name))) AS distinct_companies
    FROM contact_census_members ccm
    JOIN contacts c ON c.id = ccm.contact_id
    WHERE ccm.run_id = $1
      AND ccm.phone_quality_state != 'not_applicable'
      AND c.phone IS NOT NULL AND TRIM(c.phone) <> ''
    GROUP BY c.phone
    HAVING COUNT(DISTINCT LOWER(TRIM(c.company_name))) > 1
  `, [censusRunId]);

  const map = new Map<string, number>();
  for (const row of r.rows) {
    map.set(row.phone as string, parseInt(row.distinct_companies, 10));
  }
  return map;
}

// ──────────────────────────────────────────────────────────────────────────────
// Load quality-v1 shared phone cohort (normalized 10-digit NANP, set-based)
// ──────────────────────────────────────────────────────────────────────────────
async function loadQualitySharedPhones(
  client: pg.PoolClient,
  censusRunId: string,
): Promise<Array<{ normalized_phone: string; contact_count: number; domain_count: number }>> {
  // Normalize phone to canonical 10-digit NANP inside SQL before grouping so that
  // "5125550200" and "15125550200" and "(512) 555-0200" all land in the same bucket.
  // NANP normalization: strip all non-digits, then if 11 digits and starts with '1', drop the leading 1.
  // Wrap in a subquery so normalized_phone is a real column available to GROUP BY / HAVING.
  // PostgreSQL permits SELECT aliases in GROUP BY but not in HAVING (SQL:2003 restriction).
  const r = await client.query(`
    SELECT normalized_phone, contact_count, domain_count
    FROM (
      SELECT
        CASE
          WHEN length(regexp_replace(c.phone, '[^0-9]', '', 'g')) = 11
               AND left(regexp_replace(c.phone, '[^0-9]', '', 'g'), 1) = '1'
          THEN right(regexp_replace(c.phone, '[^0-9]', '', 'g'), 10)
          WHEN length(regexp_replace(c.phone, '[^0-9]', '', 'g')) = 10
          THEN regexp_replace(c.phone, '[^0-9]', '', 'g')
        END AS normalized_phone,
        COUNT(DISTINCT c.id) AS contact_count,
        COUNT(DISTINCT lower(split_part(c.email, '@', 2)))
          FILTER (WHERE c.email IS NOT NULL AND TRIM(c.email) <> '') AS domain_count
      FROM contact_census_members ccm
      JOIN contacts c ON c.id = ccm.contact_id
      WHERE ccm.run_id = $1
        AND c.phone IS NOT NULL AND TRIM(c.phone) <> ''
        AND c.archived_at IS NULL
      GROUP BY normalized_phone
    ) sub
    WHERE normalized_phone IS NOT NULL
      AND contact_count > 1
  `, [censusRunId]);

  return r.rows.map((row: any) => ({
    normalized_phone: row.normalized_phone as string,
    contact_count: parseInt(row.contact_count, 10),
    domain_count: parseInt(row.domain_count, 10),
  }));
}

// ──────────────────────────────────────────────────────────────────────────────
// Load quality-v1 shared email cohort (normalized lowercase, set-based)
// ──────────────────────────────────────────────────────────────────────────────
async function loadQualitySharedEmails(
  client: pg.PoolClient,
  censusRunId: string,
): Promise<Array<{ normalized_email: string; contact_count: number; domain_count: number }>> {
  const r = await client.query(`
    SELECT
      lower(trim(c.email))                      AS normalized_email,
      COUNT(DISTINCT c.id)                      AS contact_count,
      COUNT(DISTINCT lower(split_part(c.email, '@', 2))) AS domain_count
    FROM contact_census_members ccm
    JOIN contacts c ON c.id = ccm.contact_id
    WHERE ccm.run_id = $1
      AND c.email IS NOT NULL AND TRIM(c.email) <> ''
      AND c.archived_at IS NULL
    GROUP BY lower(trim(c.email))
    HAVING COUNT(DISTINCT c.id) > 1
  `, [censusRunId]);

  return r.rows.map((row: any) => ({
    normalized_email: row.normalized_email as string,
    contact_count: parseInt(row.contact_count, 10),
    domain_count: parseInt(row.domain_count, 10),
  }));
}

// ──────────────────────────────────────────────────────────────────────────────
// Load crosswalk decisions for a batch of contact IDs (set-based, not N+1)
// Returns: contactId → "candidate" | "conflict" | "none"
// Only uses completed crosswalk runs; excludes running/failed/cancelled/stale.
// ──────────────────────────────────────────────────────────────────────────────
async function loadCrosswalkDecisions(
  client: pg.PoolClient,
  contactIds: number[],
): Promise<Map<number, "candidate" | "conflict">> {
  if (contactIds.length === 0) return new Map();

  // contacts with business_id are already BUSINESS_LINK_VERIFIED — skip crosswalk lookup.
  // For contacts without business_id, check if there are approved decisions from
  // completed crosswalk runs where the subject's existing_fk_contact_id matches.
  const r = await client.query(`
    SELECT
      cis.existing_fk_contact_id                                                    AS contact_id,
      COUNT(DISTINCT cid.id) FILTER (WHERE cid.decision = 'approved'
        AND NOT cid.stale_at_decision)                                             AS approved_count,
      COUNT(DISTINCT cic.candidate_id)
        FILTER (WHERE cid.decision = 'approved' AND NOT cid.stale_at_decision
          AND cand.candidate_type = 'business')                                    AS business_candidate_count
    FROM contact_identity_subjects cis
    JOIN contact_identity_reconciliation_runs cirr
      ON cirr.id = cis.run_id AND cirr.status = 'completed'
    LEFT JOIN contact_identity_decisions cid ON cid.subject_id = cis.id
    LEFT JOIN contact_identity_candidates cand ON cand.id = cid.candidate_id
    LEFT JOIN LATERAL (SELECT cid.candidate_id) cic ON true
    WHERE cis.existing_fk_contact_id = ANY($1::int[])
    GROUP BY cis.existing_fk_contact_id
  `, [contactIds]);

  const out = new Map<number, "candidate" | "conflict">();
  for (const row of r.rows) {
    const contactId = parseInt(row.contact_id, 10);
    const approvedCount = parseInt(row.approved_count, 10);
    const bizCandidateCount = parseInt(row.business_candidate_count, 10);
    if (bizCandidateCount > 1) {
      out.set(contactId, "conflict");
    } else if (approvedCount > 0 && bizCandidateCount >= 1) {
      out.set(contactId, "candidate");
    }
  }
  return out;
}

// ──────────────────────────────────────────────────────────────────────────────
// Insert member batch (supports optional quality signal columns)
// ──────────────────────────────────────────────────────────────────────────────
interface MemberBatchRow extends ReturnType<typeof classifyReconciliation> {
  // Optional quality columns — present for quality-v1 runs only
  qualitySignalCodes?: string[];
  qualitySignalDetails?: Record<string, unknown>;
}

async function insertMemberBatch(
  client: pg.PoolClient,
  results: MemberBatchRow[],
): Promise<void> {
  if (results.length === 0) return;

  const hasQuality = results[0].qualitySignalCodes !== undefined;

  const columns = [
    "run_id", "contact_id", "census_member_id", "census_lane",
    "name_quality_state", "email_quality_state", "phone_quality_state",
    "company_quality_state", "vertical_state", "duplicate_risk_state",
    "business_gap_state", "org_aggregation_state",
    "normalization_opportunity", "cluster_candidacy_state",
    "overall_action_state", "primary_lane", "gap_codes",
    "has_business_id", "has_company_name", "has_email", "has_phone",
    "has_vertical", "has_first_name", "has_last_name",
    ...(hasQuality ? ["quality_signal_codes", "quality_signal_details"] : []),
  ];

  const valuePlaceholders: string[] = [];
  const values: unknown[] = [];
  let paramIdx = 1;

  for (const r of results) {
    const rowParams: unknown[] = [
      r.runId, r.contactId, r.censusMemberId, r.censusLane,
      r.nameQualityState, r.emailQualityState, r.phoneQualityState,
      r.companyQualityState, r.verticalState, r.duplicateRiskState,
      r.businessGapState, r.orgAggregationState,
      r.normalizationOpportunity, r.clusterCandidacyState,
      r.overallActionState, r.primaryLane, r.gapCodes,
      r.hasBusinessId, r.hasCompanyName, r.hasEmail, r.hasPhone,
      r.hasVertical, r.hasFirstName, r.hasLastName,
    ];
    if (hasQuality) {
      rowParams.push(r.qualitySignalCodes ?? []);
      rowParams.push(JSON.stringify(r.qualitySignalDetails ?? {}));
    }
    valuePlaceholders.push(`(${rowParams.map(() => `$${paramIdx++}`).join(",")})`);
    values.push(...rowParams);
  }

  await client.query(
    `INSERT INTO contact_reconciliation_members (${columns.join(",")}) VALUES ${valuePlaceholders.join(",")}
     ON CONFLICT (run_id, contact_id) DO NOTHING`,
    values,
  );
}

// ──────────────────────────────────────────────────────────────────────────────
// Upsert org candidates and members
// ──────────────────────────────────────────────────────────────────────────────
async function upsertOrgCandidates(
  client: pg.PoolClient,
  runId: string,
  batch: Array<{ contactId: number; companyName: string }>,
): Promise<void> {
  if (batch.length === 0) return;

  for (const { contactId, companyName } of batch) {
    const normalizedName = companyName.trim().toLowerCase();

    // Upsert the candidate
    const candidateR = await client.query(
      `INSERT INTO contact_organization_candidates (run_id, normalized_name, raw_sample_name)
       VALUES ($1, $2, $3)
       ON CONFLICT (run_id, normalized_name) DO NOTHING
       RETURNING id`,
      [runId, normalizedName, companyName.trim()],
    );

    let candidateId: number;
    if (candidateR.rows.length > 0) {
      candidateId = candidateR.rows[0].id;
    } else {
      const fetchR = await client.query(
        `SELECT id FROM contact_organization_candidates WHERE run_id = $1 AND normalized_name = $2`,
        [runId, normalizedName],
      );
      candidateId = fetchR.rows[0].id;
    }

    // Insert member — ON CONFLICT DO NOTHING (idempotent)
    await client.query(
      `INSERT INTO contact_organization_candidate_members (candidate_id, run_id, contact_id)
       VALUES ($1, $2, $3)
       ON CONFLICT (candidate_id, contact_id) DO NOTHING`,
      [candidateId, runId, contactId],
    );
  }
}

// ──────────────────────────────────────────────────────────────────────────────
// Upsert duplicate clusters and members
// ──────────────────────────────────────────────────────────────────────────────
async function upsertDuplicateClusters(
  client: pg.PoolClient,
  runId: string,
  batch: Array<{ contactId: number; phone: string }>,
  sharedPhoneMap: Map<string, number>,
): Promise<void> {
  if (batch.length === 0) return;

  for (const { contactId, phone } of batch) {
    const normalizedPhone = phone.trim();
    const companyCount = sharedPhoneMap.get(normalizedPhone) ?? 0;
    if (companyCount <= 1) continue;

    const clusterKey = `phone:${normalizedPhone}`;

    // Upsert cluster
    const clusterR = await client.query(
      `INSERT INTO contact_duplicate_clusters (run_id, cluster_key, cluster_reason)
       VALUES ($1, $2, 'shared_phone_multi_company')
       ON CONFLICT (run_id, cluster_key) DO NOTHING
       RETURNING id`,
      [runId, clusterKey],
    );

    let clusterId: string;
    if (clusterR.rows.length > 0) {
      clusterId = clusterR.rows[0].id;
    } else {
      const fetchR = await client.query(
        `SELECT id FROM contact_duplicate_clusters WHERE run_id = $1 AND cluster_key = $2`,
        [runId, clusterKey],
      );
      clusterId = fetchR.rows[0].id;
    }

    // Insert member — ON CONFLICT DO NOTHING
    await client.query(
      `INSERT INTO contact_duplicate_cluster_members (cluster_id, run_id, contact_id)
       VALUES ($1, $2, $3)
       ON CONFLICT (cluster_id, contact_id) DO NOTHING`,
      [clusterId, runId, contactId],
    );
  }
}

// ──────────────────────────────────────────────────────────────────────────────
// Insert normalization proposals
// ──────────────────────────────────────────────────────────────────────────────
// contactUpdatedAt is stored as a raw DB string (no JS Date conversion) so
// microsecond precision is preserved end-to-end for the SQL CAS predicate.
async function insertProposalBatch(
  client: pg.PoolClient,
  runId: string,
  proposals: Array<{
    contactId: number;
    contactUpdatedAt: string; // raw DB string — no JS Date conversion to preserve microsecond precision
    proposalType: string;
    fieldName: string;
    currentValue: string | null;
    proposedValue: string;
    confidence: number;
    beforeValues: Record<string, unknown>;
  }>,
): Promise<number> {
  if (proposals.length === 0) return 0;

  let actuallyInserted = 0;
  for (const p of proposals) {
    // ON CONFLICT DO NOTHING: idempotent on resume (unique index on run_id, contact_id, proposal_type, field_name).
    // Use RETURNING id to count the rows actually inserted (0 when the row already existed).
    const r = await client.query(
      `INSERT INTO contact_normalization_proposals
         (run_id, contact_id, proposal_type, field_name, current_value, proposed_value,
          contact_updated_at, before_values, confidence)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
       ON CONFLICT (run_id, contact_id, proposal_type, field_name) DO NOTHING
       RETURNING id`,
      [
        runId, p.contactId, p.proposalType, p.fieldName,
        p.currentValue, p.proposedValue,
        p.contactUpdatedAt, JSON.stringify(p.beforeValues), p.confidence,
      ],
    );
    actuallyInserted += r.rowCount ?? 0;
  }
  return actuallyInserted;
}

// ──────────────────────────────────────────────────────────────────────────────
// Main runner
// ──────────────────────────────────────────────────────────────────────────────
export async function executeReconciliationRun(runId: string, owner: string): Promise<void> {
  const bgProfile = process.env.BACKGROUND_JOB_PROFILE ?? "off";
  if (bgProfile !== "off") {
    // Fence with lease_owner AND status='running' so a stale invocation cannot
    // overwrite an admin pause/cancel or a resumed run owned by a different worker.
    await pool.query(
      `UPDATE contact_reconciliation_runs SET status='failed', failure_reason=$2, failed_at=now(), updated_at=now()
       WHERE id=$1 AND lease_owner=$3 AND status='running'`,
      [runId, `BACKGROUND_JOB_PROFILE is '${bgProfile}', must be 'off' to run reconciliation`, owner],
    );
    return;
  }

  const client = await pool.connect();
  let paused = false;

  try {
    // Get the source census run info AND rules_version
    const runR = await client.query(
      `SELECT source_census_run_id, rules_version, quality_flagged_contacts,
              quality_signal_instances, suppressed_cosmetic_candidates
       FROM contact_reconciliation_runs WHERE id = $1`,
      [runId],
    );
    if (runR.rows.length === 0) return;

    const sourceCensusRunId: string = runR.rows[0].source_census_run_id;
    const rulesVersion: string = runR.rows[0].rules_version ?? RULES_VERSION;
    const isQualityRun = rulesVersion === QUALITY_RULES_VERSION;

    // Get census watermark
    const censusR = await client.query(
      `SELECT max_contact_id_at_start, denominator_at_start FROM contact_census_runs WHERE id = $1`,
      [sourceCensusRunId],
    );
    if (censusR.rows.length === 0) {
      // Fence with lease_owner AND status='running' — a stale invocation must not
      // mark a run already paused/cancelled/resumed-by-another-worker as failed.
      await pool.query(
        `UPDATE contact_reconciliation_runs SET status='failed', failure_reason=$2, failed_at=now(), updated_at=now()
         WHERE id=$1 AND lease_owner=$3 AND status='running'`,
        [runId, `Source census run ${sourceCensusRunId} not found`, owner],
      );
      return;
    }

    const maxContactId = parseInt(censusR.rows[0].max_contact_id_at_start, 10);
    const denominator = parseInt(censusR.rows[0].denominator_at_start, 10);

    // Read the current run row to restore checkpoint state (supports resume).
    const thisRunR = await client.query(
      `SELECT cursor_contact_census_member_id, total_processed, total_proposed,
              lane_counts, dimension_counts,
              quality_flagged_contacts, quality_signal_instances, suppressed_cosmetic_candidates
       FROM contact_reconciliation_runs WHERE id = $1`,
      [runId],
    );
    const thisRun = thisRunR.rows[0];

    await casUpdateRun(runId, owner, {
      maxContactIdAtStart: maxContactId,
      denominatorAtStart: denominator,
    });

    // Load shared-phone data from census run (legacy path for non-quality runs)
    const sharedPhoneMap = isQualityRun
      ? new Map<string, number>()
      : await loadSharedPhoneData(client, sourceCensusRunId);

    // Load quality context once (quality-v1 runs only)
    let qualityCtx: QualityRunContext | null = null;
    if (isQualityRun) {
      const [sharedPhoneRows, sharedEmailRows] = await Promise.all([
        loadQualitySharedPhones(client, sourceCensusRunId),
        loadQualitySharedEmails(client, sourceCensusRunId),
      ]);
      qualityCtx = buildQualityRunContext(new Date(), sharedPhoneRows, sharedEmailRows);
      console.log(
        `[ReconRunner] Quality context loaded: shared_phones=${sharedPhoneRows.length}` +
        ` shared_emails=${sharedEmailRows.length}`,
      );
    }

    // Restore checkpoint — if cursor > 0 this is a resumed run
    const laneCounts: Record<string, number> =
      (typeof thisRun?.lane_counts === "object" && thisRun?.lane_counts !== null)
        ? thisRun.lane_counts as Record<string, number>
        : {};
    const dimensionCounts: Record<string, Record<string, number>> =
      (typeof thisRun?.dimension_counts === "object" && thisRun?.dimension_counts !== null)
        ? thisRun.dimension_counts as Record<string, Record<string, number>>
        : {
            r1_name: {}, r2_email: {}, r3_phone: {}, r4_company: {}, r5_vertical: {},
            r6_duplicate_risk: {}, r7_business_gap: {}, r8_org_aggregation: {},
            r9_normalization: {}, r10_cluster: {}, r11_action: {},
          };

    let cursor = parseInt(String(thisRun?.cursor_contact_census_member_id ?? "0"), 10) || 0;
    let totalProcessed = parseInt(String(thisRun?.total_processed ?? "0"), 10) || 0;
    let totalProposed = parseInt(String(thisRun?.total_proposed ?? "0"), 10) || 0;
    let totalOrgCandidates = 0;
    let totalClusters = 0;
    // Quality counters (restored from checkpoint for resume)
    let qualityFlaggedContacts = parseInt(String(thisRun?.quality_flagged_contacts ?? "0"), 10) || 0;
    let qualitySignalInstances = parseInt(String(thisRun?.quality_signal_instances ?? "0"), 10) || 0;
    let suppressedCosmeticCandidates = parseInt(String(thisRun?.suppressed_cosmetic_candidates ?? "0"), 10) || 0;
    let batchNum = 0;

    while (true) {
      // CAS check
      const statusR = await client.query(
        `SELECT status, lease_owner FROM contact_reconciliation_runs WHERE id = $1`, [runId],
      );
      const currentStatus = statusR.rows[0]?.status;
      const currentOwner = statusR.rows[0]?.lease_owner;

      if (currentOwner !== owner) {
        console.warn(`[ReconRunner] Lease stolen on run ${runId}`);
        return;
      }
      if (currentStatus === "cancelled") return;
      if (currentStatus === "paused") { paused = true; break; }
      if (currentStatus !== "running") return;

      // Pool pressure
      const pressure = (pool as any).waitingCount ?? 0;
      if (pressure > 0) {
        await new Promise(r => setTimeout(r, POOL_PRESSURE_BACKOFF_MS));
        const secondPressure = (pool as any).waitingCount ?? 0;
        if (secondPressure > 0) {
          const pressurePauseR = await pool.query(
            `UPDATE contact_reconciliation_runs
             SET status='paused', pause_reason=$2, cursor_contact_census_member_id=$3,
                 total_processed=$4, lane_counts=$5, dimension_counts=$6, updated_at=now()
             WHERE id=$1 AND lease_owner=$7 AND status='running'`,
            [runId, `Pool pressure: waitingCount=${secondPressure}`, cursor,
             totalProcessed, JSON.stringify(laneCounts), JSON.stringify(dimensionCounts), owner],
          );
          // If 0 rows, the run was already cancelled/paused externally — stop.
          if ((pressurePauseR.rowCount ?? 0) === 0) return;
          paused = true;
          break;
        }
      }

      // Health check
      if (batchNum > 0 && batchNum % HEALTH_CHECK_EVERY_N === 0) {
        if (!(await isLoginHealthy())) {
          const healthPauseR = await pool.query(
            `UPDATE contact_reconciliation_runs SET status='paused', pause_reason=$2, cursor_contact_census_member_id=$3, total_processed=$4, updated_at=now()
             WHERE id=$1 AND lease_owner=$5 AND status='running'`,
            [runId, "Login health probe failed", cursor, totalProcessed, owner],
          );
          if ((healthPauseR.rowCount ?? 0) === 0) return;
          paused = true;
          break;
        }
      }

      // Lease refresh
      if (batchNum > 0 && batchNum % LEASE_REFRESH_EVERY_N === 0) {
        if (!(await refreshLease(runId, owner))) {
          console.warn(`[ReconRunner] Lease not renewed for run ${runId}`);
          return;
        }
      }

      // Fetch batch of census members with current contact data.
      // quality-v1 extends the SELECT with additional compliance/suppression fields.
      const batchStart = Date.now();
      const batchR = await client.query(`
        SELECT
          ccm.id AS census_member_id,
          ccm.contact_id,
          ccm.primary_lane AS census_lane,
          c.first_name, c.last_name, c.email, c.phone, c.company_name,
          c.vertical, c.vertical_source, c.manual_vertical_override,
          c.do_not_contact, c.suppression_reason, c.email_status,
          c.bounce_status, c.complaint_status, c.consent_tier,
          c.record_class, c.ghl_contact_id, c.lead_source,
          c.business_id, c.updated_at::text AS contact_updated_at,
          -- quality-v1 additional fields (safe to include in all runs; NULL for old contacts)
          c.email_validation_updated_at,
          c.do_not_auto_contact,
          c.dnc_reason, c.dnc_date,
          c.opted_out_email, c.opt_out_status,
          c.unsubscribe_status,
          c.sms_status, c.sms_consent_status,
          c.next_allowed_contact_date
        FROM contact_census_members ccm
        JOIN contacts c ON c.id = ccm.contact_id
        WHERE ccm.run_id = $1
          AND ccm.id > $2
          AND c.archived_at IS NULL
        ORDER BY ccm.id ASC
        LIMIT $3
      `, [sourceCensusRunId, cursor, BATCH_SIZE]);

      const batchDuration = Date.now() - batchStart;
      if (batchDuration > BATCH_TIMEOUT_MS) {
        const timeoutPauseR = await pool.query(
          `UPDATE contact_reconciliation_runs SET status='paused', pause_reason=$2, cursor_contact_census_member_id=$3, total_processed=$4, updated_at=now()
           WHERE id=$1 AND lease_owner=$5 AND status='running'`,
          [runId, `Batch query exceeded ${BATCH_TIMEOUT_MS}ms`, cursor, totalProcessed, owner],
        );
        if ((timeoutPauseR.rowCount ?? 0) === 0) return;
        paused = true;
        break;
      }

      if (batchR.rows.length === 0) break;

      // Load crosswalk decisions for this batch (quality-v1 only, set-based — not N+1)
      const batchContactIds = batchR.rows.map((r: any) => r.contact_id as number);
      const crosswalkMap = isQualityRun
        ? await loadCrosswalkDecisions(client, batchContactIds)
        : new Map<number, "candidate" | "conflict">();

      const classifiedResults: MemberBatchRow[] = [];
      const orgBatch: Array<{ contactId: number; companyName: string }> = [];
      const dupBatch: Array<{ contactId: number; phone: string }> = [];
      const proposalBatch: Array<{
        contactId: number;
        contactUpdatedAt: string;
        proposalType: string;
        fieldName: string;
        currentValue: string | null;
        proposedValue: string;
        confidence: number;
        beforeValues: Record<string, unknown>;
      }> = [];

      // Quality-v1 per-batch counters
      let batchQualityFlagged = 0;
      let batchQualityInstances = 0;
      let batchSuppressedCosmetic = 0;

      for (const raw of batchR.rows) {
        const normalizedPhone = raw.phone?.trim() || null;
        const companyCount = normalizedPhone ? (sharedPhoneMap.get(normalizedPhone) ?? 0) : 0;

        const row: ReconciliationContactRow = {
          id: raw.contact_id,
          firstName: raw.first_name || null,
          lastName: raw.last_name || null,
          email: raw.email || null,
          phone: raw.phone || null,
          companyName: raw.company_name || null,
          vertical: raw.vertical || null,
          verticalSource: raw.vertical_source || null,
          manualVerticalOverride: raw.manual_vertical_override,
          doNotContact: raw.do_not_contact,
          suppressionReason: raw.suppression_reason || null,
          emailStatus: raw.email_status || null,
          bounceStatus: raw.bounce_status || null,
          complaintStatus: raw.complaint_status || null,
          consentTier: raw.consent_tier || null,
          recordClass: raw.record_class || null,
          ghlContactId: raw.ghl_contact_id || null,
          leadSource: raw.lead_source || null,
          businessId: raw.business_id != null ? parseInt(raw.business_id) : null,
          hasDeal: false,
          censusLane: raw.census_lane || null,
          normalizedPhone,
          isSharedPhone: companyCount > 0,
          sharedPhoneCompanyCount: companyCount,
        };

        const result = classifyReconciliation(row, runId, parseInt(raw.census_member_id)) as MemberBatchRow;

        // ── quality-v1 path: classify quality signals, suppress cosmetic proposals ──
        if (isQualityRun && qualityCtx) {
          const crosswalkDec = crosswalkMap.get(raw.contact_id as number) ?? null;
          const qInput: QualityContactInput = {
            contactId: raw.contact_id,
            firstName: raw.first_name || null,
            lastName: raw.last_name || null,
            phone: raw.phone || null,
            email: raw.email || null,
            emailStatus: raw.email_status || null,
            emailValidationUpdatedAt: raw.email_validation_updated_at
              ? new Date(raw.email_validation_updated_at) : null,
            doNotContact: raw.do_not_contact ?? false,
            doNotAutoContact: raw.do_not_auto_contact ?? false,
            dncReason: raw.dnc_reason || null,
            dncDate: raw.dnc_date ? new Date(raw.dnc_date) : null,
            suppressionReason: raw.suppression_reason || null,
            optedOutEmail: raw.opted_out_email ?? null,
            optOutStatus: raw.opt_out_status || null,
            unsubscribeStatus: raw.unsubscribe_status || null,
            bounceStatus: raw.bounce_status || null,
            complaintStatus: raw.complaint_status || null,
            smsStatus: raw.sms_status || null,
            smsConsentStatus: raw.sms_consent_status || null,
            consentTier: raw.consent_tier || null,
            nextAllowedContactDate: raw.next_allowed_contact_date
              ? new Date(raw.next_allowed_contact_date) : null,
            businessId: raw.business_id != null ? parseInt(raw.business_id) : null,
            companyName: raw.company_name || null,
            crosswalkDecisionType: crosswalkDec ?? "none",
          };
          const qResult = classifyContactQuality(qInput, qualityCtx);
          result.qualitySignalCodes = qResult.signalCodes;
          result.qualitySignalDetails = qResult.signalDetails;

          // Count quality signals
          if (qResult.signalCodes.length > 0) batchQualityFlagged++;
          batchQualityInstances += qResult.signalCodes.length;

          // Suppress cosmetic proposals: count what WOULD have been generated but do NOT insert
          const rawContactUpdatedAt: string = String(raw.contact_updated_at);
          const wouldBeProposals = generateProposals(row, result, new Date(rawContactUpdatedAt));
          batchSuppressedCosmetic += wouldBeProposals.length;
          // Do NOT push to proposalBatch for quality-v1 runs
        } else {
          // ── Legacy path: generate normalization proposals ────────────────────
          const rawContactUpdatedAt: string = String(raw.contact_updated_at);
          const proposals = generateProposals(row, result, new Date(rawContactUpdatedAt));
          for (const p of proposals) {
            proposalBatch.push({
              contactId: raw.contact_id,
              contactUpdatedAt: rawContactUpdatedAt,
              proposalType: p.proposalType,
              fieldName: p.fieldName,
              currentValue: p.currentValue,
              proposedValue: p.proposedValue,
              confidence: p.confidence,
              beforeValues: {
                first_name: raw.first_name,
                last_name: raw.last_name,
                email: raw.email,
                phone: raw.phone,
                company_name: raw.company_name,
              },
            });
          }
        }

        classifiedResults.push(result);

        // Tally lane/dimension counts
        laneCounts[result.primaryLane] = (laneCounts[result.primaryLane] ?? 0) + 1;
        dimensionCounts.r1_name[result.nameQualityState] = (dimensionCounts.r1_name[result.nameQualityState] ?? 0) + 1;
        dimensionCounts.r2_email[result.emailQualityState] = (dimensionCounts.r2_email[result.emailQualityState] ?? 0) + 1;
        dimensionCounts.r3_phone[result.phoneQualityState] = (dimensionCounts.r3_phone[result.phoneQualityState] ?? 0) + 1;
        dimensionCounts.r4_company[result.companyQualityState] = (dimensionCounts.r4_company[result.companyQualityState] ?? 0) + 1;
        dimensionCounts.r5_vertical[result.verticalState] = (dimensionCounts.r5_vertical[result.verticalState] ?? 0) + 1;
        dimensionCounts.r6_duplicate_risk[result.duplicateRiskState] = (dimensionCounts.r6_duplicate_risk[result.duplicateRiskState] ?? 0) + 1;
        dimensionCounts.r7_business_gap[result.businessGapState] = (dimensionCounts.r7_business_gap[result.businessGapState] ?? 0) + 1;
        dimensionCounts.r8_org_aggregation[result.orgAggregationState] = (dimensionCounts.r8_org_aggregation[result.orgAggregationState] ?? 0) + 1;
        dimensionCounts.r9_normalization[result.normalizationOpportunity] = (dimensionCounts.r9_normalization[result.normalizationOpportunity] ?? 0) + 1;
        dimensionCounts.r10_cluster[result.clusterCandidacyState] = (dimensionCounts.r10_cluster[result.clusterCandidacyState] ?? 0) + 1;
        dimensionCounts.r11_action[result.overallActionState] = (dimensionCounts.r11_action[result.overallActionState] ?? 0) + 1;

        // Org aggregation batch
        if (result.orgAggregationState === "aggregatable" && result.hasCompanyName) {
          orgBatch.push({ contactId: raw.contact_id, companyName: raw.company_name });
        }

        // Duplicate cluster batch (legacy: uses raw phone; quality-v1: uses SHARED_PHONE_REVIEW signal)
        if (!isQualityRun && result.duplicateRiskState === "shared_phone_multi_company" && normalizedPhone) {
          dupBatch.push({ contactId: raw.contact_id, phone: normalizedPhone });
        } else if (isQualityRun && result.qualitySignalCodes?.includes("SHARED_PHONE_REVIEW") && normalizedPhone) {
          // Use normalized NANP phone for quality-v1 clusters
          const nanp = normalizeNanpPhone(raw.phone);
          if (nanp) dupBatch.push({ contactId: raw.contact_id, phone: nanp });
        }

        totalProcessed++;
      }

      // ── Atomic batch commit ─────────────────────────────────────────────────
      const nextCursor = batchR.rows[batchR.rows.length - 1].census_member_id;
      let insertedCount = 0;
      let batchCommitted = false;
      try {
        await client.query("BEGIN");

        await insertMemberBatch(client, classifiedResults);
        await upsertOrgCandidates(client, runId, orgBatch);
        if (!isQualityRun) {
          await upsertDuplicateClusters(client, runId, dupBatch, sharedPhoneMap);
          insertedCount = await insertProposalBatch(client, runId, proposalBatch);
        } else {
          // Quality-v1: clusters keyed by normalized NANP phone
          const nanpMap = new Map<string, number>();
          for (const d of dupBatch) nanpMap.set(d.phone, 2); // threshold already passed
          await upsertDuplicateClusters(client, runId, dupBatch, nanpMap);
        }

        // Build checkpoint update for quality-v1 vs legacy
        const qualityUpdates = isQualityRun ? `
          quality_flagged_contacts = quality_flagged_contacts + ${batchQualityFlagged},
          quality_signal_instances = quality_signal_instances + ${batchQualityInstances},
          suppressed_cosmetic_candidates = suppressed_cosmetic_candidates + ${batchSuppressedCosmetic},
        ` : "";

        const cpR = await client.query(
          `UPDATE contact_reconciliation_runs
           SET cursor_contact_census_member_id=$2, total_processed=$3,
               total_proposed=$4, lane_counts=$5, dimension_counts=$6,
               ${qualityUpdates}updated_at=now()
           WHERE id=$1 AND lease_owner=$7 AND status='running'`,
          [runId, nextCursor, totalProcessed, totalProposed + insertedCount,
           JSON.stringify(laneCounts), JSON.stringify(dimensionCounts), owner],
        );

        if ((cpR.rowCount ?? 0) === 0) {
          await client.query("ROLLBACK");
          console.warn(`[ReconRunner] Batch rolled back for run ${runId} — status changed or lease lost`);
          return;
        }

        await client.query("COMMIT");
        batchCommitted = true;
      } catch (batchErr) {
        await client.query("ROLLBACK").catch(() => {});
        throw batchErr;
      }

      if (!batchCommitted) return;

      totalProposed += insertedCount;
      qualityFlaggedContacts += batchQualityFlagged;
      qualitySignalInstances += batchQualityInstances;
      suppressedCosmeticCandidates += batchSuppressedCosmetic;
      cursor = nextCursor;
      batchNum++;
    }

    if (!paused) {
      // Verify run is still in 'running' state before marking complete.
      const preCompleteR = await pool.query(
        `SELECT status FROM contact_reconciliation_runs WHERE id = $1 AND lease_owner = $2`,
        [runId, owner],
      );
      if (preCompleteR.rows[0]?.status !== "running") {
        console.warn(`[ReconRunner] Run ${runId} status changed before completion — not marking complete`);
        return;
      }

      // Count final totals
      const [orgCount, clusterCount] = await Promise.all([
        pool.query(`SELECT COUNT(*) AS n FROM contact_organization_candidates WHERE run_id = $1`, [runId]),
        pool.query(`SELECT COUNT(*) AS n FROM contact_duplicate_clusters WHERE run_id = $1`, [runId]),
      ]);

      // Compute final quality_signal_counts breakdown for quality-v1 runs
      let finalQualitySignalCounts: Record<string, number> = {};
      if (isQualityRun) {
        const qscR = await pool.query(
          `SELECT unnest(quality_signal_codes) AS code, COUNT(*) AS n
           FROM contact_reconciliation_members
           WHERE run_id = $1
           GROUP BY 1`,
          [runId],
        );
        for (const row of qscR.rows) {
          finalQualitySignalCounts[row.code as string] = parseInt(row.n, 10);
        }
      }

      const finR = await pool.query(
        `UPDATE contact_reconciliation_runs SET
           status='completed', completed_at=now(), total_processed=$2,
           total_proposed=$3, total_org_candidates=$4, total_clusters=$5,
           lane_counts=$6, dimension_counts=$7,
           cursor_contact_census_member_id=$8,
           quality_flagged_contacts=$10,
           quality_signal_instances=$11,
           suppressed_cosmetic_candidates=$12,
           quality_signal_counts=$13,
           updated_at=now()
         WHERE id=$1 AND lease_owner=$9 AND status='running'`,
        [
          runId, totalProcessed, totalProposed,
          parseInt(orgCount.rows[0].n, 10),
          parseInt(clusterCount.rows[0].n, 10),
          JSON.stringify(laneCounts), JSON.stringify(dimensionCounts),
          cursor, owner,
          qualityFlaggedContacts,
          qualitySignalInstances,
          suppressedCosmeticCandidates,
          JSON.stringify(finalQualitySignalCounts),
        ],
      );
      if ((finR.rowCount ?? 0) === 0) {
        console.warn(`[ReconRunner] Finalization skipped for run ${runId} — status changed or lease lost before complete`);
      }
    }
  } catch (err: any) {
    console.error("[ReconRunner] Fatal error:", err.message);
    try {
      // Must predicate on lease_owner AND status='running' to avoid overwriting an
      // admin-issued pause or cancel that may have occurred before the error surfaced.
      await pool.query(
        `UPDATE contact_reconciliation_runs SET status='failed', failure_reason=$2, failed_at=now(), updated_at=now()
         WHERE id=$1 AND lease_owner=$3 AND status='running'`,
        [runId, String(err.message ?? err), owner],
      );
    } catch { /* ignore */ }
  } finally {
    client.release();
  }
}

// ──────────────────────────────────────────────────────────────────────────────
// Create and start a new reconciliation run
// ──────────────────────────────────────────────────────────────────────────────
export async function createAndStartReconRun(opts: {
  sourceCensusRunId: string;
  requestedBy: string;
  environmentLabel: string;
  rulesVersion?: string;
}): Promise<string> {
  const owner = leaseOwnerTag();
  const rulesVersion = opts.rulesVersion ?? RULES_VERSION;

  const r = await pool.query(
    `INSERT INTO contact_reconciliation_runs
       (source_census_run_id, environment_label, rules_version, requested_by,
        status, lease_owner, lease_expires_at)
     VALUES ($1, $2, $3, $4, 'running', $5, now() + interval '${LEASE_DURATION_SECS} seconds')
     RETURNING id`,
    [opts.sourceCensusRunId, opts.environmentLabel, rulesVersion, opts.requestedBy, owner],
  );
  const runId: string = r.rows[0].id;

  setImmediate(() =>
    executeReconciliationRun(runId, owner).catch(e =>
      console.error("[ReconRunner] Unhandled:", e),
    ),
  );

  return runId;
}

// ──────────────────────────────────────────────────────────────────────────────
// Resume a paused run
// ──────────────────────────────────────────────────────────────────────────────
export async function resumeReconRun(runId: string): Promise<boolean> {
  const owner = leaseOwnerTag();
  const r = await pool.query(
    `UPDATE contact_reconciliation_runs
     SET status='running', pause_reason=NULL,
         lease_owner=$2, lease_expires_at=now() + interval '${LEASE_DURATION_SECS} seconds',
         updated_at=now()
     WHERE id=$1 AND status='paused'
     RETURNING id`,
    [runId, owner],
  );
  if ((r.rowCount ?? 0) === 0) return false;

  setImmediate(() =>
    executeReconciliationRun(runId, owner).catch(e =>
      console.error("[ReconRunner] Resume error:", e),
    ),
  );
  return true;
}
