import { storage } from "../storage";
import { sendGhlEmailForMerchant, isGhlConfigured } from "./ghl";
import type { InsertNotification } from "@shared/schema";

function parseCurrency(v: string | null | undefined): number {
  if (!v) return 0;
  const n = parseFloat(v.replace(/[^0-9.\-]/g, ""));
  return isNaN(n) ? 0 : n;
}

function getEstHour(): number {
  const now = new Date();
  const estString = now.toLocaleString("en-US", { timeZone: "America/New_York" });
  return new Date(estString).getHours();
}

function getEstDayOfWeek(): number {
  const now = new Date();
  const estString = now.toLocaleString("en-US", { timeZone: "America/New_York" });
  return new Date(estString).getDay();
}

export async function buildDailyDigest(): Promise<{
  html: string;
  summary: Record<string, any>;
}> {
  const now = new Date();
  const twentyFourHoursAgo = new Date(now.getTime() - 24 * 60 * 60 * 1000);

  const [allDeals, allContacts, allTickets, allTasks] = await Promise.all([
    storage.getDeals(),
    storage.getContacts(),
    storage.getTickets(),
    storage.getTasks(),
  ]);

  const newLeads = allContacts.filter(
    (c) => c.createdAt && new Date(c.createdAt) >= twentyFourHoursAgo
  );
  const dealsProgressed = allDeals.filter(
    (d) =>
      d.updatedAt &&
      new Date(d.updatedAt) >= twentyFourHoursAgo &&
      d.stage !== "New Lead"
  );
  const closedWon = allDeals.filter(
    (d) =>
      d.stage === "Closed Won" &&
      d.closedAt &&
      new Date(d.closedAt) >= twentyFourHoursAgo
  );
  const closedLost = allDeals.filter(
    (d) =>
      d.stage === "Closed Lost" &&
      d.closedAt &&
      new Date(d.closedAt) >= twentyFourHoursAgo
  );
  const tasksCompleted = allTasks.filter(
    (t) =>
      t.status === "completed" &&
      t.completedAt &&
      new Date(t.completedAt) >= twentyFourHoursAgo
  );
  const tasksOverdue = allTasks.filter(
    (t) =>
      t.status !== "completed" &&
      t.dueDate &&
      new Date(t.dueDate) < now
  );
  const newTickets = allTickets.filter(
    (t) => t.createdAt && new Date(t.createdAt) >= twentyFourHoursAgo
  );
  const resolvedTickets = allTickets.filter(
    (t) => t.resolvedAt && new Date(t.resolvedAt) >= twentyFourHoursAgo
  );

  const summary = {
    date: now.toLocaleDateString("en-US", { timeZone: "America/New_York" }),
    newLeadsCount: newLeads.length,
    dealsProgressedCount: dealsProgressed.length,
    closedWonCount: closedWon.length,
    closedLostCount: closedLost.length,
    tasksCompletedCount: tasksCompleted.length,
    tasksOverdueCount: tasksOverdue.length,
    newTicketsCount: newTickets.length,
    resolvedTicketsCount: resolvedTickets.length,
  };

  const newLeadsList = newLeads
    .slice(0, 10)
    .map(
      (c) =>
        `<li>${c.firstName} ${c.lastName}${c.companyName ? ` — ${c.companyName}` : ""}${c.leadSource ? ` (${c.leadSource})` : ""}</li>`
    )
    .join("");

  const overdueList = tasksOverdue
    .slice(0, 10)
    .map(
      (t) =>
        `<li>${t.title}${t.assignedTo ? ` — ${t.assignedTo}` : ""} (due ${t.dueDate ? new Date(t.dueDate).toLocaleDateString() : "N/A"})</li>`
    )
    .join("");

  const html = `
<h2>Liberty Bancard — Daily Activity Digest</h2>
<p><strong>Date:</strong> ${summary.date}</p>
<hr>
<h3>New Leads (${summary.newLeadsCount})</h3>
${newLeads.length > 0 ? `<ul>${newLeadsList}</ul>` : "<p>No new leads today.</p>"}
<h3>Pipeline Activity</h3>
<ul>
  <li>Deals Progressed: <strong>${summary.dealsProgressedCount}</strong></li>
  <li>Closed Won: <strong>${summary.closedWonCount}</strong></li>
  <li>Closed Lost: <strong>${summary.closedLostCount}</strong></li>
</ul>
<h3>Tasks</h3>
<ul>
  <li>Completed Today: <strong>${summary.tasksCompletedCount}</strong></li>
  <li>Currently Overdue: <strong>${summary.tasksOverdueCount}</strong></li>
</ul>
${tasksOverdue.length > 0 ? `<p><strong>Overdue Tasks:</strong></p><ul>${overdueList}</ul>` : ""}
<h3>Support</h3>
<ul>
  <li>New Tickets: <strong>${summary.newTicketsCount}</strong></li>
  <li>Resolved: <strong>${summary.resolvedTicketsCount}</strong></li>
</ul>
<p style="color:#888;font-size:12px;">Auto-generated by Liberty Bancard CRM at ${now.toLocaleString("en-US", { timeZone: "America/New_York" })} EST</p>`;

  return { html, summary };
}

export async function buildWeeklyDigest(): Promise<{
  html: string;
  summary: Record<string, any>;
}> {
  const now = new Date();
  const sevenDaysAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);

  const [allDeals, allContacts, allTickets, allTasks] = await Promise.all([
    storage.getDeals(),
    storage.getContacts(),
    storage.getTickets(),
    storage.getTasks(),
  ]);

  const newLeads = allContacts.filter(
    (c) => c.createdAt && new Date(c.createdAt) >= sevenDaysAgo
  ).length;
  const newDeals = allDeals.filter(
    (d) => d.createdAt && new Date(d.createdAt) >= sevenDaysAgo
  ).length;
  const closedWon = allDeals.filter(
    (d) =>
      d.stage === "Closed Won" &&
      d.closedAt &&
      new Date(d.closedAt) >= sevenDaysAgo
  );
  const closedLost = allDeals.filter(
    (d) =>
      d.stage === "Closed Lost" &&
      d.closedAt &&
      new Date(d.closedAt) >= sevenDaysAgo
  ).length;
  const proposalsSent = allDeals.filter(
    (d) =>
      d.stage === "Proposal Sent" &&
      d.updatedAt &&
      new Date(d.updatedAt) >= sevenDaysAgo
  ).length;
  const newTickets = allTickets.filter(
    (t) => t.createdAt && new Date(t.createdAt) >= sevenDaysAgo
  ).length;
  const resolvedTickets = allTickets.filter(
    (t) => t.resolvedAt && new Date(t.resolvedAt) >= sevenDaysAgo
  ).length;
  const overdueTaskCount = allTasks.filter(
    (t) => t.status !== "completed" && t.dueDate && new Date(t.dueDate) < now
  ).length;

  const weeklyRevenue = closedWon.reduce(
    (s, d) => s + parseCurrency(d.estimatedGrossProfitMonthly),
    0
  );
  const conversionRate =
    newDeals > 0 ? Math.round((closedWon.length / newDeals) * 100) : 0;

  const sourceBreakdown: Record<string, number> = {};
  allContacts
    .filter((c) => c.createdAt && new Date(c.createdAt) >= sevenDaysAgo)
    .forEach((c) => {
      const src = c.utmSource || c.leadSource || "direct";
      sourceBreakdown[src] = (sourceBreakdown[src] || 0) + 1;
    });

  const topSources = Object.entries(sourceBreakdown)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5);

  const ownerWins: Record<string, number> = {};
  closedWon.forEach((d) => {
    const owner = d.owner || "Unassigned";
    ownerWins[owner] = (ownerWins[owner] || 0) + 1;
  });
  const leaderboard = Object.entries(ownerWins)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5);

  const activeSalesDeals = allDeals.filter(
    (d) =>
      d.pipeline === "sales" &&
      d.stage !== "Closed Won" &&
      d.stage !== "Closed Lost"
  );
  const pipelineValue = activeSalesDeals.reduce(
    (s, d) => s + parseCurrency(d.estimatedGrossProfitMonthly),
    0
  );

  const wonDealsWithDates = closedWon.filter(
    (d) => d.createdAt && d.closedAt
  );
  const avgCycleTimeDays =
    wonDealsWithDates.length > 0
      ? Math.round(
          wonDealsWithDates.reduce(
            (s, d) =>
              s +
              (new Date(d.closedAt!).getTime() -
                new Date(d.createdAt!).getTime()) /
                (1000 * 60 * 60 * 24),
            0
          ) / wonDealsWithDates.length
        )
      : 0;

  const summary = {
    period: `${sevenDaysAgo.toLocaleDateString()} - ${now.toLocaleDateString()}`,
    newLeads,
    newDeals,
    proposalsSent,
    closedWonCount: closedWon.length,
    closedLost,
    conversionRate,
    weeklyRevenue: Math.round(weeklyRevenue),
    pipelineValue: Math.round(pipelineValue),
    avgCycleTimeDays,
    newTickets,
    resolvedTickets,
    overdueTaskCount,
    topSources,
    leaderboard,
  };

  const html = `
<h2>Liberty Bancard — Weekly KPI Digest</h2>
<p><strong>Period:</strong> ${summary.period}</p>
<hr>
<h3>Pipeline Overview</h3>
<ul>
  <li>Active Pipeline Value: <strong>$${summary.pipelineValue.toLocaleString()}/mo</strong></li>
  <li>New Leads: <strong>${summary.newLeads}</strong></li>
  <li>New Deals: <strong>${summary.newDeals}</strong></li>
  <li>Proposals Sent: <strong>${summary.proposalsSent}</strong></li>
  <li>Closed Won: <strong>${summary.closedWonCount}</strong></li>
  <li>Closed Lost: <strong>${summary.closedLost}</strong></li>
  <li>Win Rate: <strong>${summary.conversionRate}%</strong></li>
  <li>Avg Deal Cycle: <strong>${summary.avgCycleTimeDays} days</strong></li>
  <li>Revenue (Est.): <strong>$${summary.weeklyRevenue.toLocaleString()}</strong></li>
</ul>
<h3>Support</h3>
<ul>
  <li>New Tickets: <strong>${summary.newTickets}</strong></li>
  <li>Resolved: <strong>${summary.resolvedTickets}</strong></li>
  <li>Overdue Tasks: <strong>${summary.overdueTaskCount}</strong></li>
</ul>
<h3>Top Lead Sources</h3>
<ul>
  ${topSources.map(([s, c]) => `<li>${s}: <strong>${c}</strong></li>`).join("")}
</ul>
${
  leaderboard.length > 0
    ? `<h3>Rep Leaderboard (Closed Won)</h3>
<ol>
  ${leaderboard.map(([name, wins]) => `<li>${name}: <strong>${wins} win${wins > 1 ? "s" : ""}</strong></li>`).join("")}
</ol>`
    : ""
}
<p style="color:#888;font-size:12px;">Auto-generated by Liberty Bancard CRM</p>`;

  return { html, summary };
}

export async function createPreferenceAwareNotification(
  notif: InsertNotification,
  eventType?: string
): Promise<void> {
  if (eventType && notif.recipientId) {
    const prefs = await storage.getNotificationPreferences(notif.recipientId);
    const pref = prefs.find((p) => p.eventType === eventType);
    if (pref && pref.enabled === false) return;
  }
  await storage.createNotification(notif);
}

async function resolveOwnerEmail(ownerName?: string | null): Promise<string | null> {
  if (!ownerName) return null;
  const allUsers = await storage.getUsersByRole(["admin", "manager", "agent"]);
  const ownerLower = ownerName.toLowerCase().trim();
  const match = allUsers.find((u) => {
    if (u.email && u.email.toLowerCase() === ownerLower) return true;
    if (u.id === ownerName) return true;
    const fullName = [u.firstName, u.lastName].filter(Boolean).join(" ").toLowerCase().trim();
    if (fullName && fullName === ownerLower) return true;
    if (u.firstName && u.firstName.toLowerCase().trim() === ownerLower) return true;
    return false;
  });
  return match?.email || null;
}

async function getDigestRecipients(digestType: "daily" | "weekly"): Promise<string[]> {
  const recipients: string[] = [];
  const adminManagerUsers = await storage.getUsersByRole(["admin", "manager"]);

  for (const user of adminManagerUsers) {
    if (!user.email) continue;
    const prefs = await storage.getNotificationPreferences(user.id);
    const eventType = digestType === "daily" ? "daily_digest" : "weekly_digest";
    const pref = prefs.find((p) => p.eventType === eventType);
    const optedIn = digestType === "daily"
      ? (pref ? !!pref.digestDaily : true)
      : (pref ? !!pref.digestWeekly : true);
    if (optedIn) {
      recipients.push(user.email);
    }
  }

  const fallbackEmail = process.env.ADMIN_DIGEST_EMAIL;
  if (recipients.length === 0 && fallbackEmail) {
    recipients.push(fallbackEmail);
  }

  return [...new Set(recipients)];
}

async function getEmailEnabledRecipients(eventType: string): Promise<string[]> {
  const recipients: string[] = [];
  const allPrefs = await storage.getAllNotificationPreferencesByEvent(eventType);
  const enabledPrefs = allPrefs.filter((p) => p.emailEnabled);

  if (enabledPrefs.length > 0) {
    const allUsers = await storage.getUsersByRole(["admin", "manager", "agent"]);
    for (const pref of enabledPrefs) {
      const user = allUsers.find((u) => u.id === pref.userId);
      if (user?.email) {
        recipients.push(user.email);
      }
    }
  }

  const fallbackEmail = process.env.ADMIN_DIGEST_EMAIL;
  if (recipients.length === 0 && fallbackEmail) {
    recipients.push(fallbackEmail);
  }

  return [...new Set(recipients)];
}

export async function sendCriticalEmailNotification(params: {
  eventType: string;
  subject: string;
  body: string;
  recipientEmail?: string;
  ownerName?: string | null;
}): Promise<void> {
  if (!isGhlConfigured()) return;

  const recipients: string[] = [];

  if (params.recipientEmail) {
    recipients.push(params.recipientEmail);
  }

  if (params.ownerName) {
    const ownerEmail = await resolveOwnerEmail(params.ownerName);
    if (ownerEmail && !recipients.includes(ownerEmail)) {
      recipients.push(ownerEmail);
    }
  }

  const prefRecipients = await getEmailEnabledRecipients(params.eventType);
  for (const email of prefRecipients) {
    if (!recipients.includes(email)) {
      recipients.push(email);
    }
  }

  if (recipients.length === 0) {
    const fallback = process.env.ADMIN_DIGEST_EMAIL;
    if (fallback) recipients.push(fallback);
  }

  for (const email of recipients) {
    try {
      await sendGhlEmailForMerchant({
        email,
        subject: params.subject,
        body: params.body,
      });
      console.log(
        `[Notification] Sent ${params.eventType} email to ${email}`
      );
    } catch (err) {
      console.error(
        `[Notification] Failed to send ${params.eventType} email to ${email}:`,
        err
      );
    }
  }
}

export async function checkAndSendDigests(): Promise<void> {
  const estHour = getEstHour();
  const estDay = getEstDayOfWeek();
  const now = new Date();
  const todayStr = now.toLocaleDateString("en-US", {
    timeZone: "America/New_York",
  });

  const lastDailyDigestDate = await storage.getSystemSetting("last_daily_digest_date");
  const lastWeeklyDigestDate = await storage.getSystemSetting("last_weekly_digest_date");
  const lastSdrDigestDate = await storage.getSystemSetting("last_sdr_daily_digest_date");

  if (estHour === 8 && lastSdrDigestDate !== todayStr) {
    await storage.setSystemSetting("last_sdr_daily_digest_date", todayStr);
    try {
      const { buildSdrDailyDigest, sendSdrDailyDigest } = await import("./sdr/operator-digest");
      const digest = await buildSdrDailyDigest();
      await sendSdrDailyDigest(digest);
      console.log("[Digest] SDR daily digest sent");
    } catch (err) {
      console.error("[Digest] SDR daily digest error:", err);
    }
  }

  if (estHour === 8 && lastDailyDigestDate !== todayStr) {
    await storage.setSystemSetting("last_daily_digest_date", todayStr);
    try {
      const { html, summary } = await buildDailyDigest();

      await storage.createNotification({
        channel: "internal",
        title: "Daily Activity Digest",
        message: `${summary.newLeadsCount} new leads, ${summary.closedWonCount} closed won, ${summary.tasksOverdueCount} overdue tasks`,
        type: "info",
        metadata: { digestType: "daily", ...summary },
      });

      if (isGhlConfigured()) {
        const recipients = await getDigestRecipients("daily");
        for (const email of recipients) {
          try {
            await sendGhlEmailForMerchant({
              email,
              subject: `Daily Digest — ${summary.date} — Liberty Bancard`,
              body: html,
            });
            console.log("[Digest] Daily digest sent to", email);
          } catch (emailErr) {
            console.error(`[Digest] Daily digest email to ${email} failed:`, emailErr);
          }
        }
      }

      await storage.createAuditLog({
        action: "daily_digest_sent",
        entityType: "system",
        details: summary,
      });
    } catch (err) {
      console.error("[Digest] Daily digest error:", err);
    }
  }

  if (estHour === 9 && estDay === 1 && lastWeeklyDigestDate !== todayStr) {
    await storage.setSystemSetting("last_weekly_digest_date", todayStr);
    try {
      const { html, summary } = await buildWeeklyDigest();

      await storage.createNotification({
        channel: "internal",
        title: "Weekly KPI Digest",
        message: `${summary.closedWonCount} closed won, ${summary.conversionRate}% win rate, $${summary.weeklyRevenue.toLocaleString()} revenue`,
        type: "info",
        metadata: { digestType: "weekly", ...summary },
      });

      if (isGhlConfigured()) {
        const recipients = await getDigestRecipients("weekly");
        for (const email of recipients) {
          try {
            await sendGhlEmailForMerchant({
              email,
              subject: `Weekly KPI Digest — ${summary.period} — Liberty Bancard`,
              body: html,
            });
            console.log("[Digest] Weekly KPI digest sent to", email);
          } catch (emailErr) {
            console.error(`[Digest] Weekly digest email to ${email} failed:`, emailErr);
          }
        }
      }

      await storage.createAuditLog({
        action: "weekly_digest_sent",
        entityType: "system",
        details: summary,
      });
    } catch (err) {
      console.error("[Digest] Weekly digest error:", err);
    }
  }
}
