/** Pure physical queue identity contract. Keep runtime initialization out. */
export const QUEUE_NAMES = {
  GHL_SYNC: "ghl-sync",
  SLA_CHECKS: "sla-checks",
  SEQUENCES: "sequences",
  ENRICHMENT: "enrichment",
  DISCOVERY: "discovery",
  DIGESTS: "digests",
  MID_INGESTION: "mid-ingestion",
  ONBOARDING_REMINDER: "onboarding-reminder",
  ABANDONED_STATEMENT: "abandoned-statement",
  SYSTEM_AUDIT: "system-audit",
  DB_BACKUP: "db-backup",
  ENROLLMENT_RECOVERY: "enrollment-recovery",
  GHL_ENROLLMENT_RECOVERY: "ghl-enrollment-recovery",
  HEALTH_MONITOR: "health-monitor",
  EXECUTIVE_SNAPSHOT: "executive-snapshot",
  PIPELINE_SILENCE_CHECK: "pipeline-silence-check",
  PROPOSAL_FOLLOWUP: "proposal-followup",
  PARTNER_MONTHLY_DIGEST: "partner-monthly-digest",
  ACTIVATION_MONITOR: "activation-monitor",
  MERCHANT_SUCCESS: "merchant-success",
  WINBACK_OUTREACH: "winback-outreach",
  VOICEMAIL_SYNC: "voicemail-sync",
  POST_ENRICHMENT: "post-enrichment",
  ZEROBOUNCE_BATCH: "zerobounce-batch-validate",
  STATEMENT_UPLOAD: "statement-upload",
  DEAL_STAGE_EFFECTS: "deal-stage-effects",
  CHARGEBACK_COMMANDS: "chargeback-commands",
  CRO03A_QUALIFICATION: "cro03a-qualification",
  CRO03C_LIVE: "cro03c-live",
} as const;

export type QueueName = (typeof QUEUE_NAMES)[keyof typeof QUEUE_NAMES];