export const CHAIN_BLOCKLIST: string[] = [
  "autozone",
  "jiffy lube",
  "midas",
  "meineke",
  "pep boys",
  "firestone",
  "monro muffler",
  "oil can henry",
  "valvoline",
  "grease monkey",
  "christian brothers",
  "good year",
  "goodyear",
  "napa auto",
  "advance auto",
  "oreilly auto",
  "o'reilly auto",
  "heartland dental",
  "aspen dental",
  "western dental",
  "pacific dental",
  "dental care alliance",
  "bright now dental",
  "coast dental",
  "perfect teeth",
  "willamette dental",
  "gentle dental",
  "dentaquest",
  "smiledirectclub",
  "smile direct",
  "great expressions dental",
  "comfort dental",
  "family dental care",
  "kay jewelers",
  "zales",
  "jared",
  "tiffany",
  "pandora",
  "signet",
  "sterling jewelers",
  "helzberg",
  "shane co",
  "whitehall jewellers",
  "fred meyer jewelers",
  "franchise",
  "great clips",
  "sport clips",
  "supercuts",
  "fantastic sams",
  "cost cutters",
  "regis salon",
  "first choice haircutters",
  "hair cuttery",
  "mcdonalds",
  "mcdonald's",
  "burger king",
  "subway",
  "wendy's",
  "wendys",
  "taco bell",
  "chick-fil-a",
  "chick fil a",
  "dominos",
  "domino's",
  "pizza hut",
  "little caesars",
  "papa john's",
  "papa johns",
  "dunkin",
  "starbucks",
  "panera",
  "chipotle",
  "olive garden",
  "applebee's",
  "applebees",
  "denny's",
  "dennys",
  "ihop",
  "waffle house",
  "cracker barrel",
  "red lobster",
  "red robin",
  "ihop",
  "outback steakhouse",
  "longhorn steakhouse",
  "buffalo wild wings",
  "texas roadhouse",
  "planet fitness",
  "anytime fitness",
  "la fitness",
  "24 hour fitness",
  "equinox",
  "gold's gym",
  "golds gym",
  "snap fitness",
  "retro fitness",
  "crunch fitness",
  "xsport",
  "massage envy",
  "hand and stone",
  "european wax center",
  "ulta beauty",
  "ulta",
  "supercolor",
  "fantastic sam's",
  "great american",
  "holiday inn",
  "hilton",
  "marriott",
  "hyatt",
  "sheraton",
  "best western",
  "comfort inn",
  "hampton inn",
  "days inn",
  "super 8",
  "motel 6",
  "cvs",
  "walgreens",
  "rite aid",
  "walmart",
  "target",
  "costco",
  "home depot",
  "lowes",
  "lowe's",
  "menards",
  "ace hardware",
  "true value",
  "uhaul",
  "u-haul",
  "petsmart",
  "petco",
];

export function isChainBusiness(name: string): boolean {
  const lower = name.toLowerCase().trim();
  return CHAIN_BLOCKLIST.some(chain => lower.includes(chain));
}
