// Auto-generated by storage split. Domain: audit.
  // Methods are mixed into DatabaseStorage in server/storage.ts.
  import { db, pool } from "../db";
import {
  liveChats, liveChatMessages,
  type LiveChat, type InsertLiveChat, type LiveChatMessage, type InsertLiveChatMessage,
  contacts, companies, deals, tickets, tasks, documents, auditLogs, notifications, workflowRuns, workflows, rfis, users,
  aiAuditLogs, type AiAuditLog, type InsertAiAuditLog,
  chargebacks,
  type Chargeback, type InsertChargeback, type UpdateChargebackRequest,
  messageTemplates, collateralPackets, ghlActivityLog, slaConfigs,
  prospects, prospectLists, enrichmentJobs, campaigns, campaignSteps, outboundMessages, notes,
  emailLogs, callLogs, stageAutomationRules, followUpSequences, sequenceSteps, sequenceEnrollments,
  sunbizEntities, consentAuditLogs, calendarEvents,
  channelAuditLog, type ChannelAuditLog, type InsertChannelAuditLog,
  merchantApplications, merchantProfiles, equipmentOrders, agents, agentQuotas, agentMerchants, residualReports, merchantResiduals,
  healthAlerts, dealCompetitors, partners, referrals, commissionTiers, knowledgeBase, reviewRequests, testimonialSubmissions, onboardingSteps, midDailyStats,
  sdrMerchants, sdrMerchantContacts, sdrLeadState, sdrLeadEvents, sdrChannelAttempts, sdrComplianceState,
  sendingIdentities,
  leadDiscoveryJobs, leadDiscoveryResults,
  type SendingIdentity, type InsertSendingIdentity,
  businesses, businessAliases, businessLocations, leadSources, enrichmentRuns,
  type LeadDiscoveryJob, type InsertLeadDiscoveryJob,
  type LeadDiscoveryResult, type InsertLeadDiscoveryResult,
  type Business, type InsertBusiness, type UpdateBusinessRequest,
  type BusinessAlias, type InsertBusinessAlias,
  type BusinessLocation, type InsertBusinessLocation,
  type LeadSource, type InsertLeadSource,
  type EnrichmentRun, type InsertEnrichmentRun,
  type SdrMerchant, type InsertSdrMerchant,
  type SdrMerchantContact, type InsertSdrMerchantContact,
  type SdrLeadState, type InsertSdrLeadState,
  type SdrLeadEvent, type InsertSdrLeadEvent,
  type SdrChannelAttempt, type InsertSdrChannelAttempt,
  type SdrComplianceState, type InsertSdrComplianceState,
  type InsertContact, type UpdateContactRequest,
  type InsertCompany,
  type InsertDeal, type UpdateDealRequest,
  type InsertTicket, type UpdateTicketRequest,
  type InsertTask, type UpdateTaskRequest,
  type InsertDocument,
  type InsertAuditLog,
  type InsertNotification,
  type InsertWorkflow, type UpdateWorkflowRequest,
  type InsertWorkflowRun,
  type InsertRfi, type UpdateRfiRequest,
  type InsertMessageTemplate, type MessageTemplate,
  type InsertCollateralPacket,
  type InsertGhlActivityLog,
  type InsertSlaConfig,
  type Prospect, type InsertProspect, type UpdateProspectRequest,
  type InsertProspectList,
  type InsertEnrichmentJob,
  type InsertCampaign, type UpdateCampaignRequest,
  type InsertCampaignStep,
  type InsertOutboundMessage, type UpdateOutboundMessageRequest,
  type InsertNote,
  type InsertEmailLog, type InsertCallLog, type InsertStageAutomationRule, type InsertFollowUpSequence, type InsertSequenceStep, type InsertSequenceEnrollment,
  type InsertSunbizEntity, type UpdateSunbizEntityRequest, type SunbizEntity,
  type InsertMerchantApplication, type MerchantApplication,
  type InsertMerchantProfile, type MerchantProfile,
  type InsertEquipmentOrder, type EquipmentOrder,
  type InsertAgent, type Agent,
  type InsertAgentMerchant, type AgentMerchant,
  type InsertAgentQuota, type AgentQuota,
  type InsertResidualReport, type ResidualReport,
  type InsertMerchantResidual, type MerchantResidual,
  type InsertHealthAlert, type HealthAlert,
  type InsertDealCompetitor, type DealCompetitor,
  type InsertPartner, type Partner,
  type InsertReferral, type Referral,
  type InsertCommissionTier, type CommissionTier,
  type InsertKnowledgeBaseArticle, type KnowledgeBaseArticle,
  type InsertReviewRequest, type ReviewRequest,
  type InsertTestimonialSubmission, type TestimonialSubmission,
  type InsertOnboardingStep, type OnboardingStep,
  type InsertConsentAuditLog, type ConsentAuditLog,
  type CalendarEvent, type InsertCalendarEvent,
  systemSettings,
  dataDeleteRequests,
  type DataDeleteRequest, type InsertDataDeleteRequest,
  comments, ticketComments, contactCompanies, pipelineStages, notificationPreferences, savedFilters,
  type Comment, type InsertComment,
  type TicketComment, type InsertTicketComment,
  type ContactCompany, type InsertContactCompany,
  type PipelineStage, type InsertPipelineStage,
  type NotificationPreference, type InsertNotificationPreference,
  type SavedFilter, type InsertSavedFilter,
  csvImports, type CsvImport, type InsertCsvImport,
  generatedBlogPosts,
  type GeneratedBlogPost, type InsertGeneratedBlogPost,
  type UpdateSdrLeadState,
  ghlWorkflowMappings, type GhlWorkflowMapping,
  npsResponses, type NpsResponse, type InsertNpsResponse,
  merchantReferrals, type MerchantReferral, type InsertMerchantReferral,
  retentionCampaignConfigs, type RetentionCampaignConfig, type InsertRetentionCampaignConfig,
  type MidDailyStat, type InsertMidDailyStat,
  roleplaySessions, type RoleplaySession, type InsertRoleplaySession,
  roleplayExchanges, type RoleplayExchange, type InsertRoleplayExchange,
  leaderboardSettings, type LeaderboardSettings,
} from "@shared/schema";
import { eq, desc, and, lt, isNull, ne, sql, asc, gte, lte, inArray, or, ilike, count } from "drizzle-orm";
  import { type PaginationParams, type PaginatedResult, normalizePagination } from "./_shared";

  export class AuditStorage {
    async getAuditLogs(filters?: {
    entityType?: string;
    entityId?: number;
    actorType?: string;
    actorId?: string;
    userId?: string;
    startDate?: Date;
    endDate?: Date;
    limit?: number;
    offset?: number;
  }) {
    const conditions = [];
    if (filters?.entityType) conditions.push(eq(auditLogs.entityType, filters.entityType));
    if (filters?.entityId != null) conditions.push(eq(auditLogs.entityId, filters.entityId));
    if (filters?.actorType) conditions.push(eq(auditLogs.actorType, filters.actorType));
    if (filters?.actorId) conditions.push(eq(auditLogs.actorId, filters.actorId));
    if (filters?.userId) conditions.push(eq(auditLogs.userId, filters.userId));
    if (filters?.startDate) conditions.push(gte(auditLogs.createdAt, filters.startDate));
    if (filters?.endDate) conditions.push(lte(auditLogs.createdAt, filters.endDate));

    return await db.select().from(auditLogs)
      .where(conditions.length > 0 ? and(...conditions) : undefined)
      .orderBy(desc(auditLogs.createdAt))
      .limit(filters?.limit ?? 200)
      .offset(filters?.offset ?? 0);
  }

  async getAuditLogsByEntity(entityType: string, entityId: number | string, limit: number = 50) {
    const condition = typeof entityId === 'string'
      ? and(eq(auditLogs.entityType, entityType), eq(auditLogs.entityKey, entityId))
      : and(eq(auditLogs.entityType, entityType), eq(auditLogs.entityId, entityId as number));
    return await db.select().from(auditLogs)
      .where(condition)
      .orderBy(desc(auditLogs.createdAt))
      .limit(limit);
  }

  async getLastAuditLogByAction(action: string, entityType: string, entityId: number) {
    const [log] = await db
      .select()
      .from(auditLogs)
      .where(
        and(
          eq(auditLogs.action, action),
          eq(auditLogs.entityType, entityType),
          eq(auditLogs.entityId, entityId)
        )
      )
      .orderBy(desc(auditLogs.createdAt))
      .limit(1);
    return log;
  }

  async createAuditLog(insertLog: InsertAuditLog) {
    const [log] = await db.insert(auditLogs).values(insertLog).returning();
    return log;
  }

  async createChannelAuditLog(entry: InsertChannelAuditLog): Promise<ChannelAuditLog> {
    const [log] = await db.insert(channelAuditLog).values(entry).returning();
    return log;
  }

  async getChannelAuditLog(channel: string, filters?: {
    action?: string;
    actor?: string;
    startDate?: Date;
    endDate?: Date;
    limit?: number;
    offset?: number;
  }): Promise<{ entries: ChannelAuditLog[]; total: number }> {
    const conditions = [eq(channelAuditLog.channel, channel)];
    if (filters?.action) conditions.push(eq(channelAuditLog.action, filters.action));
    if (filters?.actor) {
      const actorCondition = or(
        ilike(channelAuditLog.actorEmail, `%${filters.actor}%`),
        ilike(channelAuditLog.actorUserId, `%${filters.actor}%`)
      );
      if (actorCondition) conditions.push(actorCondition);
    }
    if (filters?.startDate) conditions.push(gte(channelAuditLog.createdAt, filters.startDate));
    if (filters?.endDate) conditions.push(lte(channelAuditLog.createdAt, filters.endDate));

    const whereClause = and(...conditions);
    const limit = filters?.limit ?? 100;
    const offset = filters?.offset ?? 0;

    const [entries, [{ value: total }]] = await Promise.all([
      db.select().from(channelAuditLog)
        .where(whereClause)
        .orderBy(desc(channelAuditLog.createdAt))
        .limit(limit)
        .offset(offset),
      db.select({ value: count() }).from(channelAuditLog).where(whereClause),
    ]);

    return { entries, total: Number(total) };
  }

  async getAiAuditLog(id: number): Promise<AiAuditLog | undefined> {
    const [row] = await db.select().from(aiAuditLogs).where(eq(aiAuditLogs.id, id)).limit(1);
    return row;
  }

  async getAiAuditLogs(filters?: {
    triggerType?: string;
    startDate?: Date;
    endDate?: Date;
    flaggedOnly?: boolean;
    limit?: number;
    offset?: number;
  }): Promise<AiAuditLog[]> {
    const conditions = [];
    if (filters?.triggerType) conditions.push(eq(aiAuditLogs.triggerType, filters.triggerType));
    if (filters?.startDate) conditions.push(gte(aiAuditLogs.createdAt, filters.startDate));
    if (filters?.endDate) conditions.push(lte(aiAuditLogs.createdAt, filters.endDate));
    if (filters?.flaggedOnly) conditions.push(eq(aiAuditLogs.flagged, true));

    return db.select().from(aiAuditLogs)
      .where(conditions.length > 0 ? and(...conditions) : undefined)
      .orderBy(desc(aiAuditLogs.createdAt))
      .limit(filters?.limit ?? 100)
      .offset(filters?.offset ?? 0);
  }

  async getAiHealthMetrics(startDate?: Date, endDate?: Date): Promise<{
    totalCalls: number;
    successCalls: number;
    errorCalls: number;
    completionRate: number;
    avgLatencyMs: number;
    avgConfidenceScore: number;
    flaggedCount: number;
    flaggedRate: number;
    topErrors: Array<{ error: string; count: number }>;
    byTriggerType: Record<string, {
      calls: number; errors: number; avgConfidence: number; avgLatencyMs: number; flagged: number;
    }>;
    confidenceDistribution: { high: number; medium: number; low: number };
    totalCostCents: number;
    todayCostCents: number;
    monthCostCents: number;
    dailyRollup: Array<{ date: string; calls: number; costCents: number; promptTokens: number; completionTokens: number }>;
    confidenceThreshold: number;
  }> {
    const conditions = [];
    if (startDate) conditions.push(gte(aiAuditLogs.createdAt, startDate));
    if (endDate) conditions.push(lte(aiAuditLogs.createdAt, endDate));

    const rows = await db.select().from(aiAuditLogs)
      .where(conditions.length > 0 ? and(...conditions) : undefined);

    const totalCalls = rows.length;
    const errorCalls = rows.filter(r => r.error).length;
    const successCalls = totalCalls - errorCalls;
    const completionRate = totalCalls > 0 ? parseFloat(((successCalls / totalCalls) * 100).toFixed(1)) : 0;

    const latencies = rows.filter(r => r.durationMs != null).map(r => r.durationMs!);
    const avgLatencyMs = latencies.length > 0
      ? Math.round(latencies.reduce((a, b) => a + b, 0) / latencies.length)
      : 0;

    const confidences = rows.filter(r => r.confidenceScore != null).map(r => r.confidenceScore!);
    const avgConfidenceScore = confidences.length > 0
      ? parseFloat((confidences.reduce((a, b) => a + b, 0) / confidences.length).toFixed(3))
      : 0;

    const flaggedCount = rows.filter(r => r.flagged).length;
    const flaggedRate = totalCalls > 0 ? parseFloat(((flaggedCount / totalCalls) * 100).toFixed(1)) : 0;

    const errorCounts: Record<string, number> = {};
    for (const row of rows) {
      if (row.error) {
        const key = row.error.slice(0, 80);
        errorCounts[key] = (errorCounts[key] || 0) + 1;
      }
    }
    const topErrors = Object.entries(errorCounts)
      .sort((a, b) => b[1] - a[1])
      .slice(0, 5)
      .map(([error, count]) => ({ error, count }));

    const byTriggerType: Record<string, { calls: number; errors: number; avgConfidence: number; avgLatencyMs: number; flagged: number }> = {};
    for (const row of rows) {
      const tt = row.triggerType;
      if (!byTriggerType[tt]) byTriggerType[tt] = { calls: 0, errors: 0, avgConfidence: 0, avgLatencyMs: 0, flagged: 0 };
      byTriggerType[tt].calls++;
      if (row.error) byTriggerType[tt].errors++;
      if (row.flagged) byTriggerType[tt].flagged++;
    }
    for (const [tt, stats] of Object.entries(byTriggerType)) {
      const ttRows = rows.filter(r => r.triggerType === tt);
      const confValues = ttRows.filter(r => r.confidenceScore != null).map(r => r.confidenceScore!);
      const latValues = ttRows.filter(r => r.durationMs != null).map(r => r.durationMs!);
      stats.avgConfidence = confValues.length > 0
        ? parseFloat((confValues.reduce((a, b) => a + b, 0) / confValues.length).toFixed(3))
        : 0;
      stats.avgLatencyMs = latValues.length > 0
        ? Math.round(latValues.reduce((a, b) => a + b, 0) / latValues.length)
        : 0;
    }

    const confidenceDistribution = { high: 0, medium: 0, low: 0 };
    for (const score of confidences) {
      if (score >= 0.75) confidenceDistribution.high++;
      else if (score >= 0.5) confidenceDistribution.medium++;
      else confidenceDistribution.low++;
    }

    const totalCostCents = rows.reduce((sum, r) => sum + (r.costCents || 0), 0);
    const now2 = new Date();
    const todayStart = new Date(now2.getFullYear(), now2.getMonth(), now2.getDate());
    const monthStart = new Date(now2.getFullYear(), now2.getMonth(), 1);
    const todayCostCents = rows.filter(r => r.createdAt && new Date(r.createdAt) >= todayStart).reduce((sum, r) => sum + (r.costCents || 0), 0);
    const monthCostCents = rows.filter(r => r.createdAt && new Date(r.createdAt) >= monthStart).reduce((sum, r) => sum + (r.costCents || 0), 0);

    const days = 30;
    const rollupSince = new Date();
    rollupSince.setDate(rollupSince.getDate() - (days - 1));
    rollupSince.setHours(0, 0, 0, 0);
    const byDay: Record<string, { calls: number; costCents: number; promptTokens: number; completionTokens: number }> = {};
    for (let i = 0; i < days; i++) {
      const d = new Date(rollupSince);
      d.setDate(d.getDate() + i);
      byDay[d.toISOString().slice(0, 10)] = { calls: 0, costCents: 0, promptTokens: 0, completionTokens: 0 };
    }
    const allRecent = await db.select().from(aiAuditLogs).where(gte(aiAuditLogs.createdAt, rollupSince));
    for (const row of allRecent) {
      const key = new Date(row.createdAt!).toISOString().slice(0, 10);
      if (byDay[key]) {
        byDay[key].calls++;
        byDay[key].costCents += row.costCents || 0;
        byDay[key].promptTokens += row.promptTokens || 0;
        byDay[key].completionTokens += row.completionTokens || 0;
      }
    }
    const dailyRollup = Object.entries(byDay)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([date, stats]) => ({ date, ...stats }));

    const confidenceThreshold = parseFloat(process.env.AI_CONFIDENCE_THRESHOLD || "0.5");

    return {
      totalCalls, successCalls, errorCalls, completionRate,
      avgLatencyMs, avgConfidenceScore, flaggedCount, flaggedRate,
      topErrors, byTriggerType, confidenceDistribution,
      totalCostCents, todayCostCents, monthCostCents, dailyRollup, confidenceThreshold,
    };
  }

  async getAiAuditLogTotals(filters?: { startDate?: Date; endDate?: Date }): Promise<{
    totalCalls: number;
    totalPromptTokens: number;
    totalCompletionTokens: number;
    totalCostCents: number;
    byTriggerType: Record<string, { calls: number; promptTokens: number; completionTokens: number; costCents: number }>;
  }> {
    const conditions = [];
    if (filters?.startDate) conditions.push(gte(aiAuditLogs.createdAt, filters.startDate));
    if (filters?.endDate) conditions.push(lte(aiAuditLogs.createdAt, filters.endDate));

    const rows = await db.select().from(aiAuditLogs)
      .where(conditions.length > 0 ? and(...conditions) : undefined);

    const byTriggerType: Record<string, { calls: number; promptTokens: number; completionTokens: number; costCents: number }> = {};
    let totalPromptTokens = 0;
    let totalCompletionTokens = 0;
    let totalCostCents = 0;

    for (const row of rows) {
      const pt = row.promptTokens || 0;
      const ct = row.completionTokens || 0;
      const cost = row.costCents || 0;
      totalPromptTokens += pt;
      totalCompletionTokens += ct;
      totalCostCents += cost;

      const key = row.triggerType;
      if (!byTriggerType[key]) byTriggerType[key] = { calls: 0, promptTokens: 0, completionTokens: 0, costCents: 0 };
      byTriggerType[key].calls++;
      byTriggerType[key].promptTokens += pt;
      byTriggerType[key].completionTokens += ct;
      byTriggerType[key].costCents += cost;
    }

    return { totalCalls: rows.length, totalPromptTokens, totalCompletionTokens, totalCostCents, byTriggerType };
  }

  async getAiCostDailyRollup(days: number = 30): Promise<Array<{ date: string; calls: number; costCents: number; promptTokens: number; completionTokens: number }>> {
    const since = new Date();
    since.setDate(since.getDate() - (days - 1));
    since.setHours(0, 0, 0, 0);

    const rows = await db.select().from(aiAuditLogs)
      .where(gte(aiAuditLogs.createdAt, since))
      .orderBy(asc(aiAuditLogs.createdAt));

    const byDay: Record<string, { calls: number; costCents: number; promptTokens: number; completionTokens: number }> = {};

    for (let i = 0; i < days; i++) {
      const d = new Date(since);
      d.setDate(d.getDate() + i);
      const key = d.toISOString().slice(0, 10);
      byDay[key] = { calls: 0, costCents: 0, promptTokens: 0, completionTokens: 0 };
    }

    for (const row of rows) {
      const key = new Date(row.createdAt!).toISOString().slice(0, 10);
      if (!byDay[key]) byDay[key] = { calls: 0, costCents: 0, promptTokens: 0, completionTokens: 0 };
      byDay[key].calls++;
      byDay[key].costCents += row.costCents || 0;
      byDay[key].promptTokens += row.promptTokens || 0;
      byDay[key].completionTokens += row.completionTokens || 0;
    }

    return Object.entries(byDay)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([date, stats]) => ({ date, ...stats }));
  }

  async getAiCostSummary(startDate?: Date, endDate?: Date): Promise<{
    todayCostCents: number;
    todayCalls: number;
    monthCostCents: number;
    monthCalls: number;
    rangeCostCents: number;
    rangeCalls: number;
    byTriggerType: Record<string, { calls: number; costCents: number; promptTokens: number; completionTokens: number }>;
  }> {
    const now = new Date();
    const todayStart = new Date(now.getFullYear(), now.getMonth(), now.getDate());
    const monthStart = new Date(now.getFullYear(), now.getMonth(), 1);
    const rangeStart = startDate ?? monthStart;
    const rangeEnd = endDate ?? now;

    // Query from the earliest of monthStart and rangeStart so custom ranges work correctly
    const fetchFrom = rangeStart < monthStart ? rangeStart : monthStart;
    const sinceMonth = await db.select().from(aiAuditLogs).where(gte(aiAuditLogs.createdAt, fetchFrom));

    let todayCostCents = 0;
    let todayCalls = 0;
    let monthCostCents = 0;
    let monthCalls = 0;
    let rangeCostCents = 0;
    let rangeCalls = 0;
    const byTriggerType: Record<string, { calls: number; costCents: number; promptTokens: number; completionTokens: number }> = {};

    for (const row of sinceMonth) {
      const cost = row.costCents || 0;
      const tt = row.triggerType;
      const rowDate = new Date(row.createdAt!);

      monthCostCents += cost;
      monthCalls++;

      if (!byTriggerType[tt]) byTriggerType[tt] = { calls: 0, costCents: 0, promptTokens: 0, completionTokens: 0 };
      byTriggerType[tt].calls++;
      byTriggerType[tt].costCents += cost;
      byTriggerType[tt].promptTokens += row.promptTokens || 0;
      byTriggerType[tt].completionTokens += row.completionTokens || 0;

      if (rowDate >= todayStart) {
        todayCostCents += cost;
        todayCalls++;
      }

      if (rowDate >= rangeStart && rowDate <= rangeEnd) {
        rangeCostCents += cost;
        rangeCalls++;
      }
    }

    return { todayCostCents, todayCalls, monthCostCents, monthCalls, rangeCostCents, rangeCalls, byTriggerType };
  }

  }
  