// Auto-generated by storage split. Domain: automation.
  // Methods are mixed into DatabaseStorage in server/storage.ts.
  import { db, pool } from "../db";
import {
  liveChats, liveChatMessages,
  type LiveChat, type InsertLiveChat, type LiveChatMessage, type InsertLiveChatMessage,
  contacts, companies, deals, tickets, tasks, documents, auditLogs, notifications, workflowRuns, workflows, rfis, users,
  chargebacks,
  type Chargeback, type InsertChargeback, type UpdateChargebackRequest,
  messageTemplates, collateralPackets, ghlActivityLog, slaConfigs,
  prospects, prospectLists, enrichmentJobs, campaigns, campaignSteps, outboundMessages, notes,
  emailLogs, callLogs, stageAutomationRules, followUpSequences, sequenceSteps, sequenceEnrollments,
  sunbizEntities, consentAuditLogs, calendarEvents,
  merchantApplications, merchantProfiles, equipmentOrders, agents, agentQuotas, agentMerchants, residualReports, merchantResiduals,
  healthAlerts, dealCompetitors, partners, referrals, commissionTiers, knowledgeBase, reviewRequests, testimonialSubmissions, onboardingSteps, midDailyStats,
  sdrMerchants, sdrMerchantContacts, sdrLeadState, sdrLeadEvents, sdrChannelAttempts, sdrComplianceState,
  sendingIdentities,
  leadDiscoveryJobs, leadDiscoveryResults,
  type SendingIdentity, type InsertSendingIdentity,
  businesses, businessAliases, businessLocations, leadSources, enrichmentRuns,
  type LeadDiscoveryJob, type InsertLeadDiscoveryJob,
  type LeadDiscoveryResult, type InsertLeadDiscoveryResult,
  type Business, type InsertBusiness, type UpdateBusinessRequest,
  type BusinessAlias, type InsertBusinessAlias,
  type BusinessLocation, type InsertBusinessLocation,
  type LeadSource, type InsertLeadSource,
  type EnrichmentRun, type InsertEnrichmentRun,
  type SdrMerchant, type InsertSdrMerchant,
  type SdrMerchantContact, type InsertSdrMerchantContact,
  type SdrLeadState, type InsertSdrLeadState,
  type SdrLeadEvent, type InsertSdrLeadEvent,
  type SdrChannelAttempt, type InsertSdrChannelAttempt,
  type SdrComplianceState, type InsertSdrComplianceState,
  type InsertContact, type UpdateContactRequest,
  type InsertCompany,
  type InsertDeal, type UpdateDealRequest,
  type InsertTicket, type UpdateTicketRequest,
  type InsertTask, type UpdateTaskRequest,
  type InsertDocument,
  type InsertAuditLog,
  type InsertNotification,
  type InsertWorkflow, type UpdateWorkflowRequest,
  type InsertWorkflowRun,
  type InsertRfi, type UpdateRfiRequest,
  type InsertMessageTemplate, type MessageTemplate,
  type InsertCollateralPacket,
  type InsertGhlActivityLog,
  type InsertSlaConfig,
  type Prospect, type InsertProspect, type UpdateProspectRequest,
  type InsertProspectList,
  type InsertEnrichmentJob,
  type InsertCampaign, type UpdateCampaignRequest,
  type InsertCampaignStep,
  type InsertOutboundMessage, type UpdateOutboundMessageRequest,
  type InsertNote,
  type InsertEmailLog, type InsertCallLog, type InsertStageAutomationRule, type InsertFollowUpSequence, type InsertSequenceStep, type InsertSequenceEnrollment, type AbTestResults,
  type InsertSunbizEntity, type UpdateSunbizEntityRequest, type SunbizEntity,
  type InsertMerchantApplication, type MerchantApplication,
  type InsertMerchantProfile, type MerchantProfile,
  type InsertEquipmentOrder, type EquipmentOrder,
  type InsertAgent, type Agent,
  type InsertAgentMerchant, type AgentMerchant,
  type InsertAgentQuota, type AgentQuota,
  type InsertResidualReport, type ResidualReport,
  type InsertMerchantResidual, type MerchantResidual,
  type InsertHealthAlert, type HealthAlert,
  type InsertDealCompetitor, type DealCompetitor,
  type InsertPartner, type Partner,
  type InsertReferral, type Referral,
  type InsertCommissionTier, type CommissionTier,
  type InsertKnowledgeBaseArticle, type KnowledgeBaseArticle,
  type InsertReviewRequest, type ReviewRequest,
  type InsertTestimonialSubmission, type TestimonialSubmission,
  type InsertOnboardingStep, type OnboardingStep,
  type InsertConsentAuditLog, type ConsentAuditLog,
  type CalendarEvent, type InsertCalendarEvent,
  systemSettings,
  dataDeleteRequests,
  type DataDeleteRequest, type InsertDataDeleteRequest,
  comments, ticketComments, contactCompanies, pipelineStages, notificationPreferences, savedFilters,
  type Comment, type InsertComment,
  type TicketComment, type InsertTicketComment,
  type ContactCompany, type InsertContactCompany,
  type PipelineStage, type InsertPipelineStage,
  type NotificationPreference, type InsertNotificationPreference,
  type SavedFilter, type InsertSavedFilter,
  csvImports, type CsvImport, type InsertCsvImport,
  generatedBlogPosts,
  type GeneratedBlogPost, type InsertGeneratedBlogPost,
  type UpdateSdrLeadState,
  ghlWorkflowMappings, type GhlWorkflowMapping,
  npsResponses, type NpsResponse, type InsertNpsResponse,
  merchantReferrals, type MerchantReferral, type InsertMerchantReferral,
  retentionCampaignConfigs, type RetentionCampaignConfig, type InsertRetentionCampaignConfig,
  type MidDailyStat, type InsertMidDailyStat,
  roleplaySessions, type RoleplaySession, type InsertRoleplaySession,
  roleplayExchanges, type RoleplayExchange, type InsertRoleplayExchange,
  leaderboardSettings, type LeaderboardSettings,
} from "@shared/schema";
import { eq, desc, and, lt, isNull, ne, sql, asc, gte, lte, inArray, or, ilike, count } from "drizzle-orm";
import { coerceDateFields } from "../utils/date-coerce";
  import { type PaginationParams, type PaginatedResult, normalizePagination } from "./_shared";

  export class AutomationStorage {
    async getStageAutomationRules(pipeline?: string) {
    if (pipeline) {
      return await db.select().from(stageAutomationRules).where(eq(stageAutomationRules.pipeline, pipeline)).orderBy(desc(stageAutomationRules.priority));
    }
    return await db.select().from(stageAutomationRules).orderBy(desc(stageAutomationRules.priority));
  }


  async getStageAutomationRule(id: number) {
    const [rule] = await db.select().from(stageAutomationRules).where(eq(stageAutomationRules.id, id));
    return rule;
  }


  async createStageAutomationRule(rule: InsertStageAutomationRule) {
    const [created] = await db.insert(stageAutomationRules).values(rule).returning();
    return created;
  }


  async updateStageAutomationRule(id: number, updates: Partial<InsertStageAutomationRule>) {
    const [updated] = await db.update(stageAutomationRules).set({ ...updates, updatedAt: new Date() }).where(eq(stageAutomationRules.id, id)).returning();
    return updated;
  }


  async deleteStageAutomationRule(id: number) {
    await db.delete(stageAutomationRules).where(eq(stageAutomationRules.id, id));
  }


  async getMatchingStageRules(pipeline: string, fromStage: string | null, toStage: string) {
    return await db.select().from(stageAutomationRules).where(
      and(
        eq(stageAutomationRules.pipeline, pipeline),
        eq(stageAutomationRules.toStage, toStage),
        eq(stageAutomationRules.enabled, true),
        fromStage
          ? sql`(${stageAutomationRules.fromStage} IS NULL OR ${stageAutomationRules.fromStage} = ${fromStage})`
          : isNull(stageAutomationRules.fromStage)
      )
    ).orderBy(desc(stageAutomationRules.priority));
  }


  async getFollowUpSequences() {
    return await db.select().from(followUpSequences).orderBy(desc(followUpSequences.createdAt));
  }


  async getFollowUpSequence(id: number) {
    const [seq] = await db.select().from(followUpSequences).where(eq(followUpSequences.id, id));
    return seq;
  }


  async createFollowUpSequence(seq: InsertFollowUpSequence) {
    const [created] = await db.insert(followUpSequences).values(seq).returning();
    return created;
  }


  async updateFollowUpSequence(id: number, updates: Partial<InsertFollowUpSequence>) {
    const [updated] = await db.update(followUpSequences).set({ ...updates, updatedAt: new Date() }).where(eq(followUpSequences.id, id)).returning();
    return updated;
  }


  async deleteFollowUpSequence(id: number) {
    await db.delete(followUpSequences).where(eq(followUpSequences.id, id));
  }


  async getSequenceSteps(sequenceId: number) {
    return await db.select().from(sequenceSteps).where(eq(sequenceSteps.sequenceId, sequenceId)).orderBy(asc(sequenceSteps.stepOrder));
  }


  async createSequenceStep(step: InsertSequenceStep) {
    const [created] = await db.insert(sequenceSteps).values(step).returning();
    return created;
  }


  async updateSequenceStep(id: number, updates: Partial<InsertSequenceStep>) {
    const [updated] = await db.update(sequenceSteps).set(updates).where(eq(sequenceSteps.id, id)).returning();
    return updated;
  }


  async updateSequenceStepAbTestResults(id: number, results: AbTestResults) {
    const [updated] = await db.update(sequenceSteps)
      .set({ abTestResults: results as unknown as Record<string, unknown> })
      .where(eq(sequenceSteps.id, id))
      .returning();
    return updated;
  }


  async deleteSequenceStep(id: number) {
    await db.delete(sequenceSteps).where(eq(sequenceSteps.id, id));
  }


  async getSequenceEnrollments(sequenceId?: number) {
    if (sequenceId) {
      return await db.select().from(sequenceEnrollments).where(eq(sequenceEnrollments.sequenceId, sequenceId)).orderBy(desc(sequenceEnrollments.createdAt));
    }
    return await db.select().from(sequenceEnrollments).orderBy(desc(sequenceEnrollments.createdAt));
  }


  async getContactEnrollments(contactId: number) {
    return await db.select().from(sequenceEnrollments).where(eq(sequenceEnrollments.contactId, contactId)).orderBy(desc(sequenceEnrollments.createdAt));
  }


  async createSequenceEnrollment(enrollment: InsertSequenceEnrollment): Promise<typeof sequenceEnrollments.$inferSelect | null> {
    // Wrap the status-check + insert in a single transaction and lock the
    // sequence row FOR UPDATE.  This closes the race window where a sequence
    // could be paused between the status SELECT and the enrollment INSERT,
    // which would silently create an active enrollment in a paused sequence.
    return await db.transaction(async (tx) => {
      if (enrollment.sequenceId) {
        // SELECT FOR UPDATE prevents any concurrent UPDATE (e.g. pause) from
        // committing until our transaction finishes.
        const seqRows = await tx.execute(
          sql`SELECT status FROM follow_up_sequences WHERE id = ${enrollment.sequenceId} FOR UPDATE`
        );
        const seqStatus = (seqRows.rows[0] as any)?.status;
        if (!seqStatus) {
          throw new Error(`Sequence ${enrollment.sequenceId} not found — enrollment blocked.`);
        }
        if (seqStatus !== "active") {
          throw new Error(`Sequence ${enrollment.sequenceId} is ${seqStatus} — enrollment blocked. Activate the sequence before enrolling contacts.`);
        }
      }

      // Idempotency check — prevent TOCTOU double-enrollment.
      // If an active or paused enrollment already exists for this contact+sequence,
      // skip the insert and return null. The partial unique index
      // (idx_sequence_enrollments_active_unique) is a hard DB backstop; this
      // pre-check avoids the constraint violation in the happy path.
      if (enrollment.contactId && enrollment.sequenceId) {
        const [existing] = await tx
          .select({ id: sequenceEnrollments.id })
          .from(sequenceEnrollments)
          .where(
            and(
              eq(sequenceEnrollments.contactId, enrollment.contactId),
              eq(sequenceEnrollments.sequenceId, enrollment.sequenceId),
              inArray(sequenceEnrollments.status, ["active", "paused"])
            )
          )
          .limit(1);
        if (existing) {
          // C-13 (#1626): route direct audit inserts through the canonical sanitizer
          await tx.insert(auditLogs).values({
            action: "sequence_enrollment_duplicate_skipped",
            entityType: "contact",
            entityId: enrollment.contactId,
            actorType: "system",
            details: (await import("../services/audit-sanitizer")).sanitizeAuditPayload({
              contactId: enrollment.contactId,
              sequenceId: enrollment.sequenceId,
              existingEnrollmentId: existing.id,
              reason: "Active or paused enrollment already exists — duplicate insert skipped.",
            }),
          } as any);
          return null;
        }
      }

      try {
        const [created] = await tx.insert(sequenceEnrollments).values(enrollment).returning();
        return created;
      } catch (err: any) {
        // Catch any DB unique-constraint violation from the partial index (hard backstop).
        // Treat it as a skip — do not rethrow so callers never crash.
        const isUniqueViolation =
          err?.code === "23505" ||
          (typeof err?.message === "string" && err.message.includes("idx_sequence_enrollments_active_unique"));
        if (isUniqueViolation) {
          if (enrollment.contactId && enrollment.sequenceId) {
            // C-13 (#1626): route direct audit inserts through the canonical sanitizer
            await tx.insert(auditLogs).values({
              action: "sequence_enrollment_duplicate_skipped",
              entityType: "contact",
              entityId: enrollment.contactId,
              actorType: "system",
              details: (await import("../services/audit-sanitizer")).sanitizeAuditPayload({
                contactId: enrollment.contactId,
                sequenceId: enrollment.sequenceId,
                reason: "DB unique constraint violation caught — duplicate insert blocked by index.",
              }),
            } as any);
          }
          return null;
        }
        throw err;
      }
    });
  }


  async updateSequenceEnrollment(id: number, updates: Partial<InsertSequenceEnrollment>) {
    const coercedUpdates = coerceDateFields(
      updates as Record<string, unknown>,
      ["nextActionAt", "completedAt", "pausedAt"],
    );
    const [updated] = await db.update(sequenceEnrollments).set({ ...coercedUpdates, updatedAt: new Date() } as typeof sequenceEnrollments.$inferInsert).where(eq(sequenceEnrollments.id, id)).returning();
    return updated;
  }


  async cancelSequenceEnrollment(sequenceId: number, contactId: number): Promise<typeof sequenceEnrollments.$inferSelect | null> {
    const [enrollment] = await db
      .select()
      .from(sequenceEnrollments)
      .where(
        and(
          eq(sequenceEnrollments.sequenceId, sequenceId),
          eq(sequenceEnrollments.contactId, contactId),
          inArray(sequenceEnrollments.status, ["active", "paused"])
        )
      )
      .limit(1);
    if (!enrollment) return null;
    const [updated] = await db
      .update(sequenceEnrollments)
      .set({ status: "cancelled", updatedAt: new Date() })
      .where(eq(sequenceEnrollments.id, enrollment.id))
      .returning();
    return updated ?? null;
  }


  async getActiveEnrollments() {
    const now = new Date();
    return await db.select().from(sequenceEnrollments).where(
      and(
        eq(sequenceEnrollments.status, "active"),
        sql`${sequenceEnrollments.nextActionAt} IS NOT NULL`,
        sql`${sequenceEnrollments.nextActionAt} <= ${now}`
      )
    );
  }

  async pauseAllActiveEnrollments(contactId: number): Promise<number> {
    const active = await db.select({ id: sequenceEnrollments.id })
      .from(sequenceEnrollments)
      .where(
        and(
          eq(sequenceEnrollments.contactId, contactId),
          eq(sequenceEnrollments.status, "active")
        )
      );
    if (active.length === 0) return 0;
    await db.update(sequenceEnrollments)
      .set({ status: "paused", pausedAt: new Date(), updatedAt: new Date() })
      .where(
        and(
          eq(sequenceEnrollments.contactId, contactId),
          eq(sequenceEnrollments.status, "active")
        )
      );
    return active.length;
  }

  async getContactEnrollmentsForContacts(contactIds: number[], sequenceIds?: number[]) {
    if (contactIds.length === 0) return [];
    const CHUNK = 500;
    const results: typeof sequenceEnrollments.$inferSelect[] = [];
    for (let i = 0; i < contactIds.length; i += CHUNK) {
      const chunk = contactIds.slice(i, i + CHUNK);
      const condition = sequenceIds && sequenceIds.length > 0
        ? and(inArray(sequenceEnrollments.contactId, chunk), inArray(sequenceEnrollments.sequenceId, sequenceIds))
        : inArray(sequenceEnrollments.contactId, chunk);
      const rows = await db.select().from(sequenceEnrollments).where(condition);
      results.push(...rows);
    }
    return results;
  }

  async getFollowUpSequencesByIds(sequenceIds: number[]) {
    if (sequenceIds.length === 0) return [];
    const CHUNK = 500;
    const results: typeof followUpSequences.$inferSelect[] = [];
    for (let i = 0; i < sequenceIds.length; i += CHUNK) {
      const chunk = sequenceIds.slice(i, i + CHUNK);
      const rows = await db.select().from(followUpSequences).where(inArray(followUpSequences.id, chunk));
      results.push(...rows);
    }
    return results;
  }

  async getSequenceStepsForSequences(sequenceIds: number[]) {
    if (sequenceIds.length === 0) return [];
    const CHUNK = 500;
    const results: typeof sequenceSteps.$inferSelect[] = [];
    for (let i = 0; i < sequenceIds.length; i += CHUNK) {
      const chunk = sequenceIds.slice(i, i + CHUNK);
      const rows = await db.select().from(sequenceSteps)
        .where(inArray(sequenceSteps.sequenceId, chunk))
        .orderBy(asc(sequenceSteps.stepOrder));
      results.push(...rows);
    }
    return results;
  }

  }
  