// Auto-generated by storage split. Domain: campaigns.
  // Methods are mixed into DatabaseStorage in server/storage.ts.
  import { db, pool } from "../db";
import { denyCro03OrCro08aForbiddenEffect as denyCro03cForbiddenEffect } from "../services/cro03/cro08a-effect-fence";
import {
  liveChats, liveChatMessages,
  type LiveChat, type InsertLiveChat, type LiveChatMessage, type InsertLiveChatMessage,
  contacts, companies, deals, tickets, tasks, documents, auditLogs, notifications, workflowRuns, workflows, rfis, users,
  chargebacks,
  type Chargeback, type InsertChargeback, type UpdateChargebackRequest,
  messageTemplates, collateralPackets, ghlActivityLog, slaConfigs,
  prospects, prospectLists, enrichmentJobs, campaigns, campaignSteps, campaignPreviews, outboundMessages, notes,
  emailLogs, callLogs, stageAutomationRules, followUpSequences, sequenceSteps, sequenceEnrollments,
  sunbizEntities, consentAuditLogs, calendarEvents,
  merchantApplications, merchantProfiles, equipmentOrders, agents, agentQuotas, agentMerchants, residualReports, merchantResiduals,
  healthAlerts, dealCompetitors, partners, referrals, commissionTiers, knowledgeBase, reviewRequests, testimonialSubmissions, onboardingSteps, midDailyStats,
  sdrMerchants, sdrMerchantContacts, sdrLeadState, sdrLeadEvents, sdrChannelAttempts, sdrComplianceState,
  sendingIdentities,
  leadDiscoveryJobs, leadDiscoveryResults,
  type SendingIdentity, type InsertSendingIdentity,
  businesses, businessAliases, businessLocations, leadSources, enrichmentRuns,
  type LeadDiscoveryJob, type InsertLeadDiscoveryJob,
  type LeadDiscoveryResult, type InsertLeadDiscoveryResult,
  type Business, type InsertBusiness, type UpdateBusinessRequest,
  type BusinessAlias, type InsertBusinessAlias,
  type BusinessLocation, type InsertBusinessLocation,
  type LeadSource, type InsertLeadSource,
  type EnrichmentRun, type InsertEnrichmentRun,
  type SdrMerchant, type InsertSdrMerchant,
  type SdrMerchantContact, type InsertSdrMerchantContact,
  type SdrLeadState, type InsertSdrLeadState,
  type SdrLeadEvent, type InsertSdrLeadEvent,
  type SdrChannelAttempt, type InsertSdrChannelAttempt,
  type SdrComplianceState, type InsertSdrComplianceState,
  type InsertContact, type UpdateContactRequest,
  type InsertCompany,
  type InsertDeal, type UpdateDealRequest,
  type InsertTicket, type UpdateTicketRequest,
  type InsertTask, type UpdateTaskRequest,
  type InsertDocument,
  type InsertAuditLog,
  type InsertNotification,
  type InsertWorkflow, type UpdateWorkflowRequest,
  type InsertWorkflowRun,
  type InsertRfi, type UpdateRfiRequest,
  type InsertMessageTemplate, type MessageTemplate,
  type InsertCollateralPacket,
  type InsertGhlActivityLog,
  type InsertSlaConfig,
  type Prospect, type InsertProspect, type UpdateProspectRequest,
  type InsertProspectList,
  type InsertEnrichmentJob,
  type InsertCampaign, type UpdateCampaignRequest,
  type CampaignPreview, type InsertCampaignPreview,
  type InsertCampaignStep,
  type InsertOutboundMessage, type UpdateOutboundMessageRequest,
  type InsertNote,
  type InsertEmailLog, type InsertCallLog, type InsertStageAutomationRule, type InsertFollowUpSequence, type InsertSequenceStep, type InsertSequenceEnrollment,
  type InsertSunbizEntity, type UpdateSunbizEntityRequest, type SunbizEntity,
  type InsertMerchantApplication, type MerchantApplication,
  type InsertMerchantProfile, type MerchantProfile,
  type InsertEquipmentOrder, type EquipmentOrder,
  type InsertAgent, type Agent,
  type InsertAgentMerchant, type AgentMerchant,
  type InsertAgentQuota, type AgentQuota,
  type InsertResidualReport, type ResidualReport,
  type InsertMerchantResidual, type MerchantResidual,
  type InsertHealthAlert, type HealthAlert,
  type InsertDealCompetitor, type DealCompetitor,
  type InsertPartner, type Partner,
  type InsertReferral, type Referral,
  type InsertCommissionTier, type CommissionTier,
  type InsertKnowledgeBaseArticle, type KnowledgeBaseArticle,
  type InsertReviewRequest, type ReviewRequest,
  type InsertTestimonialSubmission, type TestimonialSubmission,
  type InsertOnboardingStep, type OnboardingStep,
  type InsertConsentAuditLog, type ConsentAuditLog,
  type CalendarEvent, type InsertCalendarEvent,
  systemSettings,
  dataDeleteRequests,
  type DataDeleteRequest, type InsertDataDeleteRequest,
  comments, ticketComments, contactCompanies, pipelineStages, notificationPreferences, savedFilters,
  type Comment, type InsertComment,
  type TicketComment, type InsertTicketComment,
  type ContactCompany, type InsertContactCompany,
  type PipelineStage, type InsertPipelineStage,
  type NotificationPreference, type InsertNotificationPreference,
  type SavedFilter, type InsertSavedFilter,
  csvImports, type CsvImport, type InsertCsvImport,
  generatedBlogPosts,
  type GeneratedBlogPost, type InsertGeneratedBlogPost,
  type UpdateSdrLeadState,
  ghlWorkflowMappings, type GhlWorkflowMapping,
  npsResponses, type NpsResponse, type InsertNpsResponse,
  merchantReferrals, type MerchantReferral, type InsertMerchantReferral,
  retentionCampaignConfigs, type RetentionCampaignConfig, type InsertRetentionCampaignConfig,
  type MidDailyStat, type InsertMidDailyStat,
  roleplaySessions, type RoleplaySession, type InsertRoleplaySession,
  roleplayExchanges, type RoleplayExchange, type InsertRoleplayExchange,
  leaderboardSettings, type LeaderboardSettings,
} from "@shared/schema";
import { eq, desc, and, lt, isNull, ne, sql, asc, gte, lte, inArray, or, ilike, count } from "drizzle-orm";
  import { type PaginationParams, type PaginatedResult, normalizePagination } from "./_shared";

  export class CampaignsStorage {
    async getCampaigns() {
    return await db.select().from(campaigns).orderBy(desc(campaigns.createdAt));
  }


  async getCampaign(id: number) {
    const [campaign] = await db.select().from(campaigns).where(eq(campaigns.id, id));
    return campaign;
  }


  async createCampaign(campaign: InsertCampaign) {
    await denyCro03cForbiddenEffect("campaign_creation");
    const [created] = await db.insert(campaigns).values(campaign).returning();
    return created;
  }


  async updateCampaign(id: number, updates: UpdateCampaignRequest) {
    const [updated] = await db.update(campaigns).set({ ...updates, updatedAt: new Date() }).where(eq(campaigns.id, id)).returning();
    return updated;
  }


  async getCampaignSteps(campaignId: number) {
    return await db.select().from(campaignSteps).where(eq(campaignSteps.campaignId, campaignId)).orderBy(asc(campaignSteps.stepOrder));
  }

  async getCampaignStep(id: number) {
    const [step] = await db.select().from(campaignSteps).where(eq(campaignSteps.id, id));
    return step;
  }


  async createCampaignStep(step: InsertCampaignStep) {
    const [created] = await db.insert(campaignSteps).values(step).returning();
    return created;
  }


  async updateCampaignStep(id: number, updates: Partial<InsertCampaignStep>) {
    const [updated] = await db.update(campaignSteps).set(updates).where(eq(campaignSteps.id, id)).returning();
    return updated;
  }


  async deleteCampaignStep(id: number) {
    await db.delete(campaignSteps).where(eq(campaignSteps.id, id));
  }


  async getOutboundMessages(campaignId?: number) {
    if (campaignId) {
      return await db.select().from(outboundMessages).where(eq(outboundMessages.campaignId, campaignId)).orderBy(desc(outboundMessages.createdAt));
    }
    return await db.select().from(outboundMessages).orderBy(desc(outboundMessages.createdAt));
  }


  async getOutboundMessage(id: number) {
    const [msg] = await db.select().from(outboundMessages).where(eq(outboundMessages.id, id));
    return msg;
  }


  async createOutboundMessage(msg: InsertOutboundMessage) {
    const [created] = await db.insert(outboundMessages).values(msg).returning();
    return created;
  }


  async createOutboundMessagesBulk(msgs: InsertOutboundMessage[]) {
    return await db.insert(outboundMessages).values(msgs).returning();
  }


  async updateOutboundMessage(id: number, updates: UpdateOutboundMessageRequest) {
    const [updated] = await db.update(outboundMessages).set(updates).where(eq(outboundMessages.id, id)).returning();
    return updated;
  }

  async claimOutboundMessageForSending(id: number): Promise<boolean> {
    const [claimed] = await db.update(outboundMessages)
      .set({ status: "sending", sendingAt: new Date() })
      .where(and(
        eq(outboundMessages.id, id),
        eq(outboundMessages.status, "queued"),
        or(isNull(outboundMessages.scheduledFor), lte(outboundMessages.scheduledFor, new Date())),
      ))
      .returning({ id: outboundMessages.id });
    return !!claimed;
  }


  async getQueuedMessages(limit: number) {
    return await db.select().from(outboundMessages)
      .where(eq(outboundMessages.status, "queued"))
      .orderBy(asc(outboundMessages.scheduledFor))
      .limit(limit);
  }

  /**
   * Mark stale in-flight messages as failed.
   * Any row that has been in `sending` status for more than 5 minutes is
   * considered to have been lost in a worker crash/restart before its status
   * update landed.  Surface it as `failed` so operators can see it rather
   * than having it silently loop back into the queue.
   * Returns the count of rows that were transitioned.
   */
  async markStaleInFlightMessagesFailed(): Promise<number> {
    const result = await db.execute(sql`
      UPDATE outbound_messages
      SET status = 'failed',
          error  = 'Worker crash detected: message was stuck in sending state for more than 5 minutes'
      WHERE status = 'sending'
        AND sending_at < NOW() - INTERVAL '5 minutes'
    `);
    return (result as any).rowCount ?? 0;
  }


  async getOutboundStats(campaignId: number) {
    const result = await db.select({
      sent: sql<number>`count(*) filter (where ${outboundMessages.status} = 'sent' or ${outboundMessages.status} = 'delivered' or ${outboundMessages.status} = 'opened' or ${outboundMessages.status} = 'replied')`,
      opened: sql<number>`count(*) filter (where ${outboundMessages.status} = 'opened' or ${outboundMessages.status} = 'replied')`,
      replied: sql<number>`count(*) filter (where ${outboundMessages.status} = 'replied')`,
      bounced: sql<number>`count(*) filter (where ${outboundMessages.status} = 'bounced')`,
    }).from(outboundMessages).where(eq(outboundMessages.campaignId, campaignId));
    return result[0] ?? { sent: 0, opened: 0, replied: 0, bounced: 0 };
  }

  /**
   * Return messages that are stuck in `sending` status for more than 60 seconds.
   * These are in-flight rows that may have been orphaned by a worker crash before
   * the 5-minute stale-cleanup fires.  Surfacing them early lets operators
   * investigate a partial failure before it turns into a failure flood.
   */
  async getStuckSendingMessages() {
    return await db.select().from(outboundMessages)
      .where(
        and(
          eq(outboundMessages.status, "sending"),
          lt(outboundMessages.sendingAt, sql`NOW() - INTERVAL '60 seconds'`),
        )
      )
      .orderBy(asc(outboundMessages.sendingAt));
  }

  // ---------------------------------------------------------------------------
  // Campaign Previews
  // ---------------------------------------------------------------------------

  async createCampaignPreview(data: InsertCampaignPreview): Promise<CampaignPreview> {
    const [row] = await db.insert(campaignPreviews).values(data).returning();
    return row;
  }

  async getCampaignPreview(id: number): Promise<CampaignPreview | undefined> {
    const [row] = await db.select().from(campaignPreviews).where(eq(campaignPreviews.id, id));
    return row;
  }

  async getLatestCampaignPreview(campaignId: number): Promise<CampaignPreview | undefined> {
    const [row] = await db.select()
      .from(campaignPreviews)
      .where(eq(campaignPreviews.campaignId, campaignId))
      .orderBy(desc(campaignPreviews.createdAt))
      .limit(1);
    return row;
  }

  async updateCampaignPreview(id: number, updates: Partial<CampaignPreview>): Promise<CampaignPreview> {
    const [row] = await db.update(campaignPreviews).set(updates).where(eq(campaignPreviews.id, id)).returning();
    return row;
  }

  async markInterruptedCampaignPreviews(): Promise<void> {
    // Preserves all diagnostic fields (counts, hash, timestamps).
    // Only flips status; does NOT clear eligibleCount or other columns.
    await db.update(campaignPreviews)
      .set({ status: "interrupted" })
      .where(eq(campaignPreviews.status, "running"));
  }

  // Atomic consumption: single conditional UPDATE that sets consumed_at only when
  // the row is still done and unconsumed.  Two concurrent requests for the same
  // previewId will each get a RETURNING result from Postgres — but only ONE will
  // match the WHERE (consumed_at IS NULL); the other gets an empty array → null.
  // This is safe without application-level locks because Postgres UPDATE is atomic.
  async consumeCampaignPreviewAtomic(id: number): Promise<CampaignPreview | null> {
    const [row] = await db.update(campaignPreviews)
      .set({ consumedAt: new Date() })
      .where(and(
        eq(campaignPreviews.id, id),
        eq(campaignPreviews.status, "done"),
        isNull(campaignPreviews.consumedAt),
      ))
      .returning();
    return row ?? null;
  }
  }
  