// Auto-generated by storage split. Domain: contacts.
  // Methods are mixed into DatabaseStorage in server/storage.ts.
  import { db, pool } from "../db";
import {
  liveChats, liveChatMessages,
  type LiveChat, type InsertLiveChat, type LiveChatMessage, type InsertLiveChatMessage,
  contacts, companies, deals, tickets, tasks, documents, auditLogs, notifications, workflowRuns, workflows, rfis, users,
  chargebacks,
  type Chargeback, type InsertChargeback, type UpdateChargebackRequest,
  messageTemplates, collateralPackets, ghlActivityLog, slaConfigs,
  prospects, prospectLists, enrichmentJobs, campaigns, campaignSteps, outboundMessages, notes,
  emailLogs, callLogs, stageAutomationRules, followUpSequences, sequenceSteps, sequenceEnrollments,
  sunbizEntities, consentAuditLogs, calendarEvents,
  merchantApplications, merchantProfiles, equipmentOrders, agents, agentQuotas, agentMerchants, residualReports, merchantResiduals,
  healthAlerts, dealCompetitors, partners, referrals, commissionTiers, knowledgeBase, reviewRequests, testimonialSubmissions, onboardingSteps, midDailyStats,
  sdrMerchants, sdrMerchantContacts, sdrLeadState, sdrLeadEvents, sdrChannelAttempts, sdrComplianceState,
  sendingIdentities,
  leadDiscoveryJobs, leadDiscoveryResults,
  type SendingIdentity, type InsertSendingIdentity,
  businesses, businessAliases, businessLocations, leadSources, enrichmentRuns,
  type LeadDiscoveryJob, type InsertLeadDiscoveryJob,
  type LeadDiscoveryResult, type InsertLeadDiscoveryResult,
  type Business, type InsertBusiness, type UpdateBusinessRequest,
  type BusinessAlias, type InsertBusinessAlias,
  type BusinessLocation, type InsertBusinessLocation,
  type LeadSource, type InsertLeadSource,
  type EnrichmentRun, type InsertEnrichmentRun,
  type SdrMerchant, type InsertSdrMerchant,
  type SdrMerchantContact, type InsertSdrMerchantContact,
  type SdrLeadState, type InsertSdrLeadState,
  type SdrLeadEvent, type InsertSdrLeadEvent,
  type SdrChannelAttempt, type InsertSdrChannelAttempt,
  type SdrComplianceState, type InsertSdrComplianceState,
  type InsertContact, type UpdateContactRequest,
  type InsertCompany,
  type InsertDeal, type UpdateDealRequest,
  type InsertTicket, type UpdateTicketRequest,
  type InsertTask, type UpdateTaskRequest,
  type InsertDocument,
  type InsertAuditLog,
  type InsertNotification,
  type InsertWorkflow, type UpdateWorkflowRequest,
  type InsertWorkflowRun,
  type InsertRfi, type UpdateRfiRequest,
  type InsertMessageTemplate, type MessageTemplate,
  type InsertCollateralPacket,
  type InsertGhlActivityLog,
  type InsertSlaConfig,
  type Prospect, type InsertProspect, type UpdateProspectRequest,
  type InsertProspectList,
  type InsertEnrichmentJob,
  type InsertCampaign, type UpdateCampaignRequest,
  type InsertCampaignStep,
  type InsertOutboundMessage, type UpdateOutboundMessageRequest,
  type InsertNote,
  type InsertEmailLog, type InsertCallLog, type InsertStageAutomationRule, type InsertFollowUpSequence, type InsertSequenceStep, type InsertSequenceEnrollment,
  type InsertSunbizEntity, type UpdateSunbizEntityRequest, type SunbizEntity,
  type InsertMerchantApplication, type MerchantApplication,
  type InsertMerchantProfile, type MerchantProfile,
  type InsertEquipmentOrder, type EquipmentOrder,
  type InsertAgent, type Agent,
  type InsertAgentMerchant, type AgentMerchant,
  type InsertAgentQuota, type AgentQuota,
  type InsertResidualReport, type ResidualReport,
  type InsertMerchantResidual, type MerchantResidual,
  type InsertHealthAlert, type HealthAlert,
  type InsertDealCompetitor, type DealCompetitor,
  type InsertPartner, type Partner,
  type InsertReferral, type Referral,
  type InsertCommissionTier, type CommissionTier,
  type InsertKnowledgeBaseArticle, type KnowledgeBaseArticle,
  type InsertReviewRequest, type ReviewRequest,
  type InsertTestimonialSubmission, type TestimonialSubmission,
  type InsertOnboardingStep, type OnboardingStep,
  type InsertConsentAuditLog, type ConsentAuditLog,
  type CalendarEvent, type InsertCalendarEvent,
  systemSettings,
  dataDeleteRequests,
  type DataDeleteRequest, type InsertDataDeleteRequest,
  comments, ticketComments, contactCompanies, pipelineStages, notificationPreferences, savedFilters,
  type Comment, type InsertComment,
  type TicketComment, type InsertTicketComment,
  type ContactCompany, type InsertContactCompany,
  type PipelineStage, type InsertPipelineStage,
  type NotificationPreference, type InsertNotificationPreference,
  type SavedFilter, type InsertSavedFilter,
  csvImports, type CsvImport, type InsertCsvImport,
  generatedBlogPosts,
  type GeneratedBlogPost, type InsertGeneratedBlogPost,
  type UpdateSdrLeadState,
  ghlWorkflowMappings, type GhlWorkflowMapping,
  npsResponses, type NpsResponse, type InsertNpsResponse,
  merchantReferrals, type MerchantReferral, type InsertMerchantReferral,
  retentionCampaignConfigs, type RetentionCampaignConfig, type InsertRetentionCampaignConfig,
  type MidDailyStat, type InsertMidDailyStat,
  roleplaySessions, type RoleplaySession, type InsertRoleplaySession,
  roleplayExchanges, type RoleplayExchange, type InsertRoleplayExchange,
  leaderboardSettings, type LeaderboardSettings,
} from "@shared/schema";
import { eq, desc, and, lt, isNull, ne, sql, asc, gte, lte, inArray, or, ilike, count } from "drizzle-orm";
import { coerceDateFields } from "../utils/date-coerce";
  import { type PaginationParams, type PaginatedResult, normalizePagination } from "./_shared";

  export class ContactsStorage {
    async getContacts(params?: PaginationParams & { emailStatus?: string }) {
    const { limit, offset } = normalizePagination(params);
    const emailStatus = params?.emailStatus;
    const whereClause = emailStatus ? eq(contacts.emailStatus, emailStatus) : undefined;
    const [totalResult] = await db.select({ count: count() }).from(contacts).where(whereClause);
    const data = await db.select().from(contacts).where(whereClause).orderBy(desc(contacts.createdAt)).limit(limit).offset(offset);
    return { data, total: totalResult.count, limit, offset };
  }


  async getContact(id: number) {
    const [contact] = await db.select().from(contacts).where(eq(contacts.id, id));
    return contact;
  }

  async getContactByGhlContactId(ghlContactId: string) {
    const [contact] = await db.select().from(contacts).where(eq(contacts.ghlContactId, ghlContactId));
    return contact;
  }


  async getContactByEmail(email: string) {
    const [contact] = await db.select().from(contacts).where(and(eq(contacts.email, email.toLowerCase()), isNull(contacts.archivedAt)));
    return contact;
  }

  async getContactByPhone(phone: string): Promise<typeof contacts.$inferSelect | null> {
    const digits = phone.replace(/\D/g, "").slice(-10);
    if (digits.length < 10) return null;
    const [contact] = await db.select().from(contacts)
      .where(and(
        isNull(contacts.archivedAt),
        sql`regexp_replace(${contacts.phone}, '[^0-9]', '', 'g') LIKE ${'%' + digits}`,
      ));
    return contact ?? null;
  }

  async getContactByCompanyName(companyName: string) {
    const [contact] = await db.select().from(contacts)
      .where(and(
        isNull(contacts.archivedAt),
        sql`lower(${contacts.companyName}) = lower(${companyName})`,
      ));
    return contact;
  }


  async createContact(insertContact: InsertContact, auditCtx?: { userId?: string | null; actorType?: string; actorId?: string | null }) {
    const { auditChange } = await import("../services/audit-change");
    return await db.transaction(async (tx) => {
      const [contact] = await tx.insert(contacts).values(insertContact).returning();
      await auditChange({
        userId: auditCtx?.userId ?? null,
        actorType: (auditCtx?.actorType as any) ?? "user",
        actorId: auditCtx?.actorId ?? null,
        action: "contact_created",
        entityType: "contact",
        entityId: contact.id,
        before: null,
        after: contact as unknown as Record<string, unknown>,
      }, tx);
      return contact;
    });
  }


  async updateContact(id: number, updates: UpdateContactRequest, auditCtx?: { userId?: string | null; actorType?: string; actorId?: string | null }) {
    const { auditChange } = await import("../services/audit-change");
    const coercedUpdates = coerceDateFields(
      updates as Record<string, unknown>,
      ["lastScoredAt", "smsOptInAt", "emailOptInAt", "lastContactedAt", "coolingUntil",
       "linkedinEnrichedAt", "archivedAt", "lastSyncedAt", "bouncedAt",
       "lastVoicemailAt", "offerRoutedAt"],
    );
    const [before] = await db.select().from(contacts).where(eq(contacts.id, id));
    return await db.transaction(async (tx) => {
      const [updated] = await tx.update(contacts).set({ ...coercedUpdates, updatedAt: new Date() } as typeof contacts.$inferInsert).where(eq(contacts.id, id)).returning();
      if (updated) {
        await auditChange({
          userId: auditCtx?.userId ?? null,
          actorType: (auditCtx?.actorType as any) ?? "user",
          actorId: auditCtx?.actorId ?? null,
          action: "contact_updated",
          entityType: "contact",
          entityId: id,
          before: before as unknown as Record<string, unknown>,
          after: updated as unknown as Record<string, unknown>,
        }, tx);
      }
      return updated;
    });
  }

  async syncUpdateContact(id: number, updates: UpdateContactRequest) {
    // Intentionally does NOT bump updatedAt so that updatedAt stays as the last
    // genuine user-edit timestamp and conflict detection remains accurate.
    const [before] = await db.select().from(contacts).where(eq(contacts.id, id));
    const [updated] = await db.update(contacts).set(updates).where(eq(contacts.id, id)).returning();
    if (updated) {
      const { auditChange } = await import("../services/audit-change");
      auditChange({ actorType: "system", action: "contact_sync_updated", entityType: "contact", entityId: id,
        before: before as unknown as Record<string, unknown>, after: updated as unknown as Record<string, unknown> }).catch(() => {});
    }
    return updated;
  }


  async getCompanies() {
    return await db.select().from(companies).orderBy(desc(companies.createdAt));
  }


  async createCompany(insertCompany: InsertCompany) {
    const [company] = await db.insert(companies).values(insertCompany).returning();
    return company;
  }


  async getCompany(id: number) {
    const [company] = await db.select().from(companies).where(eq(companies.id, id));
    return company ?? undefined;
  }


  async updateCompany(id: number, updates: Partial<InsertCompany>) {
    const [updated] = await db.update(companies).set(updates).where(eq(companies.id, id)).returning();
    return updated ?? undefined;
  }


  async getContactCompaniesByCompany(companyId: number): Promise<ContactCompany[]> {
    return db.select().from(contactCompanies).where(eq(contactCompanies.companyId, companyId));
  }


  async getContactCompanies(contactId: number): Promise<ContactCompany[]> {
    return db.select().from(contactCompanies).where(eq(contactCompanies.contactId, contactId)).orderBy(desc(contactCompanies.createdAt));
  }


  async addContactCompany(link: InsertContactCompany): Promise<ContactCompany> {
    const [created] = await db.insert(contactCompanies).values(link).returning();
    return created;
  }


  async removeContactCompany(id: number): Promise<void> {
    await db.delete(contactCompanies).where(eq(contactCompanies.id, id));
  }


  async archiveContact(id: number, auditCtx?: { userId?: string | null; actorType?: string; actorId?: string | null }) {
    const { auditChange } = await import("../services/audit-change");
    const [before] = await db.select().from(contacts).where(eq(contacts.id, id));
    return await db.transaction(async (tx) => {
      const [updated] = await tx.update(contacts).set({ archivedAt: new Date() }).where(eq(contacts.id, id)).returning();
      if (updated) {
        await auditChange({ userId: auditCtx?.userId ?? null, actorType: (auditCtx?.actorType as any) ?? "user", actorId: auditCtx?.actorId ?? null,
          action: "contact_archived", entityType: "contact", entityId: id,
          before: before as unknown as Record<string, unknown>, after: updated as unknown as Record<string, unknown> }, tx);
      }
      return updated;
    });
  }


  async restoreContact(id: number, auditCtx?: { userId?: string | null; actorType?: string; actorId?: string | null }) {
    const { auditChange } = await import("../services/audit-change");
    const [before] = await db.select().from(contacts).where(eq(contacts.id, id));
    return await db.transaction(async (tx) => {
      const [updated] = await tx.update(contacts).set({ archivedAt: null }).where(eq(contacts.id, id)).returning();
      if (updated) {
        await auditChange({ userId: auditCtx?.userId ?? null, actorType: (auditCtx?.actorType as any) ?? "user", actorId: auditCtx?.actorId ?? null,
          action: "contact_restored", entityType: "contact", entityId: id,
          before: before as unknown as Record<string, unknown>, after: updated as unknown as Record<string, unknown> }, tx);
      }
      return updated;
    });
  }


  async findDuplicateContacts() {
    const t0 = Date.now();

    // Find duplicate emails via SQL GROUP BY on normalized email — no full-table fetch
    const emailDupGroups = await db
      .select({
        normalizedEmail: sql<string>`lower(trim(${contacts.email}))`,
        ids: sql<string>`array_agg(${contacts.id} ORDER BY ${contacts.createdAt} DESC)`,
      })
      .from(contacts)
      .where(and(isNull(contacts.archivedAt), sql`${contacts.email} IS NOT NULL AND trim(${contacts.email}) != ''`))
      .groupBy(sql`lower(trim(${contacts.email}))`)
      .having(sql`count(*) > 1`);

    // Find duplicate phones via SQL GROUP BY on normalized phone
    const phoneDupGroups = await db
      .select({
        normalizedPhone: sql<string>`regexp_replace(${contacts.phone}, '[^0-9]', '', 'g')`,
        ids: sql<string>`array_agg(${contacts.id} ORDER BY ${contacts.createdAt} DESC)`,
      })
      .from(contacts)
      .where(and(
        isNull(contacts.archivedAt),
        sql`${contacts.phone} IS NOT NULL`,
        sql`length(regexp_replace(${contacts.phone}, '[^0-9]', '', 'g')) >= 10`,
      ))
      .groupBy(sql`regexp_replace(${contacts.phone}, '[^0-9]', '', 'g')`)
      .having(sql`count(*) > 1`);

    // Collect all duplicate contact IDs in one set
    const allDupIds: number[] = [];
    const seen = new Set<number>();

    for (const row of emailDupGroups) {
      const ids: number[] = Array.isArray(row.ids) ? row.ids : (row.ids as unknown as string).replace(/[{}]/g, '').split(',').map(Number);
      for (const id of ids) allDupIds.push(id);
    }
    for (const row of phoneDupGroups) {
      const ids: number[] = Array.isArray(row.ids) ? row.ids : (row.ids as unknown as string).replace(/[{}]/g, '').split(',').map(Number);
      for (const id of ids) allDupIds.push(id);
    }

    // Fetch only the duplicate contacts in a single query
    const uniqueDupIds = [...new Set(allDupIds)];
    const dupContacts = uniqueDupIds.length > 0
      ? await db.select().from(contacts).where(inArray(contacts.id, uniqueDupIds))
      : [];
    const contactById = new Map(dupContacts.map(c => [c.id, c]));

    const duplicates: { email: string; phone: string; contacts: typeof dupContacts }[] = [];

    for (const row of emailDupGroups) {
      const ids: number[] = Array.isArray(row.ids) ? row.ids : (row.ids as unknown as string).replace(/[{}]/g, '').split(',').map(Number);
      if (ids.some(id => seen.has(id))) continue;
      ids.forEach(id => seen.add(id));
      const group = ids.map(id => contactById.get(id)).filter(Boolean) as typeof dupContacts;
      duplicates.push({ email: row.normalizedEmail ?? '', phone: '', contacts: group });
    }

    for (const row of phoneDupGroups) {
      const ids: number[] = Array.isArray(row.ids) ? row.ids : (row.ids as unknown as string).replace(/[{}]/g, '').split(',').map(Number);
      if (ids.some(id => seen.has(id))) continue;
      ids.forEach(id => seen.add(id));
      const group = ids.map(id => contactById.get(id)).filter(Boolean) as typeof dupContacts;
      duplicates.push({ email: '', phone: row.normalizedPhone ?? '', contacts: group });
    }

    console.log(`[findDuplicateContacts] ${duplicates.length} groups in ${Date.now() - t0}ms`);
    return duplicates;
  }


  async mergeContacts(primaryId: number, duplicateId: number, auditCtx?: { userId?: string | null; actorType?: string }) {
    const primary = await this.getContact(primaryId);
    const duplicate = await this.getContact(duplicateId);
    if (!primary || !duplicate) return undefined;
    const { auditChange } = await import("../services/audit-change");
    await db.transaction(async (tx) => {
      await tx.update(deals).set({ contactId: primaryId }).where(eq(deals.contactId, duplicateId));
      await tx.update(tickets).set({ contactId: primaryId }).where(eq(tickets.contactId, duplicateId));
      await tx.update(tasks).set({ contactId: primaryId }).where(eq(tasks.contactId, duplicateId));
      await tx.update(documents).set({ contactId: primaryId }).where(eq(documents.contactId, duplicateId));
      await tx.update(contacts).set({ archivedAt: new Date(), notes: `[Merged into Contact #${primaryId}] ${duplicate.notes || ''}` }).where(eq(contacts.id, duplicateId));
      await auditChange({ userId: auditCtx?.userId ?? null, actorType: (auditCtx?.actorType as any) ?? "user",
        action: "contact_merged", entityType: "contact", entityId: duplicateId,
        before: duplicate as unknown as Record<string, unknown>,
        after: { mergedIntoContactId: primaryId, archivedAt: new Date() } }, tx);
    });
    return primary;
  }


  async getContactsByIds(ids: number[]) {
    if (ids.length === 0) return [];
    const CHUNK = 500;
    const results: typeof contacts.$inferSelect[] = [];
    for (let i = 0; i < ids.length; i += CHUNK) {
      const chunk = ids.slice(i, i + CHUNK);
      const rows = await db.select().from(contacts).where(inArray(contacts.id, chunk));
      results.push(...rows);
    }
    return results;
  }

  async getContactsByPartnerOrg(partnerOrgId: number) {
    return await db.select().from(contacts).where(eq(contacts.partnerOrgId, partnerOrgId)).orderBy(desc(contacts.createdAt));
  }

  async getChildLocations(parentContactId: number) {
    return await db.select().from(contacts)
      .where(and(eq(contacts.parentContactId, parentContactId), isNull(contacts.archivedAt)))
      .orderBy(asc(contacts.locationName), asc(contacts.companyName));
  }

  async getParentAccount(contactId: number) {
    const [contact] = await db.select().from(contacts).where(eq(contacts.id, contactId));
    if (!contact?.parentContactId) return null;
    const [parent] = await db.select().from(contacts).where(eq(contacts.id, contact.parentContactId));
    return parent ?? null;
  }

  async getContactVerticalCounts(): Promise<Array<{ vertical: string; count: number }>> {
    const { normalizeDiscoveryVertical } = await import("../services/sdr/lead-finder");
    const rows = await db
      .select({ vertical: contacts.vertical, cnt: count() })
      .from(contacts)
      .where(and(isNull(contacts.archivedAt), sql`${contacts.vertical} IS NOT NULL AND trim(${contacts.vertical}) != ''`))
      .groupBy(contacts.vertical);

    const tally = new Map<string, number>();
    for (const row of rows) {
      const canonical = normalizeDiscoveryVertical({ rawCategory: row.vertical }).canonicalVertical;
      tally.set(canonical, (tally.get(canonical) ?? 0) + row.cnt);
    }
    return Array.from(tally.entries())
      .map(([vertical, cnt]) => ({ vertical, count: cnt }))
      .sort((a, b) => b.count - a.count);
  }

  async getContactsByVertical(vertical: string, limit?: number): Promise<Array<{ id: number; firstName: string; lastName: string; email: string; phone: string; vertical: string | null }>> {
    const { normalizeDiscoveryVertical } = await import("../services/sdr/lead-finder");
    const rows = await db
      .select({ id: contacts.id, firstName: contacts.firstName, lastName: contacts.lastName, email: contacts.email, phone: contacts.phone, vertical: contacts.vertical })
      .from(contacts)
      .where(and(isNull(contacts.archivedAt), sql`${contacts.vertical} IS NOT NULL AND trim(${contacts.vertical}) != ''`))
      .orderBy(desc(contacts.createdAt));

    const matching = rows.filter(r => {
      const canonical = normalizeDiscoveryVertical({ rawCategory: r.vertical }).canonicalVertical;
      return canonical === vertical;
    });
    return limit ? matching.slice(0, limit) : matching;
  }

  async getContactsForCampaignAudience(opts: {
    verticals?: string[];
    minCompletenessScore?: number;
    limit?: number;
  }): Promise<Array<{
    id: number;
    firstName: string;
    lastName: string;
    email: string;
    phone: string | null;
    vertical: string | null;
    companyName: string | null;
    city: string | null;
    state: string | null;
    dataCompletenessScore: number | null;
    emailStatus: string;
    optedOutEmail: boolean | null;
  }>> {
    const { normalizeDiscoveryVertical } = await import("../services/sdr/lead-finder");

    // SQL-level pre-filter: archived-out, bad email status, opted out.
    // We cap at sqlLimit to protect memory — best-scored candidates first.
    const sqlLimit = (opts.limit ?? 5000) * (opts.verticals && opts.verticals.length ? 10 : 1);
    const cappedSqlLimit = Math.min(sqlLimit, 50000);

    const rows = await db
      .select({
        id: contacts.id,
        firstName: contacts.firstName,
        lastName: contacts.lastName,
        email: contacts.email,
        phone: contacts.phone,
        vertical: contacts.vertical,
        companyName: contacts.companyName,
        city: contacts.city,
        state: contacts.state,
        dataCompletenessScore: contacts.dataCompletenessScore,
        emailStatus: contacts.emailStatus,
        optedOutEmail: contacts.optedOutEmail,
      })
      .from(contacts)
      .where(
        and(
          isNull(contacts.archivedAt),
          sql`${contacts.email} IS NOT NULL AND trim(${contacts.email}) != ''`,
          ne(contacts.emailStatus, "bounced"),
          ne(contacts.emailStatus, "invalid"),
          sql`${contacts.optedOutEmail} IS NOT TRUE`,
          opts.minCompletenessScore != null
            ? gte(contacts.dataCompletenessScore, opts.minCompletenessScore)
            : undefined,
        )
      )
      .orderBy(desc(contacts.dataCompletenessScore), desc(contacts.leadScore))
      .limit(cappedSqlLimit);

    if (!opts.verticals || opts.verticals.length === 0) {
      return rows.slice(0, opts.limit ?? 5000);
    }

    const targetSet = new Set(opts.verticals);
    const matched = rows.filter((r) => {
      if (!r.vertical) return false;
      const canonical = normalizeDiscoveryVertical({ rawCategory: r.vertical }).canonicalVertical;
      return targetSet.has(canonical);
    });
    return matched.slice(0, opts.limit ?? 5000);
  }

  async getGroupKpis(parentContactId: number) {
    const children = await this.getChildLocations(parentContactId);
    const allIds = [parentContactId, ...children.map(c => c.id)];
    if (allIds.length === 0) return { locationCount: 0, totalDeals: 0, closedWonCount: 0, totalVolume: 0 };

    const groupDeals = await db.select().from(deals)
      .where(and(inArray(deals.contactId, allIds), isNull(deals.archivedAt)));

    let totalVolume = 0;
    let closedWonCount = 0;
    const midSet = new Set<string>();
    for (const d of groupDeals) {
      if (d.totalVolume) totalVolume += parseFloat(d.totalVolume) || 0;
      if (d.stage === "Closed Won") closedWonCount++;
      if (d.mid) midSet.add(d.mid);
    }

    const [parent] = await db.select({ managementType: contacts.managementType }).from(contacts).where(eq(contacts.id, parentContactId));

    return {
      locationCount: children.length,
      totalDeals: groupDeals.length,
      closedWonCount,
      totalVolume,
      activeMids: midSet.size,
      locationIds: allIds,
      managementType: parent?.managementType ?? "unknown",
    };
  }
}
