// Auto-generated by storage split. Domain: deals.
  // Methods are mixed into DatabaseStorage in server/storage.ts.
  import { db, pool } from "../db";
import {
  liveChats, liveChatMessages,
  type LiveChat, type InsertLiveChat, type LiveChatMessage, type InsertLiveChatMessage,
  contacts, companies, deals, tickets, tasks, documents, auditLogs, notifications, workflowRuns, workflows, rfis, users,
  chargebacks,
  type Chargeback, type InsertChargeback, type UpdateChargebackRequest,
  messageTemplates, collateralPackets, ghlActivityLog, slaConfigs,
  prospects, prospectLists, enrichmentJobs, campaigns, campaignSteps, outboundMessages, notes,
  emailLogs, callLogs, stageAutomationRules, followUpSequences, sequenceSteps, sequenceEnrollments,
  sunbizEntities, consentAuditLogs, calendarEvents,
  merchantApplications, merchantProfiles, equipmentOrders, agents, agentQuotas, agentMerchants, residualReports, merchantResiduals,
  healthAlerts, dealCompetitors, partners, referrals, commissionTiers, knowledgeBase, reviewRequests, testimonialSubmissions, onboardingSteps, midDailyStats,
  sdrMerchants, sdrMerchantContacts, sdrLeadState, sdrLeadEvents, sdrChannelAttempts, sdrComplianceState,
  sendingIdentities,
  leadDiscoveryJobs, leadDiscoveryResults,
  type SendingIdentity, type InsertSendingIdentity,
  businesses, businessAliases, businessLocations, leadSources, enrichmentRuns,
  type LeadDiscoveryJob, type InsertLeadDiscoveryJob,
  type LeadDiscoveryResult, type InsertLeadDiscoveryResult,
  type Business, type InsertBusiness, type UpdateBusinessRequest,
  type BusinessAlias, type InsertBusinessAlias,
  type BusinessLocation, type InsertBusinessLocation,
  type LeadSource, type InsertLeadSource,
  type EnrichmentRun, type InsertEnrichmentRun,
  type SdrMerchant, type InsertSdrMerchant,
  type SdrMerchantContact, type InsertSdrMerchantContact,
  type SdrLeadState, type InsertSdrLeadState,
  type SdrLeadEvent, type InsertSdrLeadEvent,
  type SdrChannelAttempt, type InsertSdrChannelAttempt,
  type SdrComplianceState, type InsertSdrComplianceState,
  type InsertContact, type UpdateContactRequest,
  type InsertCompany,
  type InsertDeal, type UpdateDealRequest,
  type InsertTicket, type UpdateTicketRequest,
  type InsertTask, type UpdateTaskRequest,
  type InsertDocument,
  type InsertAuditLog,
  type InsertNotification,
  OPEN_SALES_LEAD_STAGES,
  type InsertWorkflow, type UpdateWorkflowRequest,
  type InsertWorkflowRun,
  type InsertRfi, type UpdateRfiRequest,
  type InsertMessageTemplate, type MessageTemplate,
  type InsertCollateralPacket,
  type InsertGhlActivityLog,
  type InsertSlaConfig,
  type Prospect, type InsertProspect, type UpdateProspectRequest,
  type InsertProspectList,
  type InsertEnrichmentJob,
  type InsertCampaign, type UpdateCampaignRequest,
  type InsertCampaignStep,
  type InsertOutboundMessage, type UpdateOutboundMessageRequest,
  type InsertNote,
  type InsertEmailLog, type InsertCallLog, type InsertStageAutomationRule, type InsertFollowUpSequence, type InsertSequenceStep, type InsertSequenceEnrollment,
  type InsertSunbizEntity, type UpdateSunbizEntityRequest, type SunbizEntity,
  type InsertMerchantApplication, type MerchantApplication,
  type InsertMerchantProfile, type MerchantProfile,
  type InsertEquipmentOrder, type EquipmentOrder,
  type InsertAgent, type Agent,
  type InsertAgentMerchant, type AgentMerchant,
  type InsertAgentQuota, type AgentQuota,
  type InsertResidualReport, type ResidualReport,
  type InsertMerchantResidual, type MerchantResidual,
  type InsertHealthAlert, type HealthAlert,
  type InsertDealCompetitor, type DealCompetitor,
  type InsertPartner, type Partner,
  type InsertReferral, type Referral,
  type InsertCommissionTier, type CommissionTier,
  type InsertKnowledgeBaseArticle, type KnowledgeBaseArticle,
  type InsertReviewRequest, type ReviewRequest,
  type InsertTestimonialSubmission, type TestimonialSubmission,
  type InsertOnboardingStep, type OnboardingStep,
  type InsertConsentAuditLog, type ConsentAuditLog,
  type CalendarEvent, type InsertCalendarEvent,
  systemSettings,
  dataDeleteRequests,
  type DataDeleteRequest, type InsertDataDeleteRequest,
  comments, ticketComments, contactCompanies, pipelineStages, notificationPreferences, savedFilters,
  type Comment, type InsertComment,
  type TicketComment, type InsertTicketComment,
  type ContactCompany, type InsertContactCompany,
  type PipelineStage, type InsertPipelineStage,
  type NotificationPreference, type InsertNotificationPreference,
  type SavedFilter, type InsertSavedFilter,
  csvImports, type CsvImport, type InsertCsvImport,
  generatedBlogPosts,
  type GeneratedBlogPost, type InsertGeneratedBlogPost,
  type UpdateSdrLeadState,
  ghlWorkflowMappings, type GhlWorkflowMapping,
  npsResponses, type NpsResponse, type InsertNpsResponse,
  merchantReferrals, type MerchantReferral, type InsertMerchantReferral,
  retentionCampaignConfigs, type RetentionCampaignConfig, type InsertRetentionCampaignConfig,
  type MidDailyStat, type InsertMidDailyStat,
  roleplaySessions, type RoleplaySession, type InsertRoleplaySession,
  roleplayExchanges, type RoleplayExchange, type InsertRoleplayExchange,
  leaderboardSettings, type LeaderboardSettings,
} from "@shared/schema";
import { eq, desc, and, lt, isNull, ne, sql, asc, gte, lte, inArray, or, ilike, count } from "drizzle-orm";
  import { type PaginationParams, type PaginatedResult, normalizePagination } from "./_shared";
import { auditChange } from "../services/audit-change";
import { deriveLinkedDealClassInTransaction } from "../services/commercial-classification-authority";

export interface ConversionSalesDealAuthorityParams {
  contactId: number;
  estimatedVolume?: string | null;
  auditCtx?: { userId?: string | null; actorType?: "user" | "ai" | "system"; actorId?: string | null };
}

export interface ConversionSalesDealAuthorityResult {
  deal: typeof deals.$inferSelect;
  created: boolean;
}

const ASSIGNED_OWNER_EMAIL = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

/**
 * Transaction-only conversion deal authority.
 *
 * The caller supplies its durable transaction. This function never starts one,
 * so the contact lock, class derivation, deal/audit insert, and caller's final
 * claim update have one rollback boundary.
 */
export async function getOrCreateConversionSalesDeal(
  tx: any,
  params: ConversionSalesDealAuthorityParams,
): Promise<ConversionSalesDealAuthorityResult> {
  const openSalesStages = sql.join(
    OPEN_SALES_LEAD_STAGES.map((stage) => sql`${stage}`),
    sql`, `,
  );

  // Lock the canonical contact before inspecting its deal set or assignment.
  const contact = ((await tx.execute(sql`
    SELECT id, assigned_to, partner_org_id
    FROM contacts
    WHERE id = ${params.contactId}
    FOR UPDATE
  `)) as { rows?: Array<{ id: number; assigned_to: string | null; partner_org_id: number | null }> }).rows?.[0];

  if (!contact) {
    throw new Error(`CONVERSION_CANONICAL_CONTACT_NOT_FOUND:${params.contactId}`);
  }

  const existing = ((await tx.execute(sql`
    SELECT *
    FROM deals
    WHERE contact_id = ${params.contactId}
      AND pipeline = 'sales'
      AND record_class = 'production'
      AND archived_at IS NULL
      AND stage IN (${openSalesStages})
    ORDER BY updated_at DESC NULLS LAST, id DESC
    LIMIT 1
    FOR UPDATE
  `)) as { rows?: typeof deals.$inferSelect[] }).rows?.[0];

  if (existing) return { deal: existing, created: false };

  const assignedTo = contact.assigned_to?.trim() ?? "";
  let owner: string | null = null;
  if (ASSIGNED_OWNER_EMAIL.test(assignedTo)) {
    const assignedUser = ((await tx.execute(sql`
      SELECT id
      FROM users
      WHERE lower(email) = lower(${assignedTo})
      LIMIT 1
    `)) as { rows?: Array<{ id: string }> }).rows?.[0];
    if (assignedUser) owner = assignedTo;
  }

  const recordClass = await deriveLinkedDealClassInTransaction(tx, params.contactId);
  const [deal] = await tx.insert(deals).values({
    contactId: params.contactId,
    pipeline: "sales",
    stage: "New Lead",
    owner,
    partnerOrgId: contact.partner_org_id ?? null,
    notes: `Estimated volume: ${params.estimatedVolume || "N/A"}`,
    recordClass,
  } as InsertDeal).returning();

  await auditChange({
    userId: params.auditCtx?.userId ?? null,
    actorType: params.auditCtx?.actorType ?? "system",
    actorId: params.auditCtx?.actorId ?? null,
    action: "deal_created",
    entityType: "deal",
    entityId: deal.id,
    before: null,
    after: deal as unknown as Record<string, unknown>,
  }, tx);

  return { deal, created: true };
}

  export class DealsStorage {
    async getDeals(params?: PaginationParams & { ownerEmail?: string; recordClass?: "production" }) {
    const { limit, offset } = normalizePagination(params);
    const ownership = params?.ownerEmail ? or(eq(deals.owner, params.ownerEmail), isNull(deals.owner)) : undefined;
    const whereClause = params?.recordClass === "production"
      ? and(isNull(deals.archivedAt), eq(deals.recordClass, "production"), ownership)
      : and(isNull(deals.archivedAt), ownership);
    const [totalResult] = await db.select({ count: count() }).from(deals).where(whereClause);
    const rows = await db
      .select({
        deal: deals,
        contactFirstName: contacts.firstName,
        contactLastName: contacts.lastName,
        contactCompanyName: contacts.companyName,
        contactEmail: contacts.email,
        contactPhone: contacts.phone,
        contactEmployeeCount: contacts.employeeCount, // #1146
        contactLeadSource: contacts.leadSource, // #1473 — show source batch on pipeline cards
      })
      .from(deals)
      .leftJoin(contacts, eq(deals.contactId, contacts.id))
      .where(whereClause)
      .orderBy(desc(deals.updatedAt), desc(deals.id))
      .limit(limit)
      .offset(offset);
    const data = rows.map(({ deal, contactFirstName, contactLastName, contactCompanyName, contactEmail, contactPhone, contactEmployeeCount, contactLeadSource }) => ({
      ...deal,
      contactName: (contactFirstName || contactLastName)
        ? `${contactFirstName || ""} ${contactLastName || ""}`.trim()
        : null,
      companyName: contactCompanyName || null,
      contactEmail: contactEmail || null,
      contactPhone: contactPhone || null,
      contactEmployeeCount: contactEmployeeCount ?? null, // #1146
      contactLeadSource: contactLeadSource || null, // #1473
    }));
    return { data, total: totalResult.count, limit, offset };
  }


  async getDeal(id: number) {
    const [row] = await db
      .select({
        deal: deals,
        contactFirstName: contacts.firstName,
        contactLastName: contacts.lastName,
        contactCompanyName: contacts.companyName,
        contactEmail: contacts.email,
        contactPhone: contacts.phone,
      })
      .from(deals)
      .leftJoin(contacts, eq(deals.contactId, contacts.id))
      .where(eq(deals.id, id));
    if (!row) return undefined;
    const { deal, contactFirstName, contactLastName, contactCompanyName, contactEmail, contactPhone } = row;
    return {
      ...deal,
      contactName: (contactFirstName || contactLastName)
        ? `${contactFirstName || ""} ${contactLastName || ""}`.trim()
        : null,
      companyName: contactCompanyName || null,
      contactEmail: contactEmail || null,
      contactPhone: contactPhone || null,
    };
  }

  async getDealByGhlOpportunityId(ghlOpportunityId: string) {
    const [deal] = await db.select().from(deals).where(eq(deals.ghlOpportunityId, ghlOpportunityId));
    return deal;
  }


  async getDealsByPipeline(pipeline: string, params?: PaginationParams & { ownerEmail?: string }) {
    const { limit, offset } = normalizePagination(params);
    const ownership = params?.ownerEmail ? or(eq(deals.owner, params.ownerEmail), isNull(deals.owner)) : undefined;
    const whereClause = and(eq(deals.pipeline, pipeline), isNull(deals.archivedAt), ownership);
    const [totalResult] = await db.select({ count: count() }).from(deals).where(whereClause);
    const rows = await db
      .select({
        deal: deals,
        contactFirstName: contacts.firstName,
        contactLastName: contacts.lastName,
        contactCompanyName: contacts.companyName,
        contactEmail: contacts.email,
        contactPhone: contacts.phone,
        contactEmployeeCount: contacts.employeeCount, // #1146
        contactLeadSource: contacts.leadSource, // #1473 — show source batch on pipeline cards
      })
      .from(deals)
      .leftJoin(contacts, eq(deals.contactId, contacts.id))
      .where(whereClause)
      .orderBy(desc(deals.updatedAt), desc(deals.id))
      .limit(limit)
      .offset(offset);
    const data = rows.map(({ deal, contactFirstName, contactLastName, contactCompanyName, contactEmail, contactPhone, contactEmployeeCount, contactLeadSource }) => ({
      ...deal,
      contactName: (contactFirstName || contactLastName)
        ? `${contactFirstName || ""} ${contactLastName || ""}`.trim()
        : null,
      companyName: contactCompanyName || null,
      contactEmail: contactEmail || null,
      contactPhone: contactPhone || null,
      contactEmployeeCount: contactEmployeeCount ?? null, // #1146
      contactLeadSource: contactLeadSource || null, // #1473
    }));
    return { data, total: totalResult.count, limit, offset };
  }


  async getDealsByContact(contactId: number) {
    return await db.select().from(deals).where(and(eq(deals.contactId, contactId), isNull(deals.archivedAt))).orderBy(desc(deals.createdAt));
  }


  async createDeal(insertDeal: InsertDeal, auditCtx?: { userId?: string | null; actorType?: string; actorId?: string | null }) {
    const { auditChange } = await import("../services/audit-change");
    const payload: any = { ...insertDeal };
    const { deriveLinkedDealClass } = await import("../services/commercial-classification-authority");
    payload.recordClass = await deriveLinkedDealClass(payload.contactId, payload.companyId);
    if (payload.contactId && !payload.partnerOrgId) {
      const [contact] = await db.select({ partnerOrgId: contacts.partnerOrgId }).from(contacts).where(eq(contacts.id, payload.contactId));
      if (contact?.partnerOrgId) payload.partnerOrgId = contact.partnerOrgId;
    }
    return await db.transaction(async (tx) => {
      const [deal] = await tx.insert(deals).values(payload).returning();
      await auditChange({
        userId: auditCtx?.userId ?? null,
        actorType: (auditCtx?.actorType as any) ?? "user",
        actorId: auditCtx?.actorId ?? null,
        action: "deal_created",
        entityType: "deal",
        entityId: deal.id,
        before: null,
        after: deal as unknown as Record<string, unknown>,
      }, tx);
      return deal;
    });
  }


  async updateDeal(id: number, updates: UpdateDealRequest, auditCtx?: { userId?: string | null; actorType?: string; actorId?: string | null }) {
    const { auditChange } = await import("../services/audit-change");
    // TypeScript callers cannot provide stage, but runtime callers (HTTP JSON,
    // stale compiled clients, and `as any`) must not regain that authority.
    if (Object.prototype.hasOwnProperty.call(updates as object, "stage")) {
      throw new Error("DEAL_STAGE_AUTHORITY_REQUIRED");
    }
    const [before] = await db.select().from(deals).where(eq(deals.id, id));
    const DEAL_TIMESTAMP_FIELDS: string[] = [
      "nextFollowUp", "expectedGoLiveDate", "goLiveDate", "lastStatementReviewDate",
      "nextStatementReviewDate", "proposalGeneratedAt", "proposalEmailSentAt", "lastNudgeAt",
      "nextNudgeAt", "blueprintGeneratedAt", "closedAt", "boardingSubmittedAt",
      "boardingApprovedAt", "shareLastViewedAt", "archivedAt",
    ];
    const coercedUpdates: Record<string, unknown> = { ...updates };
    for (const field of DEAL_TIMESTAMP_FIELDS) {
      const value = coercedUpdates[field as string];
      if (typeof value === "string") {
        const parsed = new Date(value);
        coercedUpdates[field as string] = isNaN(parsed.getTime()) ? null : parsed;
      }
    }
    return await db.transaction(async (tx) => {
      const [updated] = await tx.update(deals).set({ ...coercedUpdates, updatedAt: new Date() } as typeof deals.$inferInsert).where(eq(deals.id, id)).returning();
      if (updated) {
        await auditChange({
          userId: auditCtx?.userId ?? null,
          actorType: (auditCtx?.actorType as any) ?? "user",
          actorId: auditCtx?.actorId ?? null,
          action: "deal_updated",
          entityType: "deal",
          entityId: id,
          before: before as unknown as Record<string, unknown>,
          after: updated as unknown as Record<string, unknown>,
        }, tx);
      }
      return updated;
    });
  }


  async getDealsStuckInStage(stage: string, maxMinutes: number) {
    const cutoff = new Date(Date.now() - maxMinutes * 60 * 1000);
    return await db.select().from(deals)
      .where(and(
        eq(deals.stage, stage),
        lt(deals.updatedAt!, cutoff),
        isNull(deals.closedAt)
      ));
  }


  async archiveDeal(id: number, auditCtx?: { userId?: string | null; actorType?: string; actorId?: string | null }) {
    const { auditChange } = await import("../services/audit-change");
    const [before] = await db.select().from(deals).where(eq(deals.id, id));
    return await db.transaction(async (tx) => {
      const [updated] = await tx.update(deals).set({ archivedAt: new Date() }).where(eq(deals.id, id)).returning();
      if (updated) {
        await auditChange({ userId: auditCtx?.userId ?? null, actorType: (auditCtx?.actorType as any) ?? "user", actorId: auditCtx?.actorId ?? null,
          action: "deal_archived", entityType: "deal", entityId: id,
          before: before as unknown as Record<string, unknown>, after: updated as unknown as Record<string, unknown> }, tx);
      }
      return updated;
    });
  }


  async restoreDeal(id: number, auditCtx?: { userId?: string | null; actorType?: string; actorId?: string | null }) {
    const { auditChange } = await import("../services/audit-change");
    const [before] = await db.select().from(deals).where(eq(deals.id, id));
    return await db.transaction(async (tx) => {
      const [updated] = await tx.update(deals).set({ archivedAt: null }).where(eq(deals.id, id)).returning();
      if (updated) {
        await auditChange({ userId: auditCtx?.userId ?? null, actorType: (auditCtx?.actorType as any) ?? "user", actorId: auditCtx?.actorId ?? null,
          action: "deal_restored", entityType: "deal", entityId: id,
          before: before as unknown as Record<string, unknown>, after: updated as unknown as Record<string, unknown> }, tx);
      }
      return updated;
    });
  }




  async getDealsByIds(ids: number[]) {
    if (ids.length === 0) return [];
    return await db.select().from(deals).where(inArray(deals.id, ids));
  }

  async getDealsByContactIds(contactIds: number[]) {
    if (contactIds.length === 0) return [];
    const CHUNK = 500;
    const results: typeof deals.$inferSelect[] = [];
    for (let i = 0; i < contactIds.length; i += CHUNK) {
      const chunk = contactIds.slice(i, i + CHUNK);
      const rows = await db.select().from(deals)
        .where(and(inArray(deals.contactId, chunk), isNull(deals.archivedAt)))
        .orderBy(desc(deals.createdAt));
      results.push(...rows);
    }
    return results;
  }

  async getDealsByPartnerOrg(partnerOrgId: number) {
    return await db.select().from(deals).where(and(eq(deals.partnerOrgId, partnerOrgId), isNull(deals.archivedAt))).orderBy(desc(deals.createdAt));
  }

  async getOrphanContactCount(filters: { source?: string; vertical?: string; minScore?: number }): Promise<number> {
    const minScore = filters.minScore ?? 45;
    const conditions: any[] = [
      gte(contacts.leadScore, minScore),
      isNull(contacts.archivedAt),
      sql`NOT EXISTS (SELECT 1 FROM deals WHERE deals.contact_id = ${contacts.id} AND deals.archived_at IS NULL)`,
    ];
    if (filters.source) conditions.push(eq(contacts.leadSource, filters.source));
    if (filters.vertical) conditions.push(eq(contacts.vertical, filters.vertical));
    const [row] = await db.select({ count: sql<number>`COUNT(*)::int` }).from(contacts).where(and(...conditions));
    return row?.count ?? 0;
  }

  async getOrphanContactCandidates(filters: { source?: string; vertical?: string; minScore?: number; limit?: number; afterId?: number }) {
    const minScore = filters.minScore ?? 45;
    // No hard global cap — callers use afterId cursor pagination for large populations.
    // Preview uses a configurable limit; backfill cursor fetches batchSize at a time.
    const limit = filters.limit ?? 1000;

    const conditions: any[] = [
      gte(contacts.leadScore, minScore),
      isNull(contacts.archivedAt),
      sql`NOT EXISTS (SELECT 1 FROM deals WHERE deals.contact_id = ${contacts.id} AND deals.archived_at IS NULL)`,
    ];

    if (filters.source) conditions.push(eq(contacts.leadSource, filters.source));
    if (filters.vertical) conditions.push(eq(contacts.vertical, filters.vertical));
    if (filters.afterId) conditions.push(sql`${contacts.id} > ${filters.afterId}`);

    return await db.select({
      id: contacts.id,
      firstName: contacts.firstName,
      lastName: contacts.lastName,
      email: contacts.email,
      phone: contacts.phone,
      companyName: contacts.companyName,
      leadScore: contacts.leadScore,
      vertical: contacts.vertical,
      leadSource: contacts.leadSource,
      doNotContact: contacts.doNotContact,
      businessId: contacts.businessId,
    }).from(contacts)
      .where(and(...conditions))
      .orderBy(asc(contacts.id))
      .limit(limit);
  }

  async getBackfillProgress(): Promise<Record<string, unknown> | null> {
    const [row] = await db.select().from(systemSettings).where(eq(systemSettings.key, "contacts_deal_backfill_progress"));
    return (row?.value as Record<string, unknown>) ?? null;
  }

  async setBackfillProgress(progress: Record<string, unknown>): Promise<void> {
    const existing = await db.select({ key: systemSettings.key }).from(systemSettings).where(eq(systemSettings.key, "contacts_deal_backfill_progress"));
    if (existing.length > 0) {
      await db.update(systemSettings).set({ value: progress, updatedAt: new Date() }).where(eq(systemSettings.key, "contacts_deal_backfill_progress"));
    } else {
      await db.insert(systemSettings).values({ key: "contacts_deal_backfill_progress", value: progress });
    }
  }

  }
  