// Auto-generated by storage split. Domain: merchants.
  // Methods are mixed into DatabaseStorage in server/storage.ts.
  import { db, pool } from "../db";
import {
  liveChats, liveChatMessages,
  type LiveChat, type InsertLiveChat, type LiveChatMessage, type InsertLiveChatMessage,
  contacts, companies, deals, tickets, tasks, documents, auditLogs, notifications, workflowRuns, workflows, rfis, users,
  chargebacks,
  type Chargeback, type InsertChargeback, type UpdateChargebackRequest,
  messageTemplates, collateralPackets, ghlActivityLog, slaConfigs,
  prospects, prospectLists, enrichmentJobs, campaigns, campaignSteps, outboundMessages, notes,
  emailLogs, callLogs, stageAutomationRules, followUpSequences, sequenceSteps, sequenceEnrollments,
  sunbizEntities, consentAuditLogs, calendarEvents,
  merchantApplications, merchantProfiles, equipmentOrders, agents, agentQuotas, agentMerchants, residualReports, merchantResiduals,
  healthAlerts, dealCompetitors, partners, referrals, commissionTiers, knowledgeBase, reviewRequests, testimonialSubmissions, onboardingSteps, midDailyStats,
  sdrMerchants, sdrMerchantContacts, sdrLeadState, sdrLeadEvents, sdrChannelAttempts, sdrComplianceState,
  sendingIdentities,
  leadDiscoveryJobs, leadDiscoveryResults,
  type SendingIdentity, type InsertSendingIdentity,
  businesses, businessAliases, businessLocations, leadSources, enrichmentRuns,
  type LeadDiscoveryJob, type InsertLeadDiscoveryJob,
  type LeadDiscoveryResult, type InsertLeadDiscoveryResult,
  type Business, type InsertBusiness, type UpdateBusinessRequest,
  type BusinessAlias, type InsertBusinessAlias,
  type BusinessLocation, type InsertBusinessLocation,
  type LeadSource, type InsertLeadSource,
  type EnrichmentRun, type InsertEnrichmentRun,
  type SdrMerchant, type InsertSdrMerchant,
  type SdrMerchantContact, type InsertSdrMerchantContact,
  type SdrLeadState, type InsertSdrLeadState,
  type SdrLeadEvent, type InsertSdrLeadEvent,
  type SdrChannelAttempt, type InsertSdrChannelAttempt,
  type SdrComplianceState, type InsertSdrComplianceState,
  type InsertContact, type UpdateContactRequest,
  type InsertCompany,
  type InsertDeal, type UpdateDealRequest,
  type InsertTicket, type UpdateTicketRequest,
  type InsertTask, type UpdateTaskRequest,
  type InsertDocument,
  type InsertAuditLog,
  type InsertNotification,
  type InsertWorkflow, type UpdateWorkflowRequest,
  type InsertWorkflowRun,
  type InsertRfi, type UpdateRfiRequest,
  type InsertMessageTemplate, type MessageTemplate,
  type InsertCollateralPacket,
  type InsertGhlActivityLog,
  type InsertSlaConfig,
  type Prospect, type InsertProspect, type UpdateProspectRequest,
  type InsertProspectList,
  type InsertEnrichmentJob,
  type InsertCampaign, type UpdateCampaignRequest,
  type InsertCampaignStep,
  type InsertOutboundMessage, type UpdateOutboundMessageRequest,
  type InsertNote,
  type InsertEmailLog, type InsertCallLog, type InsertStageAutomationRule, type InsertFollowUpSequence, type InsertSequenceStep, type InsertSequenceEnrollment,
  type InsertSunbizEntity, type UpdateSunbizEntityRequest, type SunbizEntity,
  type InsertMerchantApplication, type MerchantApplication,
  type InsertMerchantProfile, type MerchantProfile,
  type InsertEquipmentOrder, type EquipmentOrder,
  type InsertAgent, type Agent,
  type InsertAgentMerchant, type AgentMerchant,
  type InsertAgentQuota, type AgentQuota,
  type InsertResidualReport, type ResidualReport,
  type InsertMerchantResidual, type MerchantResidual,
  type InsertHealthAlert, type HealthAlert,
  type InsertDealCompetitor, type DealCompetitor,
  type InsertPartner, type Partner,
  type InsertReferral, type Referral,
  type InsertCommissionTier, type CommissionTier,
  type InsertKnowledgeBaseArticle, type KnowledgeBaseArticle,
  type InsertReviewRequest, type ReviewRequest,
  type InsertTestimonialSubmission, type TestimonialSubmission,
  type InsertOnboardingStep, type OnboardingStep,
  type InsertConsentAuditLog, type ConsentAuditLog,
  type CalendarEvent, type InsertCalendarEvent,
  systemSettings,
  dataDeleteRequests,
  type DataDeleteRequest, type InsertDataDeleteRequest,
  comments, ticketComments, contactCompanies, pipelineStages, notificationPreferences, savedFilters,
  type Comment, type InsertComment,
  type TicketComment, type InsertTicketComment,
  type ContactCompany, type InsertContactCompany,
  type PipelineStage, type InsertPipelineStage,
  type NotificationPreference, type InsertNotificationPreference,
  type SavedFilter, type InsertSavedFilter,
  csvImports, type CsvImport, type InsertCsvImport,
  generatedBlogPosts,
  type GeneratedBlogPost, type InsertGeneratedBlogPost,
  type UpdateSdrLeadState,
  ghlWorkflowMappings, type GhlWorkflowMapping,
  npsResponses, type NpsResponse, type InsertNpsResponse,
  merchantReferrals, type MerchantReferral, type InsertMerchantReferral,
  retentionCampaignConfigs, type RetentionCampaignConfig, type InsertRetentionCampaignConfig,
  type MidDailyStat, type InsertMidDailyStat,
  roleplaySessions, type RoleplaySession, type InsertRoleplaySession,
  roleplayExchanges, type RoleplayExchange, type InsertRoleplayExchange,
  leaderboardSettings, type LeaderboardSettings,
} from "@shared/schema";
import { eq, desc, and, lt, isNull, ne, sql, asc, gte, lte, inArray, or, ilike, count } from "drizzle-orm";
  import { type PaginationParams, type PaginatedResult, normalizePagination } from "./_shared";

  export class MerchantsStorage {
    async getMerchantApplications() {
    return await db.select().from(merchantApplications).orderBy(desc(merchantApplications.createdAt));
  }


  async getMerchantApplication(id: number) {
    const [app] = await db.select().from(merchantApplications).where(eq(merchantApplications.id, id));
    return app;
  }


  async getMerchantApplicationByUser(userId: string) {
    const [app] = await db.select().from(merchantApplications).where(eq(merchantApplications.userId, userId));
    return app;
  }


  async createMerchantApplication(app: InsertMerchantApplication, auditCtx?: { userId?: string | null; actorType?: string; actorId?: string | null }) {
    const { auditChange } = await import("../services/audit-change");
    return await db.transaction(async (tx) => {
      const [created] = await tx.insert(merchantApplications).values(app).returning();
      await auditChange({
        userId: auditCtx?.userId ?? null,
        actorType: (auditCtx?.actorType as any) ?? "user",
        actorId: auditCtx?.actorId ?? null,
        action: "merchant_application_created",
        entityType: "merchant_application",
        entityId: created.id,
        before: null,
        after: created as unknown as Record<string, unknown>,
      }, tx);
      return created;
    });
  }


  async updateMerchantApplication(id: number, updates: Partial<InsertMerchantApplication>, auditCtx?: { userId?: string | null; actorType?: string; actorId?: string | null }) {
    const { auditChange } = await import("../services/audit-change");
    const [before] = await db.select().from(merchantApplications).where(eq(merchantApplications.id, id));
    return await db.transaction(async (tx) => {
      const [updated] = await tx.update(merchantApplications).set({ ...updates, updatedAt: new Date() }).where(eq(merchantApplications.id, id)).returning();
      if (updated) {
        await auditChange({
          userId: auditCtx?.userId ?? null,
          actorType: (auditCtx?.actorType as any) ?? "user",
          actorId: auditCtx?.actorId ?? null,
          action: "merchant_application_updated",
          entityType: "merchant_application",
          entityId: id,
          before: before as unknown as Record<string, unknown>,
          after: updated as unknown as Record<string, unknown>,
        }, tx);
      }
      return updated;
    });
  }


  async getMerchantProfiles() {
    return await db.select().from(merchantProfiles).orderBy(desc(merchantProfiles.createdAt));
  }


  async getMerchantProfile(id: number) {
    const [profile] = await db.select().from(merchantProfiles).where(eq(merchantProfiles.id, id));
    return profile;
  }


  async getMerchantProfileByUser(userId: string) {
    const [profile] = await db.select().from(merchantProfiles).where(eq(merchantProfiles.userId, userId));
    return profile;
  }


  async createMerchantProfile(profile: InsertMerchantProfile) {
    const [created] = await db.insert(merchantProfiles).values(profile).returning();
    return created;
  }


  async updateMerchantProfile(id: number, updates: Partial<InsertMerchantProfile>) {
    const [updated] = await db.update(merchantProfiles).set({ ...updates, updatedAt: new Date() }).where(eq(merchantProfiles.id, id)).returning();
    return updated;
  }


  async getEquipmentOrders(dealId?: number) {
    if (dealId) {
      return await db.select().from(equipmentOrders).where(eq(equipmentOrders.dealId, dealId)).orderBy(desc(equipmentOrders.createdAt));
    }
    return await db.select().from(equipmentOrders).orderBy(desc(equipmentOrders.createdAt));
  }


  async getEquipmentOrder(id: number) {
    const [order] = await db.select().from(equipmentOrders).where(eq(equipmentOrders.id, id));
    return order;
  }


  async getEquipmentOrdersByDeal(dealId: number) {
    return await db.select().from(equipmentOrders).where(eq(equipmentOrders.dealId, dealId)).orderBy(desc(equipmentOrders.createdAt));
  }


  async createEquipmentOrder(order: InsertEquipmentOrder) {
    const [created] = await db.insert(equipmentOrders).values(order).returning();
    return created;
  }


  async updateEquipmentOrder(id: number, updates: Partial<InsertEquipmentOrder>) {
    const [updated] = await db.update(equipmentOrders).set({ ...updates, updatedAt: new Date() }).where(eq(equipmentOrders.id, id)).returning();
    return updated;
  }


  async getAgents() {
    return await db.select().from(agents).orderBy(desc(agents.createdAt));
  }


  async getAgent(id: number) {
    const [agent] = await db.select().from(agents).where(eq(agents.id, id));
    return agent;
  }


  async createAgent(agent: InsertAgent) {
    const [created] = await db.insert(agents).values(agent).returning();
    return created;
  }


  async updateAgent(id: number, updates: Partial<InsertAgent>) {
    const [updated] = await db.update(agents).set({ ...updates, updatedAt: new Date() }).where(eq(agents.id, id)).returning();
    return updated;
  }


  async getAgentMerchants(agentId?: number): Promise<AgentMerchant[]> {
    if (agentId) {
      return await db.select().from(agentMerchants).where(eq(agentMerchants.agentId, agentId)).orderBy(desc(agentMerchants.assignedAt));
    }
    return await db.select().from(agentMerchants).orderBy(desc(agentMerchants.assignedAt));
  }


  async getAgentMerchant(id: number): Promise<AgentMerchant | undefined> {
    const [row] = await db.select().from(agentMerchants).where(eq(agentMerchants.id, id));
    return row;
  }


  async assignMerchantToAgent(data: InsertAgentMerchant): Promise<AgentMerchant> {
    const [created] = await db.insert(agentMerchants).values(data).returning();
    return created;
  }


  async unassignMerchantFromAgent(id: number): Promise<void> {
    await db.delete(agentMerchants).where(eq(agentMerchants.id, id));
  }


  async updateAgentMerchant(id: number, updates: Partial<InsertAgentMerchant>): Promise<AgentMerchant | undefined> {
    const [updated] = await db.update(agentMerchants).set(updates).where(eq(agentMerchants.id, id)).returning();
    return updated;
  }


  async getAgentMerchantsByDeal(dealId: number): Promise<AgentMerchant[]> {
    return await db.select().from(agentMerchants).where(eq(agentMerchants.dealId, dealId));
  }


  async getAgentQuotas(): Promise<AgentQuota[]> {
    return db.select().from(agentQuotas).orderBy(desc(agentQuotas.createdAt));
  }


  async getAgentQuotasByAgent(agentId: number): Promise<AgentQuota[]> {
    return db.select().from(agentQuotas).where(eq(agentQuotas.agentId, agentId)).orderBy(desc(agentQuotas.createdAt));
  }


  async createAgentQuota(quota: InsertAgentQuota): Promise<AgentQuota> {
    const [created] = await db.insert(agentQuotas).values(quota).returning();
    return created;
  }


  async updateAgentQuota(id: number, data: Partial<AgentQuota>): Promise<AgentQuota | undefined> {
    const [updated] = await db.update(agentQuotas).set(data).where(eq(agentQuotas.id, id)).returning();
    return updated;
  }

  }
  