// Auto-generated by storage split. Domain: notifications.
  // Methods are mixed into DatabaseStorage in server/storage.ts.
  import { db, pool } from "../db";
import {
  liveChats, liveChatMessages,
  type LiveChat, type InsertLiveChat, type LiveChatMessage, type InsertLiveChatMessage,
  contacts, companies, deals, tickets, tasks, documents, auditLogs, notifications, workflowRuns, workflows, rfis, users,
  chargebacks,
  type Chargeback, type InsertChargeback, type UpdateChargebackRequest,
  messageTemplates, collateralPackets, ghlActivityLog, slaConfigs,
  prospects, prospectLists, enrichmentJobs, campaigns, campaignSteps, outboundMessages, notes,
  emailLogs, callLogs, stageAutomationRules, followUpSequences, sequenceSteps, sequenceEnrollments,
  sunbizEntities, consentAuditLogs, calendarEvents,
  merchantApplications, merchantProfiles, equipmentOrders, agents, agentQuotas, agentMerchants, residualReports, merchantResiduals,
  healthAlerts, dealCompetitors, partners, referrals, commissionTiers, knowledgeBase, reviewRequests, testimonialSubmissions, onboardingSteps, midDailyStats,
  sdrMerchants, sdrMerchantContacts, sdrLeadState, sdrLeadEvents, sdrChannelAttempts, sdrComplianceState,
  sendingIdentities,
  leadDiscoveryJobs, leadDiscoveryResults,
  type SendingIdentity, type InsertSendingIdentity,
  businesses, businessAliases, businessLocations, leadSources, enrichmentRuns,
  type LeadDiscoveryJob, type InsertLeadDiscoveryJob,
  type LeadDiscoveryResult, type InsertLeadDiscoveryResult,
  type Business, type InsertBusiness, type UpdateBusinessRequest,
  type BusinessAlias, type InsertBusinessAlias,
  type BusinessLocation, type InsertBusinessLocation,
  type LeadSource, type InsertLeadSource,
  type EnrichmentRun, type InsertEnrichmentRun,
  type SdrMerchant, type InsertSdrMerchant,
  type SdrMerchantContact, type InsertSdrMerchantContact,
  type SdrLeadState, type InsertSdrLeadState,
  type SdrLeadEvent, type InsertSdrLeadEvent,
  type SdrChannelAttempt, type InsertSdrChannelAttempt,
  type SdrComplianceState, type InsertSdrComplianceState,
  type InsertContact, type UpdateContactRequest,
  type InsertCompany,
  type InsertDeal, type UpdateDealRequest,
  type InsertTicket, type UpdateTicketRequest,
  type InsertTask, type UpdateTaskRequest,
  type InsertDocument,
  type InsertAuditLog,
  type InsertNotification,
  type InsertWorkflow, type UpdateWorkflowRequest,
  type InsertWorkflowRun,
  type InsertRfi, type UpdateRfiRequest,
  type InsertMessageTemplate, type MessageTemplate,
  type InsertCollateralPacket,
  type InsertGhlActivityLog,
  type InsertSlaConfig,
  type Prospect, type InsertProspect, type UpdateProspectRequest,
  type InsertProspectList,
  type InsertEnrichmentJob,
  type InsertCampaign, type UpdateCampaignRequest,
  type InsertCampaignStep,
  type InsertOutboundMessage, type UpdateOutboundMessageRequest,
  type InsertNote,
  type InsertEmailLog, type InsertCallLog, type InsertStageAutomationRule, type InsertFollowUpSequence, type InsertSequenceStep, type InsertSequenceEnrollment,
  type InsertSunbizEntity, type UpdateSunbizEntityRequest, type SunbizEntity,
  type InsertMerchantApplication, type MerchantApplication,
  type InsertMerchantProfile, type MerchantProfile,
  type InsertEquipmentOrder, type EquipmentOrder,
  type InsertAgent, type Agent,
  type InsertAgentMerchant, type AgentMerchant,
  type InsertAgentQuota, type AgentQuota,
  type InsertResidualReport, type ResidualReport,
  type InsertMerchantResidual, type MerchantResidual,
  type InsertHealthAlert, type HealthAlert,
  type InsertDealCompetitor, type DealCompetitor,
  type InsertPartner, type Partner,
  type InsertReferral, type Referral,
  type InsertCommissionTier, type CommissionTier,
  type InsertKnowledgeBaseArticle, type KnowledgeBaseArticle,
  type InsertReviewRequest, type ReviewRequest,
  type InsertTestimonialSubmission, type TestimonialSubmission,
  type InsertOnboardingStep, type OnboardingStep,
  type InsertConsentAuditLog, type ConsentAuditLog,
  type CalendarEvent, type InsertCalendarEvent,
  systemSettings,
  dataDeleteRequests,
  type DataDeleteRequest, type InsertDataDeleteRequest,
  comments, ticketComments, contactCompanies, pipelineStages, notificationPreferences, savedFilters,
  type Comment, type InsertComment,
  type TicketComment, type InsertTicketComment,
  type ContactCompany, type InsertContactCompany,
  type PipelineStage, type InsertPipelineStage,
  type NotificationPreference, type InsertNotificationPreference,
  type SavedFilter, type InsertSavedFilter,
  csvImports, type CsvImport, type InsertCsvImport,
  generatedBlogPosts,
  type GeneratedBlogPost, type InsertGeneratedBlogPost,
  type UpdateSdrLeadState,
  ghlWorkflowMappings, type GhlWorkflowMapping,
  npsResponses, type NpsResponse, type InsertNpsResponse,
  merchantReferrals, type MerchantReferral, type InsertMerchantReferral,
  retentionCampaignConfigs, type RetentionCampaignConfig, type InsertRetentionCampaignConfig,
  type MidDailyStat, type InsertMidDailyStat,
  roleplaySessions, type RoleplaySession, type InsertRoleplaySession,
  roleplayExchanges, type RoleplayExchange, type InsertRoleplayExchange,
  leaderboardSettings, type LeaderboardSettings,
} from "@shared/schema";
import { eq, desc, and, lt, isNull, ne, sql, asc, gte, lte, inArray, or, ilike, count } from "drizzle-orm";
  import { type PaginationParams, type PaginatedResult, normalizePagination } from "./_shared";

  export class NotificationsStorage {
    async getNotifications() {
    return await db.select().from(notifications).orderBy(desc(notifications.createdAt));
  }


  async getNotificationsPaginated(params: { limit: number; offset: number; category?: string; userId?: string }) {
    const { limit, offset, category, userId } = params;
    const categoryEventTypes: Record<string, string[]> = {
      leads: ["contact_created", "hot_lead", "sequence_completed"],
      deals: ["deal_created", "deal_stage_changed", "deal_closed_won"],
      sla: ["sla_breach", "task_due_soon", "ticket_created", "ticket_updated"],
      system: ["daily_digest", "weekly_digest", "mention", "comment_reply", "task_assigned"],
    };

    // Scope: show notifications addressed to this user OR system-wide (recipientId IS NULL)
    const userScope = userId
      ? or(eq(notifications.recipientId, userId), isNull(notifications.recipientId))
      : undefined;

    const categoryCondition =
      category && category !== "all" && categoryEventTypes[category]
        ? inArray(
            sql`(${notifications.metadata}->>'eventType')::text`,
            categoryEventTypes[category]
          )
        : undefined;

    // Push preference-based event-type filtering into SQL: exclude notifications whose
    // metadata.eventType matches a disabled preference for this user. NOT EXISTS keeps
    // notifications without an eventType or without a matching preference row.
    const preferenceCondition = userId
      ? sql`NOT EXISTS (
          SELECT 1 FROM ${notificationPreferences}
          WHERE ${notificationPreferences.userId} = ${userId}
            AND ${notificationPreferences.enabled} = false
            AND ${notificationPreferences.eventType} = (${notifications.metadata}->>'eventType')
        )`
      : undefined;

    const conditions = [userScope, categoryCondition, preferenceCondition].filter(
      (c): c is NonNullable<typeof c> => c !== undefined
    );
    const where = conditions.length > 0 ? and(...conditions) : undefined;

    const [data, totalRows] = await Promise.all([
      where
        ? db.select().from(notifications).where(where).orderBy(desc(notifications.createdAt)).limit(limit).offset(offset)
        : db.select().from(notifications).orderBy(desc(notifications.createdAt)).limit(limit).offset(offset),
      where
        ? db.select({ count: count() }).from(notifications).where(where)
        : db.select({ count: count() }).from(notifications),
    ]);

    return { data, total: totalRows[0]?.count ?? 0 };
  }


  async getNotificationsUnreadCount(userId?: string): Promise<number> {
    const unreadCond = eq(notifications.read, false);
    const userScope = userId
      ? or(eq(notifications.recipientId, userId), isNull(notifications.recipientId))
      : undefined;
    const where = userScope ? and(userScope, unreadCond) : unreadCond;
    const [row] = await db.select({ count: count() }).from(notifications).where(where);
    return row?.count ?? 0;
  }


  async createNotification(insertNotification: InsertNotification) {
    const [notification] = await db.insert(notifications).values(insertNotification).returning();
    return notification;
  }


  async markNotificationRead(id: number, userId?: string) {
    // If userId is provided, only mark read if the notification belongs to this user
    // (recipientId matches OR it is a system-wide notification with recipientId IS NULL)
    const condition = userId
      ? and(eq(notifications.id, id), or(eq(notifications.recipientId, userId), isNull(notifications.recipientId)))
      : eq(notifications.id, id);
    await db.update(notifications).set({ read: true }).where(condition);
  }


  async deleteNotification(id: number, userId?: string): Promise<boolean> {
    // If userId provided, verify ownership (recipientId matches user OR is NULL for system notifications)
    if (userId) {
      const [notif] = await db.select({ id: notifications.id, recipientId: notifications.recipientId })
        .from(notifications)
        .where(eq(notifications.id, id));
      if (!notif) return false;
      if (notif.recipientId !== null && notif.recipientId !== userId) return false;
    }
    await db.delete(notifications).where(eq(notifications.id, id));
    return true;
  }


  async clearOldReadNotifications(userId?: string): Promise<number> {
    const cutoff = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
    const userScope = userId
      ? or(eq(notifications.recipientId, userId), isNull(notifications.recipientId))
      : undefined;
    const where = and(
      eq(notifications.read, true),
      lt(notifications.createdAt, cutoff),
      ...(userScope ? [userScope] : [])
    );
    const result = await db.delete(notifications).where(where).returning({ id: notifications.id });
    return result.length;
  }


  async getNotificationPreferences(userId: string): Promise<NotificationPreference[]> {
    return db.select().from(notificationPreferences).where(eq(notificationPreferences.userId, userId));
  }


  async upsertNotificationPreference(pref: InsertNotificationPreference): Promise<NotificationPreference> {
    const existing = await db.select().from(notificationPreferences).where(and(eq(notificationPreferences.userId, pref.userId), eq(notificationPreferences.eventType, pref.eventType)));
    if (existing.length > 0) {
      const updates: Partial<Pick<InsertNotificationPreference, "enabled" | "emailEnabled" | "digestDaily" | "digestWeekly">> = {};
      if (typeof pref.enabled === "boolean") updates.enabled = pref.enabled;
      if (typeof pref.emailEnabled === "boolean") updates.emailEnabled = pref.emailEnabled;
      if (typeof pref.digestDaily === "boolean") updates.digestDaily = pref.digestDaily;
      if (typeof pref.digestWeekly === "boolean") updates.digestWeekly = pref.digestWeekly;
      const [updated] = await db.update(notificationPreferences).set(updates).where(eq(notificationPreferences.id, existing[0].id)).returning();
      return updated;
    }
    const [created] = await db.insert(notificationPreferences).values(pref).returning();
    return created;
  }


  async getUsersByRole(roles: string[]): Promise<{ id: string; email: string | null; role: string | null; firstName: string | null; lastName: string | null }[]> {
    return db.select({ id: users.id, email: users.email, role: users.role, firstName: users.firstName, lastName: users.lastName }).from(users).where(inArray(users.role, roles));
  }


  async getAllNotificationPreferencesByEvent(eventType: string): Promise<NotificationPreference[]> {
    return db.select().from(notificationPreferences).where(eq(notificationPreferences.eventType, eventType));
  }


  async markAllNotificationsRead(userId?: string): Promise<void> {
    if (userId) {
      // Mark notifications scoped to this user: those addressed to them OR system-wide (recipientId IS NULL)
      await db.update(notifications).set({ read: true }).where(
        and(
          or(eq(notifications.recipientId, userId), isNull(notifications.recipientId)),
          eq(notifications.read, false)
        )
      );
    } else {
      await db.update(notifications).set({ read: true }).where(eq(notifications.read, false));
    }
  }


  async clearAllNotifications(userId?: string): Promise<void> {
    if (userId) {
      // Delete this user's personal notifications
      await db.delete(notifications).where(eq(notifications.recipientId, userId));
      // System-wide notifications (recipientId IS NULL) can't be deleted per-user;
      // mark them read so they no longer appear in the user's unread count/list.
      await db.update(notifications).set({ read: true }).where(
        and(isNull(notifications.recipientId), eq(notifications.read, false))
      );
    } else {
      await db.delete(notifications);
    }
  }

  }
  