// Auto-generated by storage split. Domain: partnerOrgs.
  // Methods are mixed into DatabaseStorage in server/storage.ts.
  import { db, pool } from "../db";
import {
  liveChats, liveChatMessages,
  type LiveChat, type InsertLiveChat, type LiveChatMessage, type InsertLiveChatMessage,
  contacts, companies, deals, tickets, tasks, documents, auditLogs, notifications, workflowRuns, workflows, rfis, users,
  chargebacks,
  type Chargeback, type InsertChargeback, type UpdateChargebackRequest,
  messageTemplates, collateralPackets, ghlActivityLog, slaConfigs,
  prospects, prospectLists, enrichmentJobs, campaigns, campaignSteps, outboundMessages, notes,
  emailLogs, callLogs, stageAutomationRules, followUpSequences, sequenceSteps, sequenceEnrollments,
  sunbizEntities, consentAuditLogs, calendarEvents,
  merchantApplications, merchantProfiles, equipmentOrders, agents, agentQuotas, agentMerchants, residualReports, merchantResiduals,
  healthAlerts, dealCompetitors, partners, referrals, commissionTiers, knowledgeBase, reviewRequests, testimonialSubmissions, onboardingSteps, midDailyStats,
  sdrMerchants, sdrMerchantContacts, sdrLeadState, sdrLeadEvents, sdrChannelAttempts, sdrComplianceState,
  sendingIdentities,
  leadDiscoveryJobs, leadDiscoveryResults,
  type SendingIdentity, type InsertSendingIdentity,
  businesses, businessAliases, businessLocations, leadSources, enrichmentRuns,
  type LeadDiscoveryJob, type InsertLeadDiscoveryJob,
  type LeadDiscoveryResult, type InsertLeadDiscoveryResult,
  type Business, type InsertBusiness, type UpdateBusinessRequest,
  type BusinessAlias, type InsertBusinessAlias,
  type BusinessLocation, type InsertBusinessLocation,
  type LeadSource, type InsertLeadSource,
  type EnrichmentRun, type InsertEnrichmentRun,
  type SdrMerchant, type InsertSdrMerchant,
  type SdrMerchantContact, type InsertSdrMerchantContact,
  type SdrLeadState, type InsertSdrLeadState,
  type SdrLeadEvent, type InsertSdrLeadEvent,
  type SdrChannelAttempt, type InsertSdrChannelAttempt,
  type SdrComplianceState, type InsertSdrComplianceState,
  type InsertContact, type UpdateContactRequest,
  type InsertCompany,
  type InsertDeal, type UpdateDealRequest,
  type InsertTicket, type UpdateTicketRequest,
  type InsertTask, type UpdateTaskRequest,
  type InsertDocument,
  type InsertAuditLog,
  type InsertNotification,
  type InsertWorkflow, type UpdateWorkflowRequest,
  type InsertWorkflowRun,
  type InsertRfi, type UpdateRfiRequest,
  type InsertMessageTemplate, type MessageTemplate,
  type InsertCollateralPacket,
  type InsertGhlActivityLog,
  type InsertSlaConfig,
  type Prospect, type InsertProspect, type UpdateProspectRequest,
  type InsertProspectList,
  type InsertEnrichmentJob,
  type InsertCampaign, type UpdateCampaignRequest,
  type InsertCampaignStep,
  type InsertOutboundMessage, type UpdateOutboundMessageRequest,
  type InsertNote,
  type InsertEmailLog, type InsertCallLog, type InsertStageAutomationRule, type InsertFollowUpSequence, type InsertSequenceStep, type InsertSequenceEnrollment,
  type InsertSunbizEntity, type UpdateSunbizEntityRequest, type SunbizEntity,
  type InsertMerchantApplication, type MerchantApplication,
  type InsertMerchantProfile, type MerchantProfile,
  type InsertEquipmentOrder, type EquipmentOrder,
  type InsertAgent, type Agent,
  type InsertAgentMerchant, type AgentMerchant,
  type InsertAgentQuota, type AgentQuota,
  type InsertResidualReport, type ResidualReport,
  type InsertMerchantResidual, type MerchantResidual,
  type InsertHealthAlert, type HealthAlert,
  type InsertDealCompetitor, type DealCompetitor,
  type InsertPartner, type Partner,
  type InsertReferral, type Referral,
  type InsertCommissionTier, type CommissionTier,
  type InsertKnowledgeBaseArticle, type KnowledgeBaseArticle,
  type InsertReviewRequest, type ReviewRequest,
  type InsertTestimonialSubmission, type TestimonialSubmission,
  type InsertOnboardingStep, type OnboardingStep,
  type InsertConsentAuditLog, type ConsentAuditLog,
  type CalendarEvent, type InsertCalendarEvent,
  systemSettings,
  dataDeleteRequests,
  type DataDeleteRequest, type InsertDataDeleteRequest,
  comments, ticketComments, contactCompanies, pipelineStages, notificationPreferences, savedFilters,
  type Comment, type InsertComment,
  type TicketComment, type InsertTicketComment,
  type ContactCompany, type InsertContactCompany,
  type PipelineStage, type InsertPipelineStage,
  type NotificationPreference, type InsertNotificationPreference,
  type SavedFilter, type InsertSavedFilter,
  csvImports, type CsvImport, type InsertCsvImport,
  generatedBlogPosts,
  type GeneratedBlogPost, type InsertGeneratedBlogPost,
  type UpdateSdrLeadState,
  ghlWorkflowMappings, type GhlWorkflowMapping,
  npsResponses, type NpsResponse, type InsertNpsResponse,
  merchantReferrals, type MerchantReferral, type InsertMerchantReferral,
  retentionCampaignConfigs, type RetentionCampaignConfig, type InsertRetentionCampaignConfig,
  type MidDailyStat, type InsertMidDailyStat,
  roleplaySessions, type RoleplaySession, type InsertRoleplaySession,
  roleplayExchanges, type RoleplayExchange, type InsertRoleplayExchange,
  leaderboardSettings, type LeaderboardSettings,
} from "@shared/schema";
import { eq, desc, and, lt, isNull, ne, sql, asc, gte, lte, inArray, or, ilike, count } from "drizzle-orm";
  import { type PaginationParams, type PaginatedResult, normalizePagination } from "./_shared";

  export class PartnerOrgsStorage {
    async getPartnerOrgs() {
    const { partnerOrganizations } = await import("@shared/schema");
    return await db.select().from(partnerOrganizations).orderBy(desc(partnerOrganizations.createdAt));
  }


  async getPartnerOrg(id: number) {
    const { partnerOrganizations } = await import("@shared/schema");
    const [org] = await db.select().from(partnerOrganizations).where(eq(partnerOrganizations.id, id));
    return org || null;
  }


  async getPartnerOrgBySlug(slug: string) {
    const { partnerOrganizations } = await import("@shared/schema");
    const [org] = await db.select().from(partnerOrganizations).where(eq(partnerOrganizations.slug, slug));
    return org || null;
  }


  async createPartnerOrg(data: import("@shared/schema").InsertPartnerOrganization) {
    const { partnerOrganizations } = await import("@shared/schema");
    const [org] = await db.insert(partnerOrganizations).values(data).returning();
    return org;
  }


  async updatePartnerOrg(id: number, updates: Partial<import("@shared/schema").InsertPartnerOrganization>) {
    const { partnerOrganizations } = await import("@shared/schema");
    const [org] = await db.update(partnerOrganizations)
      .set({ ...updates, updatedAt: new Date() })
      .where(eq(partnerOrganizations.id, id))
      .returning();
    return org || null;
  }


  async deletePartnerOrg(id: number) {
    const { partnerOrganizations } = await import("@shared/schema");
    await db.delete(partnerOrganizations).where(eq(partnerOrganizations.id, id));
  }

  // ── Partner Org Users ─────────────────────────────────────────────────────

  async getPartnerOrgUsers(orgId: number) {
    const { partnerOrgUsers } = await import("@shared/schema");
    return await db.select().from(partnerOrgUsers).where(eq(partnerOrgUsers.partnerOrgId, orgId)).orderBy(partnerOrgUsers.createdAt);
  }


  async getPartnerOrgUser(id: number) {
    const { partnerOrgUsers } = await import("@shared/schema");
    const [user] = await db.select().from(partnerOrgUsers).where(eq(partnerOrgUsers.id, id));
    return user || null;
  }


  async getPartnerOrgUserByEmail(email: string) {
    const { partnerOrgUsers } = await import("@shared/schema");
    const [user] = await db.select().from(partnerOrgUsers).where(eq(partnerOrgUsers.email, email));
    return user || null;
  }


  async getPartnerOrgUserByEmailAndOrg(email: string, orgId: number) {
    const { partnerOrgUsers } = await import("@shared/schema");
    const [user] = await db.select().from(partnerOrgUsers).where(
      and(eq(partnerOrgUsers.email, email), eq(partnerOrgUsers.partnerOrgId, orgId))
    );
    return user || null;
  }


  async createPartnerOrgUser(data: import("@shared/schema").InsertPartnerOrgUser) {
    const { partnerOrgUsers } = await import("@shared/schema");
    const [user] = await db.insert(partnerOrgUsers).values(data).returning();
    return user;
  }


  async updatePartnerOrgUser(id: number, updates: Partial<import("@shared/schema").InsertPartnerOrgUser>) {
    const { partnerOrgUsers } = await import("@shared/schema");
    const [user] = await db.update(partnerOrgUsers).set(updates).where(eq(partnerOrgUsers.id, id)).returning();
    return user || null;
  }

  // ── Deals / Contacts by Partner Org ──────────────────────────────────────

  // ── Co-Branded Proposals ──────────────────────────────────────────────────

  async getCoBrandedProposals(partnerOrgId: number) {
    const { coBrandedProposals } = await import("@shared/schema");
    return await db.select().from(coBrandedProposals)
      .where(eq(coBrandedProposals.partnerOrgId, partnerOrgId))
      .orderBy(desc(coBrandedProposals.createdAt));
  }

  async getAllCoBrandedProposals() {
    const { coBrandedProposals } = await import("@shared/schema");
    return await db.select().from(coBrandedProposals)
      .orderBy(desc(coBrandedProposals.createdAt));
  }

  async getCoBrandedProposal(id: number) {
    const { coBrandedProposals } = await import("@shared/schema");
    const [p] = await db.select().from(coBrandedProposals).where(eq(coBrandedProposals.id, id));
    return p || null;
  }

  async getCoBrandedProposalByToken(token: string) {
    const { coBrandedProposals } = await import("@shared/schema");
    const [p] = await db.select().from(coBrandedProposals).where(eq(coBrandedProposals.token, token));
    return p || null;
  }

  async createCoBrandedProposal(data: import("@shared/schema").InsertCoBrandedProposal) {
    const { coBrandedProposals } = await import("@shared/schema");
    const [p] = await db.insert(coBrandedProposals).values(data).returning();
    return p;
  }

  async updateCoBrandedProposal(id: number, updates: Partial<import("@shared/schema").InsertCoBrandedProposal>) {
    const { coBrandedProposals } = await import("@shared/schema");
    const [p] = await db.update(coBrandedProposals)
      .set({ ...updates, updatedAt: new Date() })
      .where(eq(coBrandedProposals.id, id))
      .returning();
    return p || null;
  }

  async deleteCoBrandedProposal(id: number) {
    const { coBrandedProposals } = await import("@shared/schema");
    await db.delete(coBrandedProposals).where(eq(coBrandedProposals.id, id));
  }
  }
  