// Auto-generated by storage split. Domain: partners.
  // Methods are mixed into DatabaseStorage in server/storage.ts.
  import { db, pool } from "../db";
import {
  liveChats, liveChatMessages,
  type LiveChat, type InsertLiveChat, type LiveChatMessage, type InsertLiveChatMessage,
  contacts, companies, deals, tickets, tasks, documents, auditLogs, notifications, workflowRuns, workflows, rfis, users,
  chargebacks,
  type Chargeback, type InsertChargeback, type UpdateChargebackRequest,
  messageTemplates, collateralPackets, ghlActivityLog, slaConfigs,
  prospects, prospectLists, enrichmentJobs, campaigns, campaignSteps, outboundMessages, notes,
  emailLogs, callLogs, stageAutomationRules, followUpSequences, sequenceSteps, sequenceEnrollments,
  sunbizEntities, consentAuditLogs, calendarEvents,
  merchantApplications, merchantProfiles, equipmentOrders, agents, agentQuotas, agentMerchants, residualReports, merchantResiduals,
  healthAlerts, dealCompetitors, partners, referrals, commissionTiers, knowledgeBase, reviewRequests, testimonialSubmissions, onboardingSteps, midDailyStats,
  sdrMerchants, sdrMerchantContacts, sdrLeadState, sdrLeadEvents, sdrChannelAttempts, sdrComplianceState,
  sendingIdentities,
  leadDiscoveryJobs, leadDiscoveryResults,
  type SendingIdentity, type InsertSendingIdentity,
  businesses, businessAliases, businessLocations, leadSources, enrichmentRuns,
  type LeadDiscoveryJob, type InsertLeadDiscoveryJob,
  type LeadDiscoveryResult, type InsertLeadDiscoveryResult,
  type Business, type InsertBusiness, type UpdateBusinessRequest,
  type BusinessAlias, type InsertBusinessAlias,
  type BusinessLocation, type InsertBusinessLocation,
  type LeadSource, type InsertLeadSource,
  type EnrichmentRun, type InsertEnrichmentRun,
  type SdrMerchant, type InsertSdrMerchant,
  type SdrMerchantContact, type InsertSdrMerchantContact,
  type SdrLeadState, type InsertSdrLeadState,
  type SdrLeadEvent, type InsertSdrLeadEvent,
  type SdrChannelAttempt, type InsertSdrChannelAttempt,
  type SdrComplianceState, type InsertSdrComplianceState,
  type InsertContact, type UpdateContactRequest,
  type InsertCompany,
  type InsertDeal, type UpdateDealRequest,
  type InsertTicket, type UpdateTicketRequest,
  type InsertTask, type UpdateTaskRequest,
  type InsertDocument,
  type InsertAuditLog,
  type InsertNotification,
  type InsertWorkflow, type UpdateWorkflowRequest,
  type InsertWorkflowRun,
  type InsertRfi, type UpdateRfiRequest,
  type InsertMessageTemplate, type MessageTemplate,
  type InsertCollateralPacket,
  type InsertGhlActivityLog,
  type InsertSlaConfig,
  type Prospect, type InsertProspect, type UpdateProspectRequest,
  type InsertProspectList,
  type InsertEnrichmentJob,
  type InsertCampaign, type UpdateCampaignRequest,
  type InsertCampaignStep,
  type InsertOutboundMessage, type UpdateOutboundMessageRequest,
  type InsertNote,
  type InsertEmailLog, type InsertCallLog, type InsertStageAutomationRule, type InsertFollowUpSequence, type InsertSequenceStep, type InsertSequenceEnrollment,
  type InsertSunbizEntity, type UpdateSunbizEntityRequest, type SunbizEntity,
  type InsertMerchantApplication, type MerchantApplication,
  type InsertMerchantProfile, type MerchantProfile,
  type InsertEquipmentOrder, type EquipmentOrder,
  type InsertAgent, type Agent,
  type InsertAgentMerchant, type AgentMerchant,
  type InsertAgentQuota, type AgentQuota,
  type InsertResidualReport, type ResidualReport,
  type InsertMerchantResidual, type MerchantResidual,
  type InsertHealthAlert, type HealthAlert,
  type InsertDealCompetitor, type DealCompetitor,
  type InsertPartner, type Partner,
  type InsertReferral, type Referral,
  type InsertCommissionTier, type CommissionTier,
  type InsertKnowledgeBaseArticle, type KnowledgeBaseArticle,
  type InsertReviewRequest, type ReviewRequest,
  type InsertTestimonialSubmission, type TestimonialSubmission,
  type InsertOnboardingStep, type OnboardingStep,
  type InsertConsentAuditLog, type ConsentAuditLog,
  type CalendarEvent, type InsertCalendarEvent,
  systemSettings,
  dataDeleteRequests,
  type DataDeleteRequest, type InsertDataDeleteRequest,
  comments, ticketComments, contactCompanies, pipelineStages, notificationPreferences, savedFilters,
  type Comment, type InsertComment,
  type TicketComment, type InsertTicketComment,
  type ContactCompany, type InsertContactCompany,
  type PipelineStage, type InsertPipelineStage,
  type NotificationPreference, type InsertNotificationPreference,
  type SavedFilter, type InsertSavedFilter,
  csvImports, type CsvImport, type InsertCsvImport,
  generatedBlogPosts,
  type GeneratedBlogPost, type InsertGeneratedBlogPost,
  type UpdateSdrLeadState,
  ghlWorkflowMappings, type GhlWorkflowMapping,
  npsResponses, type NpsResponse, type InsertNpsResponse,
  merchantReferrals, type MerchantReferral, type InsertMerchantReferral,
  retentionCampaignConfigs, type RetentionCampaignConfig, type InsertRetentionCampaignConfig,
  type MidDailyStat, type InsertMidDailyStat,
  roleplaySessions, type RoleplaySession, type InsertRoleplaySession,
  roleplayExchanges, type RoleplayExchange, type InsertRoleplayExchange,
  leaderboardSettings, type LeaderboardSettings,
} from "@shared/schema";
import { eq, desc, and, lt, isNull, ne, sql, asc, gte, lte, inArray, or, ilike, count } from "drizzle-orm";
  import { type PaginationParams, type PaginatedResult, normalizePagination } from "./_shared";

  export class PartnersStorage {
    async getPartners() {
    return await db.select().from(partners).orderBy(desc(partners.createdAt));
  }


  async getPartner(id: number) {
    const [partner] = await db.select().from(partners).where(eq(partners.id, id));
    return partner;
  }


  async getPartnerByCode(code: string) {
    const [partner] = await db.select().from(partners).where(eq(partners.affiliateCode, code.toLowerCase()));
    return partner;
  }


  async getPartnerByEmail(email: string) {
    const [partner] = await db.select().from(partners).where(eq(partners.email, email.toLowerCase()));
    return partner;
  }


  async createPartner(partner: InsertPartner) {
    const [created] = await db.insert(partners).values(partner).returning();
    return created;
  }


  async updatePartner(id: number, updates: Partial<InsertPartner>) {
    const [updated] = await db.update(partners).set({ ...updates, updatedAt: new Date() }).where(eq(partners.id, id)).returning();
    return updated;
  }


  async incrementPartnerClicks(code: string) {
    await db.update(partners)
      .set({ totalClicks: sql`${partners.totalClicks} + 1`, updatedAt: new Date() })
      .where(eq(partners.affiliateCode, code.toLowerCase()));
  }


  async setPartnerResetToken(id: number, tokenHash: string, expiresAt: Date) {
    await db.update(partners)
      .set({ passwordResetToken: tokenHash, passwordResetExpiresAt: expiresAt, updatedAt: new Date() })
      .where(eq(partners.id, id));
  }


  async getPartnerByResetToken(tokenHash: string) {
    const [partner] = await db.select().from(partners)
      .where(and(eq(partners.passwordResetToken, tokenHash), gte(partners.passwordResetExpiresAt, new Date())));
    return partner;
  }


  async updatePartnerPassword(id: number, passwordHash: string) {
    await db.update(partners)
      .set({ passwordHash, passwordResetToken: null, passwordResetExpiresAt: null, updatedAt: new Date() })
      .where(eq(partners.id, id));
  }


  async setPartnerInviteToken(id: number, tokenHash: string, expiresAt: Date) {
    await db.update(partners)
      .set({ inviteToken: tokenHash, inviteTokenExpiresAt: expiresAt, updatedAt: new Date() })
      .where(eq(partners.id, id));
  }


  async getPartnerByInviteToken(tokenHash: string) {
    const [partner] = await db.select().from(partners)
      .where(and(eq(partners.inviteToken, tokenHash), gte(partners.inviteTokenExpiresAt, new Date())));
    return partner;
  }


  async clearPartnerInviteToken(id: number) {
    await db.update(partners)
      .set({ inviteToken: null, inviteTokenExpiresAt: null, updatedAt: new Date() })
      .where(eq(partners.id, id));
  }


  async getReferrals(partnerId?: number) {
    if (partnerId) {
      return await db.select().from(referrals).where(eq(referrals.partnerId, partnerId)).orderBy(desc(referrals.createdAt));
    }
    return await db.select().from(referrals).orderBy(desc(referrals.createdAt));
  }


  async getReferral(id: number) {
    const [referral] = await db.select().from(referrals).where(eq(referrals.id, id));
    return referral;
  }


  async getReferralsByPartner(partnerId: number) {
    return await db.select().from(referrals).where(eq(referrals.partnerId, partnerId)).orderBy(desc(referrals.createdAt));
  }


  async createReferral(referral: InsertReferral) {
    const [created] = await db.insert(referrals).values(referral).returning();
    return created;
  }


  async updateReferral(id: number, updates: Partial<InsertReferral>) {
    const [updated] = await db.update(referrals).set({ ...updates, updatedAt: new Date() }).where(eq(referrals.id, id)).returning();
    return updated;
  }


  async getCommissionTiers() {
    return await db.select().from(commissionTiers).orderBy(asc(commissionTiers.minReferrals));
  }


  async createCommissionTier(tier: InsertCommissionTier, auditCtx?: { userId?: string | null; actorType?: string; actorId?: string | null }) {
    const { auditChange } = await import("../services/audit-change");
    return await db.transaction(async (tx) => {
      const [created] = await tx.insert(commissionTiers).values(tier).returning();
      await auditChange({
        userId: auditCtx?.userId ?? null,
        actorType: (auditCtx?.actorType as any) ?? "user",
        actorId: auditCtx?.actorId ?? null,
        action: "commission_tier_created",
        entityType: "commission_tier",
        entityId: created.id,
        before: null,
        after: created as unknown as Record<string, unknown>,
      }, tx);
      return created;
    });
  }


  async updateCommissionTier(id: number, updates: Partial<InsertCommissionTier>, auditCtx?: { userId?: string | null; actorType?: string; actorId?: string | null }) {
    const { auditChange } = await import("../services/audit-change");
    const [before] = await db.select().from(commissionTiers).where(eq(commissionTiers.id, id));
    return await db.transaction(async (tx) => {
      const [updated] = await tx.update(commissionTiers).set(updates).where(eq(commissionTiers.id, id)).returning();
      if (updated) {
        await auditChange({
          userId: auditCtx?.userId ?? null,
          actorType: (auditCtx?.actorType as any) ?? "user",
          actorId: auditCtx?.actorId ?? null,
          action: "commission_tier_updated",
          entityType: "commission_tier",
          entityId: id,
          before: before as unknown as Record<string, unknown>,
          after: updated as unknown as Record<string, unknown>,
        }, tx);
      }
      return updated;
    });
  }


  async deleteCommissionTier(id: number, auditCtx?: { userId?: string | null; actorType?: string; actorId?: string | null }) {
    const { auditChange } = await import("../services/audit-change");
    const [before] = await db.select().from(commissionTiers).where(eq(commissionTiers.id, id));
    await db.transaction(async (tx) => {
      await tx.delete(commissionTiers).where(eq(commissionTiers.id, id));
      if (before) {
        await auditChange({
          userId: auditCtx?.userId ?? null,
          actorType: (auditCtx?.actorType as any) ?? "user",
          action: "commission_tier_deleted",
          entityType: "commission_tier",
          entityId: id,
          before: before as unknown as Record<string, unknown>,
          after: null,
        }, tx);
      }
    });
  }


  async getAffiliateLeaderboard() {
    return await db.select().from(partners)
      .where(eq(partners.partnerType, "affiliate"))
      .orderBy(desc(partners.totalConversions))
      .limit(20);
  }


  async getKnowledgeBaseArticles() {
    return await db.select().from(knowledgeBase).orderBy(desc(knowledgeBase.createdAt));
  }


  async getKnowledgeBaseArticle(id: number) {
    const [article] = await db.select().from(knowledgeBase).where(eq(knowledgeBase.id, id));
    return article;
  }


  async getKnowledgeBaseByCategory(category: string) {
    return await db.select().from(knowledgeBase).where(eq(knowledgeBase.category, category)).orderBy(desc(knowledgeBase.createdAt));
  }


  async getPublishedArticles() {
    return await db.select().from(knowledgeBase).where(eq(knowledgeBase.isPublished, true)).orderBy(desc(knowledgeBase.createdAt));
  }


  async createKnowledgeBaseArticle(article: InsertKnowledgeBaseArticle) {
    const [created] = await db.insert(knowledgeBase).values(article).returning();
    return created;
  }


  async updateKnowledgeBaseArticle(id: number, updates: Partial<InsertKnowledgeBaseArticle>) {
    const [updated] = await db.update(knowledgeBase).set({ ...updates, updatedAt: new Date() }).where(eq(knowledgeBase.id, id)).returning();
    return updated;
  }

  }
  