// Auto-generated by storage split. Domain: residuals.
  // Methods are mixed into DatabaseStorage in server/storage.ts.
  import { db, pool } from "../db";
import {
  liveChats, liveChatMessages,
  type LiveChat, type InsertLiveChat, type LiveChatMessage, type InsertLiveChatMessage,
  contacts, companies, deals, tickets, tasks, documents, auditLogs, notifications, workflowRuns, workflows, rfis, users,
  chargebacks,
  type Chargeback, type InsertChargeback, type UpdateChargebackRequest,
  messageTemplates, collateralPackets, ghlActivityLog, slaConfigs,
  prospects, prospectLists, enrichmentJobs, campaigns, campaignSteps, outboundMessages, notes,
  emailLogs, callLogs, stageAutomationRules, followUpSequences, sequenceSteps, sequenceEnrollments,
  sunbizEntities, consentAuditLogs, calendarEvents,
  merchantApplications, merchantProfiles, equipmentOrders, agents, agentQuotas, agentMerchants, residualReports, merchantResiduals,
  healthAlerts, dealCompetitors, partners, referrals, commissionTiers, knowledgeBase, reviewRequests, testimonialSubmissions, onboardingSteps, midDailyStats,
  sdrMerchants, sdrMerchantContacts, sdrLeadState, sdrLeadEvents, sdrChannelAttempts, sdrComplianceState,
  sendingIdentities,
  leadDiscoveryJobs, leadDiscoveryResults,
  type SendingIdentity, type InsertSendingIdentity,
  businesses, businessAliases, businessLocations, leadSources, enrichmentRuns,
  type LeadDiscoveryJob, type InsertLeadDiscoveryJob,
  type LeadDiscoveryResult, type InsertLeadDiscoveryResult,
  type Business, type InsertBusiness, type UpdateBusinessRequest,
  type BusinessAlias, type InsertBusinessAlias,
  type BusinessLocation, type InsertBusinessLocation,
  type LeadSource, type InsertLeadSource,
  type EnrichmentRun, type InsertEnrichmentRun,
  type SdrMerchant, type InsertSdrMerchant,
  type SdrMerchantContact, type InsertSdrMerchantContact,
  type SdrLeadState, type InsertSdrLeadState,
  type SdrLeadEvent, type InsertSdrLeadEvent,
  type SdrChannelAttempt, type InsertSdrChannelAttempt,
  type SdrComplianceState, type InsertSdrComplianceState,
  type InsertContact, type UpdateContactRequest,
  type InsertCompany,
  type InsertDeal, type UpdateDealRequest,
  type InsertTicket, type UpdateTicketRequest,
  type InsertTask, type UpdateTaskRequest,
  type InsertDocument,
  type InsertAuditLog,
  type InsertNotification,
  type InsertWorkflow, type UpdateWorkflowRequest,
  type InsertWorkflowRun,
  type InsertRfi, type UpdateRfiRequest,
  type InsertMessageTemplate, type MessageTemplate,
  type InsertCollateralPacket,
  type InsertGhlActivityLog,
  type InsertSlaConfig,
  type Prospect, type InsertProspect, type UpdateProspectRequest,
  type InsertProspectList,
  type InsertEnrichmentJob,
  type InsertCampaign, type UpdateCampaignRequest,
  type InsertCampaignStep,
  type InsertOutboundMessage, type UpdateOutboundMessageRequest,
  type InsertNote,
  type InsertEmailLog, type InsertCallLog, type InsertStageAutomationRule, type InsertFollowUpSequence, type InsertSequenceStep, type InsertSequenceEnrollment,
  type InsertSunbizEntity, type UpdateSunbizEntityRequest, type SunbizEntity,
  type InsertMerchantApplication, type MerchantApplication,
  type InsertMerchantProfile, type MerchantProfile,
  type InsertEquipmentOrder, type EquipmentOrder,
  type InsertAgent, type Agent,
  type InsertAgentMerchant, type AgentMerchant,
  type InsertAgentQuota, type AgentQuota,
  type InsertResidualReport, type ResidualReport,
  type InsertMerchantResidual, type MerchantResidual,
  type InsertHealthAlert, type HealthAlert,
  type InsertDealCompetitor, type DealCompetitor,
  type InsertPartner, type Partner,
  type InsertReferral, type Referral,
  type InsertCommissionTier, type CommissionTier,
  type InsertKnowledgeBaseArticle, type KnowledgeBaseArticle,
  type InsertReviewRequest, type ReviewRequest,
  type InsertTestimonialSubmission, type TestimonialSubmission,
  type InsertOnboardingStep, type OnboardingStep,
  type InsertConsentAuditLog, type ConsentAuditLog,
  type CalendarEvent, type InsertCalendarEvent,
  systemSettings,
  dataDeleteRequests,
  type DataDeleteRequest, type InsertDataDeleteRequest,
  comments, ticketComments, contactCompanies, pipelineStages, notificationPreferences, savedFilters,
  type Comment, type InsertComment,
  type TicketComment, type InsertTicketComment,
  type ContactCompany, type InsertContactCompany,
  type PipelineStage, type InsertPipelineStage,
  type NotificationPreference, type InsertNotificationPreference,
  type SavedFilter, type InsertSavedFilter,
  csvImports, type CsvImport, type InsertCsvImport,
  generatedBlogPosts,
  type GeneratedBlogPost, type InsertGeneratedBlogPost,
  type UpdateSdrLeadState,
  ghlWorkflowMappings, type GhlWorkflowMapping,
  npsResponses, type NpsResponse, type InsertNpsResponse,
  merchantReferrals, type MerchantReferral, type InsertMerchantReferral,
  retentionCampaignConfigs, type RetentionCampaignConfig, type InsertRetentionCampaignConfig,
  type MidDailyStat, type InsertMidDailyStat,
  roleplaySessions, type RoleplaySession, type InsertRoleplaySession,
  roleplayExchanges, type RoleplayExchange, type InsertRoleplayExchange,
  leaderboardSettings, type LeaderboardSettings,
} from "@shared/schema";
import { eq, desc, and, lt, isNull, ne, sql, asc, gte, lte, inArray, or, ilike, count } from "drizzle-orm";
  import { type PaginationParams, type PaginatedResult, normalizePagination } from "./_shared";

  export class ResidualsStorage {
    async getResidualReports() {
    return await db.select().from(residualReports).orderBy(desc(residualReports.createdAt));
  }


  async getResidualReport(id: number) {
    const [report] = await db.select().from(residualReports).where(eq(residualReports.id, id));
    return report;
  }


  async getResidualReportsByMonth(month: string) {
    return await db.select().from(residualReports).where(eq(residualReports.month, month)).orderBy(desc(residualReports.createdAt));
  }


  async createResidualReport(report: InsertResidualReport) {
    const [created] = await db.insert(residualReports).values(report).returning();
    return created;
  }


  async getMerchantResiduals(reportId?: number) {
    if (reportId) {
      return await db.select().from(merchantResiduals).where(eq(merchantResiduals.reportId, reportId)).orderBy(desc(merchantResiduals.createdAt));
    }
    return await db.select().from(merchantResiduals).orderBy(desc(merchantResiduals.createdAt));
  }


  async getMerchantResidual(id: number) {
    const [residual] = await db.select().from(merchantResiduals).where(eq(merchantResiduals.id, id));
    return residual;
  }


  async getMerchantResidualsByDeal(dealId: number) {
    return await db.select().from(merchantResiduals).where(eq(merchantResiduals.dealId, dealId)).orderBy(desc(merchantResiduals.createdAt));
  }


  async getMerchantResidualsByMonth(month: string) {
    return await db.select().from(merchantResiduals).where(eq(merchantResiduals.month, month)).orderBy(desc(merchantResiduals.createdAt));
  }


  async createMerchantResidual(residual: InsertMerchantResidual) {
    const [created] = await db.insert(merchantResiduals).values(residual).returning();
    return created;
  }


  async getResidualImports() {
    const { residualImports } = await import("@shared/schema");
    return await db.select().from(residualImports).orderBy(desc(residualImports.createdAt));
  }


  async getResidualImport(id: number) {
    const { residualImports } = await import("@shared/schema");
    const [row] = await db.select().from(residualImports).where(eq(residualImports.id, id));
    return row;
  }


  async createResidualImport(data: import("@shared/schema").InsertResidualImport) {
    const { residualImports } = await import("@shared/schema");
    const [row] = await db.insert(residualImports).values(data).returning();
    return row;
  }


  async updateResidualImport(id: number, updates: Partial<import("@shared/schema").InsertResidualImport>) {
    const { residualImports } = await import("@shared/schema");
    const [row] = await db.update(residualImports).set(updates).where(eq(residualImports.id, id)).returning();
    return row;
  }


  async deleteResidualImport(id: number) {
    const { residualImports } = await import("@shared/schema");
    await db.delete(residualImports).where(eq(residualImports.id, id));
  }


  async getResidualImportRows(importId: number) {
    const { residualImportRows } = await import("@shared/schema");
    return await db.select().from(residualImportRows).where(eq(residualImportRows.importId, importId)).orderBy(desc(residualImportRows.createdAt));
  }


  async createResidualImportRow(data: import("@shared/schema").InsertResidualImportRow) {
    const { residualImportRows } = await import("@shared/schema");
    const [row] = await db.insert(residualImportRows).values(data).returning();
    return row;
  }


  async createResidualImportRowsBulk(data: import("@shared/schema").InsertResidualImportRow[]) {
    const { residualImportRows } = await import("@shared/schema");
    if (data.length === 0) return [];
    return await db.insert(residualImportRows).values(data).returning();
  }


  async getResidualImportRow(id: number) {
    const { residualImportRows } = await import("@shared/schema");
    const [row] = await db.select().from(residualImportRows).where(eq(residualImportRows.id, id));
    return row;
  }


  async updateResidualImportRow(id: number, updates: Partial<import("@shared/schema").InsertResidualImportRow>) {
    const { residualImportRows } = await import("@shared/schema");
    const [updated] = await db.update(residualImportRows).set(updates).where(eq(residualImportRows.id, id)).returning();
    return updated;
  }


  async deleteResidualImportRows(importId: number) {
    const { residualImportRows } = await import("@shared/schema");
    await db.delete(residualImportRows).where(eq(residualImportRows.importId, importId));
  }


  async getMidDailyStats(mid?: string) {
    if (mid) {
      return await db.select().from(midDailyStats).where(eq(midDailyStats.mid, mid)).orderBy(desc(midDailyStats.date));
    }
    return await db.select().from(midDailyStats).orderBy(desc(midDailyStats.date));
  }


  async getMidDailyStatsByDeal(dealId: number, days?: number) {
    const query = db.select().from(midDailyStats).where(eq(midDailyStats.dealId, dealId)).orderBy(desc(midDailyStats.date));
    if (days) {
      const cutoff = new Date();
      cutoff.setDate(cutoff.getDate() - days);
      const cutoffStr = cutoff.toISOString().split("T")[0];
      return await db.select().from(midDailyStats)
        .where(and(eq(midDailyStats.dealId, dealId), gte(midDailyStats.date, cutoffStr)))
        .orderBy(desc(midDailyStats.date));
    }
    return await query;
  }


  async getMidDailyStatByMidAndDate(mid: string, date: string) {
    const [stat] = await db.select().from(midDailyStats)
      .where(and(eq(midDailyStats.mid, mid), eq(midDailyStats.date, date)));
    return stat;
  }


  async createMidDailyStat(stat: InsertMidDailyStat) {
    const [created] = await db.insert(midDailyStats).values(stat).returning();
    return created;
  }


  async updateMidDailyStat(id: number, updates: Partial<InsertMidDailyStat>) {
    const [updated] = await db.update(midDailyStats).set(updates).where(eq(midDailyStats.id, id)).returning();
    return updated;
  }


  async upsertMidDailyStat(stat: InsertMidDailyStat) {
    const existing = await this.getMidDailyStatByMidAndDate(stat.mid, stat.date);
    if (existing) {
      return await this.updateMidDailyStat(existing.id, stat);
    }
    return await this.createMidDailyStat(stat);
  }

  // ── Partner Organizations ─────────────────────────────────────────────────
  }
  