// Auto-generated by storage split. Domain: residuals.
  // Methods are mixed into DatabaseStorage in server/storage.ts.
  import { db, pool } from "../db";
import {
  liveChats, liveChatMessages,
  type LiveChat, type InsertLiveChat, type LiveChatMessage, type InsertLiveChatMessage,
  contacts, companies, deals, tickets, tasks, documents, auditLogs, notifications, workflowRuns, workflows, rfis, users,
  chargebacks,
  type Chargeback, type InsertChargeback, type UpdateChargebackRequest,
  messageTemplates, collateralPackets, ghlActivityLog, slaConfigs,
  prospects, prospectLists, enrichmentJobs, campaigns, campaignSteps, outboundMessages, notes,
  emailLogs, callLogs, stageAutomationRules, followUpSequences, sequenceSteps, sequenceEnrollments,
  sunbizEntities, consentAuditLogs, calendarEvents,
  merchantApplications, merchantProfiles, equipmentOrders, agents, agentQuotas, agentMerchants, residualReports, merchantResiduals,
  partnerOrganizations,
  healthAlerts, dealCompetitors, partners, referrals, commissionTiers, knowledgeBase, reviewRequests, testimonialSubmissions, onboardingSteps, midDailyStats,
  sdrMerchants, sdrMerchantContacts, sdrLeadState, sdrLeadEvents, sdrChannelAttempts, sdrComplianceState,
  sendingIdentities,
  leadDiscoveryJobs, leadDiscoveryResults,
  type SendingIdentity, type InsertSendingIdentity,
  businesses, businessAliases, businessLocations, leadSources, enrichmentRuns,
  type LeadDiscoveryJob, type InsertLeadDiscoveryJob,
  type LeadDiscoveryResult, type InsertLeadDiscoveryResult,
  type Business, type InsertBusiness, type UpdateBusinessRequest,
  type BusinessAlias, type InsertBusinessAlias,
  type BusinessLocation, type InsertBusinessLocation,
  type LeadSource, type InsertLeadSource,
  type EnrichmentRun, type InsertEnrichmentRun,
  type SdrMerchant, type InsertSdrMerchant,
  type SdrMerchantContact, type InsertSdrMerchantContact,
  type SdrLeadState, type InsertSdrLeadState,
  type SdrLeadEvent, type InsertSdrLeadEvent,
  type SdrChannelAttempt, type InsertSdrChannelAttempt,
  type SdrComplianceState, type InsertSdrComplianceState,
  type InsertContact, type UpdateContactRequest,
  type InsertCompany,
  type InsertDeal, type UpdateDealRequest,
  type InsertTicket, type UpdateTicketRequest,
  type InsertTask, type UpdateTaskRequest,
  type InsertDocument,
  type InsertAuditLog,
  type InsertNotification,
  type InsertWorkflow, type UpdateWorkflowRequest,
  type InsertWorkflowRun,
  type InsertRfi, type UpdateRfiRequest,
  type InsertMessageTemplate, type MessageTemplate,
  type InsertCollateralPacket,
  type InsertGhlActivityLog,
  type InsertSlaConfig,
  type Prospect, type InsertProspect, type UpdateProspectRequest,
  type InsertProspectList,
  type InsertEnrichmentJob,
  type InsertCampaign, type UpdateCampaignRequest,
  type InsertCampaignStep,
  type InsertOutboundMessage, type UpdateOutboundMessageRequest,
  type InsertNote,
  type InsertEmailLog, type InsertCallLog, type InsertStageAutomationRule, type InsertFollowUpSequence, type InsertSequenceStep, type InsertSequenceEnrollment,
  type InsertSunbizEntity, type UpdateSunbizEntityRequest, type SunbizEntity,
  type InsertMerchantApplication, type MerchantApplication,
  type InsertMerchantProfile, type MerchantProfile,
  type InsertEquipmentOrder, type EquipmentOrder,
  type InsertAgent, type Agent,
  type InsertAgentMerchant, type AgentMerchant,
  type InsertAgentQuota, type AgentQuota,
  type InsertResidualReport, type ResidualReport,
  type InsertMerchantResidual, type MerchantResidual,
  type InsertHealthAlert, type HealthAlert,
  type InsertDealCompetitor, type DealCompetitor,
  type InsertPartner, type Partner,
  type InsertReferral, type Referral,
  type InsertCommissionTier, type CommissionTier,
  type InsertKnowledgeBaseArticle, type KnowledgeBaseArticle,
  type InsertReviewRequest, type ReviewRequest,
  type InsertTestimonialSubmission, type TestimonialSubmission,
  type InsertOnboardingStep, type OnboardingStep,
  type InsertConsentAuditLog, type ConsentAuditLog,
  type CalendarEvent, type InsertCalendarEvent,
  systemSettings,
  dataDeleteRequests,
  type DataDeleteRequest, type InsertDataDeleteRequest,
  comments, ticketComments, contactCompanies, pipelineStages, notificationPreferences, savedFilters,
  type Comment, type InsertComment,
  type TicketComment, type InsertTicketComment,
  type ContactCompany, type InsertContactCompany,
  type PipelineStage, type InsertPipelineStage,
  type NotificationPreference, type InsertNotificationPreference,
  type SavedFilter, type InsertSavedFilter,
  csvImports, type CsvImport, type InsertCsvImport,
  generatedBlogPosts,
  type GeneratedBlogPost, type InsertGeneratedBlogPost,
  type UpdateSdrLeadState,
  ghlWorkflowMappings, type GhlWorkflowMapping,
  npsResponses, type NpsResponse, type InsertNpsResponse,
  merchantReferrals, type MerchantReferral, type InsertMerchantReferral,
  retentionCampaignConfigs, type RetentionCampaignConfig, type InsertRetentionCampaignConfig,
  type MidDailyStat, type InsertMidDailyStat,
  roleplaySessions, type RoleplaySession, type InsertRoleplaySession,
  roleplayExchanges, type RoleplayExchange, type InsertRoleplayExchange,
  leaderboardSettings, type LeaderboardSettings,
} from "@shared/schema";
import { eq, desc, and, lt, isNull, ne, sql, asc, gte, lte, inArray, or, ilike, count } from "drizzle-orm";
  import { type PaginationParams, type PaginatedResult, normalizePagination } from "./_shared";

  export class ResidualsStorage {
    async getResidualReports() {
    return await db.select().from(residualReports).orderBy(desc(residualReports.createdAt));
  }


  async getResidualReport(id: number) {
    const [report] = await db.select().from(residualReports).where(eq(residualReports.id, id));
    return report;
  }


  async getResidualReportsByMonth(month: string) {
    return await db.select().from(residualReports).where(eq(residualReports.month, month)).orderBy(desc(residualReports.createdAt));
  }


  async createResidualReport(report: InsertResidualReport, auditCtx?: { userId?: string | null; actorType?: string; actorId?: string | null }) {
    const { auditChange } = await import("../services/audit-change");
    return await db.transaction(async (tx) => {
      const [created] = await tx.insert(residualReports).values(report).returning();
      await auditChange({
        userId: auditCtx?.userId ?? null,
        actorType: (auditCtx?.actorType as any) ?? "user",
        actorId: auditCtx?.actorId ?? null,
        action: "residual_report_created",
        entityType: "residual_report",
        entityId: created.id,
        before: null,
        after: created as unknown as Record<string, unknown>,
      }, tx);
      return created;
    });
  }


  async getMerchantResiduals(reportId?: number) {
    if (reportId) {
      return await db.select().from(merchantResiduals).where(eq(merchantResiduals.reportId, reportId)).orderBy(desc(merchantResiduals.createdAt));
    }
    return await db.select().from(merchantResiduals).orderBy(desc(merchantResiduals.createdAt));
  }


  async getMerchantResidual(id: number) {
    const [residual] = await db.select().from(merchantResiduals).where(eq(merchantResiduals.id, id));
    return residual;
  }


  async getMerchantResidualsByDeal(dealId: number) {
    return await db.select().from(merchantResiduals).where(eq(merchantResiduals.dealId, dealId)).orderBy(desc(merchantResiduals.createdAt));
  }


  async getMerchantResidualsByMonth(month: string) {
    return await db.select().from(merchantResiduals).where(eq(merchantResiduals.month, month)).orderBy(desc(merchantResiduals.createdAt));
  }


  async createMerchantResidual(residual: InsertMerchantResidual) {
    const [created] = await db.insert(merchantResiduals).values(residual).returning();
    return created;
  }


  async getResidualImports() {
    const { residualImports } = await import("@shared/schema");
    return await db.select().from(residualImports).orderBy(desc(residualImports.createdAt));
  }


  async getResidualImport(id: number) {
    const { residualImports } = await import("@shared/schema");
    const [row] = await db.select().from(residualImports).where(eq(residualImports.id, id));
    return row;
  }


  async createResidualImport(data: import("@shared/schema").InsertResidualImport) {
    const { residualImports } = await import("@shared/schema");
    const [row] = await db.insert(residualImports).values(data).returning();
    return row;
  }


  async updateResidualImport(id: number, updates: Partial<import("@shared/schema").InsertResidualImport>) {
    const { residualImports } = await import("@shared/schema");
    const [row] = await db.update(residualImports).set(updates).where(eq(residualImports.id, id)).returning();
    return row;
  }


  async deleteResidualImport(id: number) {
    const { residualImports } = await import("@shared/schema");
    await db.delete(residualImports).where(eq(residualImports.id, id));
  }


  async getResidualImportRows(importId: number) {
    const { residualImportRows } = await import("@shared/schema");
    return await db.select().from(residualImportRows).where(eq(residualImportRows.importId, importId)).orderBy(desc(residualImportRows.createdAt));
  }


  async createResidualImportRow(data: import("@shared/schema").InsertResidualImportRow) {
    const { residualImportRows } = await import("@shared/schema");
    const [row] = await db.insert(residualImportRows).values(data).returning();
    return row;
  }


  async createResidualImportRowsBulk(data: import("@shared/schema").InsertResidualImportRow[]) {
    const { residualImportRows } = await import("@shared/schema");
    if (data.length === 0) return [];
    return await db.insert(residualImportRows).values(data).returning();
  }


  async getResidualImportRow(id: number) {
    const { residualImportRows } = await import("@shared/schema");
    const [row] = await db.select().from(residualImportRows).where(eq(residualImportRows.id, id));
    return row;
  }


  async updateResidualImportRow(id: number, updates: Partial<import("@shared/schema").InsertResidualImportRow>) {
    const { residualImportRows } = await import("@shared/schema");
    const [updated] = await db.update(residualImportRows).set(updates).where(eq(residualImportRows.id, id)).returning();
    return updated;
  }


  async deleteResidualImportRows(importId: number) {
    const { residualImportRows } = await import("@shared/schema");
    await db.delete(residualImportRows).where(eq(residualImportRows.importId, importId));
  }


  async getMidDailyStats(mid?: string) {
    if (mid) {
      return await db.select().from(midDailyStats).where(eq(midDailyStats.mid, mid)).orderBy(desc(midDailyStats.date));
    }
    return await db.select().from(midDailyStats).orderBy(desc(midDailyStats.date));
  }


  async getMidDailyStatsByDeal(dealId: number, days?: number) {
    const query = db.select().from(midDailyStats).where(eq(midDailyStats.dealId, dealId)).orderBy(desc(midDailyStats.date));
    if (days) {
      const cutoff = new Date();
      cutoff.setDate(cutoff.getDate() - days);
      const cutoffStr = cutoff.toISOString().split("T")[0];
      return await db.select().from(midDailyStats)
        .where(and(eq(midDailyStats.dealId, dealId), gte(midDailyStats.date, cutoffStr)))
        .orderBy(desc(midDailyStats.date));
    }
    return await query;
  }


  async getMidDailyStatByMidAndDate(mid: string, date: string) {
    const [stat] = await db.select().from(midDailyStats)
      .where(and(eq(midDailyStats.mid, mid), eq(midDailyStats.date, date)));
    return stat;
  }


  async createMidDailyStat(stat: InsertMidDailyStat) {
    const [created] = await db.insert(midDailyStats).values(stat).returning();
    return created;
  }


  async updateMidDailyStat(id: number, updates: Partial<InsertMidDailyStat>) {
    const [updated] = await db.update(midDailyStats).set(updates).where(eq(midDailyStats.id, id)).returning();
    return updated;
  }


  async upsertMidDailyStat(stat: InsertMidDailyStat) {
    const existing = await this.getMidDailyStatByMidAndDate(stat.mid, stat.date);
    if (existing) {
      return await this.updateMidDailyStat(existing.id, stat);
    }
    return await this.createMidDailyStat(stat);
  }

  // ── Agent Payout Ledger ───────────────────────────────────────────────────

  async getAgentPayouts(filters?: { status?: string; periodMonth?: string }) {
    const { agentPayouts } = await import("@shared/schema");
    const conditions = [];
    if (filters?.status) conditions.push(eq(agentPayouts.status, filters.status));
    if (filters?.periodMonth) conditions.push(eq(agentPayouts.periodMonth, filters.periodMonth));
    const query = conditions.length
      ? db.select().from(agentPayouts).where(and(...conditions as any))
      : db.select().from(agentPayouts);
    return await query.orderBy(desc(agentPayouts.periodMonth));
  }

  async getAgentPayoutsForUser(agentUserId: string) {
    const { agentPayouts } = await import("@shared/schema");
    return await db.select().from(agentPayouts)
      .where(eq(agentPayouts.agentUserId, agentUserId))
      .orderBy(desc(agentPayouts.periodMonth));
  }

  async getAgentPayout(id: number) {
    const { agentPayouts } = await import("@shared/schema");
    const [row] = await db.select().from(agentPayouts).where(eq(agentPayouts.id, id));
    return row;
  }

  async createAgentPayout(data: import("@shared/schema").InsertAgentPayout) {
    const { agentPayouts } = await import("@shared/schema");
    const [row] = await db.insert(agentPayouts).values(data).returning();
    return row;
  }

  async updateAgentPayout(id: number, updates: Partial<import("@shared/schema").InsertAgentPayout> & { paidAt?: Date | null; updatedAt?: Date; partnerOrgId?: number | null }) {
    const { agentPayouts } = await import("@shared/schema");
    const [row] = await db.update(agentPayouts).set({ ...updates, updatedAt: new Date() })
      .where(eq(agentPayouts.id, id)).returning();
    return row;
  }

  /**
   * Atomically transitions a payout from `fromStatus` → `toStatus`.
   * The status predicate is part of the UPDATE WHERE clause, so concurrent
   * requests cannot both succeed. Returns the updated row, or null if
   * no row matched (i.e. the status already changed).
   */
  async transitionPayoutStatus(
    id: number,
    fromStatus: string,
    toStatus: string,
    extra: { paidAt?: Date; notes?: string },
  ) {
    const { agentPayouts } = await import("@shared/schema");
    const setClause: Record<string, unknown> = { status: toStatus, updatedAt: new Date() };
    if (extra.paidAt !== undefined) setClause.paidAt = extra.paidAt;
    if (extra.notes !== undefined) setClause.notes = extra.notes;
    const [row] = await db.update(agentPayouts)
      .set(setClause as any)
      .where(and(eq(agentPayouts.id, id), eq(agentPayouts.status, fromStatus)))
      .returning();
    return row ?? null;
  }

  async generatePayoutsForMonth(month: string) {
    // Aggregate merchantResiduals for the month, grouped by (agentId, partnerOrgId).
    // Each (agent, partnerOrg) pair gets its own ledger row so partner attribution is preserved.
    // Residuals with no deal or a deal with no partner org land in the partnerOrgId=null bucket.
    //
    // CONCURRENCY SAFETY:
    //   1. The entire generation is wrapped in a transaction that immediately acquires a
    //      PostgreSQL session advisory lock keyed to this month. Concurrent generators block
    //      at the lock and see the updated residual snapshot once they proceed.
    //   2. Each upsert includes `WHERE agent_payouts.status = 'pending'` in the DO UPDATE
    //      clause so approved/paid rows are never overwritten, even if a race occurs.

    return db.transaction(async (tx) => {
      // Acquire an exclusive advisory lock for this month's generation.
      // pg_advisory_xact_lock blocks until no other session holds the same key
      // and is released automatically at transaction end.
      await tx.execute(sql`SELECT pg_advisory_xact_lock(hashtext('payouts_generate_' || ${month}))`);

      // Resolve the canonical confirmed import for this month: the most recently confirmed one.
      // Generation aggregates ONLY residuals stamped with this import_id (rows from earlier imports
      // for the same month are excluded). This prevents double-counting when a month is re-imported.
      const { residualImports: riTable } = await import("@shared/schema");
      const [canonicalImport] = await tx.select({ id: riTable.id })
        .from(riTable)
        .where(and(eq(riTable.month, month), eq(riTable.status, "confirmed")))
        .orderBy(desc(riTable.id))
        .limit(1);

      // Read the finalized residual snapshot inside the transaction.
      // • When a confirmed import exists: use only its rows (import_id = canonicalImport.id).
      // • When no confirmed import exists: use only legacy rows (import_id IS NULL).
      //   This explicitly excludes rows tied to a pending import — those are not yet finalized.
      const residualFilter = canonicalImport
        ? and(eq(merchantResiduals.month, month), eq(merchantResiduals.importId, canonicalImport.id))
        : and(eq(merchantResiduals.month, month), sql`${merchantResiduals.importId} IS NULL`);

      const residualRows = await tx.select().from(merchantResiduals)
        .where(residualFilter);

      // Batch-resolve partnerOrgId for every unique dealId in one query.
      const allDealIds = [...new Set(residualRows.map(r => r.dealId).filter((id): id is number => id != null))];
      const dealPartnerMap = new Map<number, number | null>();
      if (allDealIds.length > 0) {
        const dealRows = await tx.select({ id: deals.id, partnerOrgId: deals.partnerOrgId })
          .from(deals)
          .where(inArray(deals.id, allDealIds));
        for (const d of dealRows) dealPartnerMap.set(d.id, d.partnerOrgId ?? null);
      }

      // Group by (agentId, partnerOrgId) — one ledger row per unique combination.
      const byAgentPartner = new Map<string, {
        agentId: number;
        partnerOrgId: number | null;
        grossResidual: number;
        agentCommission: number;
        partnerCommission: number;
      }>();

      for (const row of residualRows) {
        if (!row.agentId) continue;
        const partnerOrgId = row.dealId != null ? (dealPartnerMap.get(row.dealId) ?? null) : null;
        const key = `${row.agentId}:${partnerOrgId ?? "null"}`;
        const existing = byAgentPartner.get(key) ?? { agentId: row.agentId, partnerOrgId, grossResidual: 0, agentCommission: 0, partnerCommission: 0 };
        existing.grossResidual += parseFloat(row.revenue || "0");
        existing.agentCommission += parseFloat(row.agentCommission || "0");
        existing.partnerCommission += parseFloat(row.partnerCommission || "0");
        byAgentPartner.set(key, existing);
      }

      // Resolve all agent user accounts in one batch to minimise round-trips.
      const agentIds = [...new Set([...byAgentPartner.values()].map(t => t.agentId))];
      const agentRecords = agentIds.length > 0
        ? await tx.select().from(agents).where(inArray(agents.id, agentIds))
        : [];
      const agentUserMap = new Map(agentRecords.filter(a => a.userId).map(a => [a.id, a.userId!]));

      type UpsertRow = { id: number; agent_user_id: string; partner_user_id: string | null; partner_org_id: number | null; period_month: string; gross_residual: string; agent_share: string; partner_share: string; status: string; paid_at: Date | null; notes: string | null; created_at: Date | null; updated_at: Date | null };
      const { agentPayouts } = await import("@shared/schema");
      const results = [];

      for (const [, totals] of byAgentPartner) {
        const agentUserId = agentUserMap.get(totals.agentId);
        if (!agentUserId) continue;

        const grossResidual = totals.grossResidual.toFixed(2);
        const agentShare = totals.agentCommission.toFixed(2);
        const partnerShare = totals.partnerCommission.toFixed(2);
        const partnerOrgId = totals.partnerOrgId;

        // Atomic upsert: insert or update pending rows only.
        // The WHERE clause on DO UPDATE means approved/paid rows are never touched.
        let upsertRows: UpsertRow[];

        if (partnerOrgId == null) {
          const { rows } = await tx.execute(sql`
            INSERT INTO agent_payouts
              (agent_user_id, partner_org_id, period_month, gross_residual, agent_share, partner_share, status, created_at, updated_at)
            VALUES
              (${agentUserId}, NULL, ${month}, ${grossResidual}, ${agentShare}, ${partnerShare}, 'pending', NOW(), NOW())
            ON CONFLICT (agent_user_id, period_month) WHERE partner_org_id IS NULL
            DO UPDATE SET
              gross_residual = EXCLUDED.gross_residual,
              agent_share    = EXCLUDED.agent_share,
              partner_share  = EXCLUDED.partner_share,
              updated_at     = NOW()
            WHERE agent_payouts.status = 'pending'
            RETURNING *
          `);
          upsertRows = rows as UpsertRow[];
        } else {
          const { rows } = await tx.execute(sql`
            INSERT INTO agent_payouts
              (agent_user_id, partner_org_id, period_month, gross_residual, agent_share, partner_share, status, created_at, updated_at)
            VALUES
              (${agentUserId}, ${partnerOrgId}, ${month}, ${grossResidual}, ${agentShare}, ${partnerShare}, 'pending', NOW(), NOW())
            ON CONFLICT (agent_user_id, period_month, partner_org_id) WHERE partner_org_id IS NOT NULL
            DO UPDATE SET
              gross_residual = EXCLUDED.gross_residual,
              agent_share    = EXCLUDED.agent_share,
              partner_share  = EXCLUDED.partner_share,
              updated_at     = NOW()
            WHERE agent_payouts.status = 'pending'
            RETURNING *
          `);
          upsertRows = rows as UpsertRow[];
        }

        if (upsertRows.length > 0) {
          // Upsert succeeded (new insert or pending row updated) — map to camelCase.
          const r = upsertRows[0];
          results.push({
            id: r.id,
            agentUserId: r.agent_user_id,
            partnerUserId: r.partner_user_id,
            partnerOrgId: r.partner_org_id,
            periodMonth: r.period_month,
            grossResidual: r.gross_residual,
            agentShare: r.agent_share,
            partnerShare: r.partner_share,
            status: r.status,
            paidAt: r.paid_at,
            notes: r.notes,
            createdAt: r.created_at,
            updatedAt: r.updated_at,
          });
        } else {
          // DO UPDATE WHERE predicate didn't match → row is approved/paid; fetch and return it unchanged.
          const conditions = [
            eq(agentPayouts.agentUserId, agentUserId),
            eq(agentPayouts.periodMonth, month),
            partnerOrgId == null
              ? sql`${agentPayouts.partnerOrgId} IS NULL`
              : eq(agentPayouts.partnerOrgId, partnerOrgId),
          ];
          const [existingRow] = await tx.select().from(agentPayouts).where(and(...conditions as any));
          if (existingRow) results.push(existingRow);
        }
      }

      return results;
    });
  }

  // ── Partner Organizations ─────────────────────────────────────────────────
  }
  