// Auto-generated by storage split. Domain: reviews.
  // Methods are mixed into DatabaseStorage in server/storage.ts.
  import { db, pool } from "../db";
import {
  liveChats, liveChatMessages,
  type LiveChat, type InsertLiveChat, type LiveChatMessage, type InsertLiveChatMessage,
  contacts, companies, deals, tickets, tasks, documents, auditLogs, notifications, workflowRuns, workflows, rfis, users,
  chargebacks,
  type Chargeback, type InsertChargeback, type UpdateChargebackRequest,
  messageTemplates, collateralPackets, ghlActivityLog, slaConfigs,
  prospects, prospectLists, enrichmentJobs, campaigns, campaignSteps, outboundMessages, notes,
  emailLogs, callLogs, stageAutomationRules, followUpSequences, sequenceSteps, sequenceEnrollments,
  sunbizEntities, consentAuditLogs, calendarEvents,
  merchantApplications, merchantProfiles, equipmentOrders, agents, agentQuotas, agentMerchants, residualReports, merchantResiduals,
  healthAlerts, dealCompetitors, partners, referrals, commissionTiers, knowledgeBase, reviewRequests, testimonialSubmissions, onboardingSteps, midDailyStats,
  sdrMerchants, sdrMerchantContacts, sdrLeadState, sdrLeadEvents, sdrChannelAttempts, sdrComplianceState,
  sendingIdentities,
  leadDiscoveryJobs, leadDiscoveryResults,
  type SendingIdentity, type InsertSendingIdentity,
  businesses, businessAliases, businessLocations, leadSources, enrichmentRuns,
  type LeadDiscoveryJob, type InsertLeadDiscoveryJob,
  type LeadDiscoveryResult, type InsertLeadDiscoveryResult,
  type Business, type InsertBusiness, type UpdateBusinessRequest,
  type BusinessAlias, type InsertBusinessAlias,
  type BusinessLocation, type InsertBusinessLocation,
  type LeadSource, type InsertLeadSource,
  type EnrichmentRun, type InsertEnrichmentRun,
  type SdrMerchant, type InsertSdrMerchant,
  type SdrMerchantContact, type InsertSdrMerchantContact,
  type SdrLeadState, type InsertSdrLeadState,
  type SdrLeadEvent, type InsertSdrLeadEvent,
  type SdrChannelAttempt, type InsertSdrChannelAttempt,
  type SdrComplianceState, type InsertSdrComplianceState,
  type InsertContact, type UpdateContactRequest,
  type InsertCompany,
  type InsertDeal, type UpdateDealRequest,
  type InsertTicket, type UpdateTicketRequest,
  type InsertTask, type UpdateTaskRequest,
  type InsertDocument,
  type InsertAuditLog,
  type InsertNotification,
  type InsertWorkflow, type UpdateWorkflowRequest,
  type InsertWorkflowRun,
  type InsertRfi, type UpdateRfiRequest,
  type InsertMessageTemplate, type MessageTemplate,
  type InsertCollateralPacket,
  type InsertGhlActivityLog,
  type InsertSlaConfig,
  type Prospect, type InsertProspect, type UpdateProspectRequest,
  type InsertProspectList,
  type InsertEnrichmentJob,
  type InsertCampaign, type UpdateCampaignRequest,
  type InsertCampaignStep,
  type InsertOutboundMessage, type UpdateOutboundMessageRequest,
  type InsertNote,
  type InsertEmailLog, type InsertCallLog, type InsertStageAutomationRule, type InsertFollowUpSequence, type InsertSequenceStep, type InsertSequenceEnrollment,
  type InsertSunbizEntity, type UpdateSunbizEntityRequest, type SunbizEntity,
  type InsertMerchantApplication, type MerchantApplication,
  type InsertMerchantProfile, type MerchantProfile,
  type InsertEquipmentOrder, type EquipmentOrder,
  type InsertAgent, type Agent,
  type InsertAgentMerchant, type AgentMerchant,
  type InsertAgentQuota, type AgentQuota,
  type InsertResidualReport, type ResidualReport,
  type InsertMerchantResidual, type MerchantResidual,
  type InsertHealthAlert, type HealthAlert,
  type InsertDealCompetitor, type DealCompetitor,
  type InsertPartner, type Partner,
  type InsertReferral, type Referral,
  type InsertCommissionTier, type CommissionTier,
  type InsertKnowledgeBaseArticle, type KnowledgeBaseArticle,
  type InsertReviewRequest, type ReviewRequest,
  type InsertTestimonialSubmission, type TestimonialSubmission,
  type InsertOnboardingStep, type OnboardingStep,
  type InsertConsentAuditLog, type ConsentAuditLog,
  type CalendarEvent, type InsertCalendarEvent,
  systemSettings,
  dataDeleteRequests,
  type DataDeleteRequest, type InsertDataDeleteRequest,
  comments, ticketComments, contactCompanies, pipelineStages, notificationPreferences, savedFilters,
  type Comment, type InsertComment,
  type TicketComment, type InsertTicketComment,
  type ContactCompany, type InsertContactCompany,
  type PipelineStage, type InsertPipelineStage,
  type NotificationPreference, type InsertNotificationPreference,
  type SavedFilter, type InsertSavedFilter,
  csvImports, type CsvImport, type InsertCsvImport,
  generatedBlogPosts,
  type GeneratedBlogPost, type InsertGeneratedBlogPost,
  type UpdateSdrLeadState,
  ghlWorkflowMappings, type GhlWorkflowMapping,
  npsResponses, type NpsResponse, type InsertNpsResponse,
  merchantReferrals, type MerchantReferral, type InsertMerchantReferral,
  retentionCampaignConfigs, type RetentionCampaignConfig, type InsertRetentionCampaignConfig,
  type MidDailyStat, type InsertMidDailyStat,
  roleplaySessions, type RoleplaySession, type InsertRoleplaySession,
  roleplayExchanges, type RoleplayExchange, type InsertRoleplayExchange,
  leaderboardSettings, type LeaderboardSettings,
} from "@shared/schema";
import { eq, desc, and, lt, isNull, ne, sql, asc, gte, lte, inArray, or, ilike, count, getTableColumns } from "drizzle-orm";
import { npsStatsReadSchema } from "../../shared/nps-observation";

// A-owned management read scope only. Public token reads and B writes are unchanged.
const npsManagementReadScope = () => sql`
  ${contacts.recordClass} = 'production' AND ${contacts.archivedAt} IS NULL
  AND (${npsResponses.createdAt} IS NULL OR ${npsResponses.createdAt} <= statement_timestamp())
  AND (${npsResponses.submittedAt} IS NULL OR ${npsResponses.submittedAt} <= statement_timestamp())`;
  import { type PaginationParams, type PaginatedResult, normalizePagination } from "./_shared";

  export class ReviewsStorage {
    async getReviewRequests(dealId?: number) {
    if (dealId) {
      return await db.select().from(reviewRequests).where(eq(reviewRequests.dealId, dealId)).orderBy(desc(reviewRequests.createdAt));
    }
    return await db.select().from(reviewRequests).orderBy(desc(reviewRequests.createdAt));
  }


  async getReviewRequest(id: number) {
    const [request] = await db.select().from(reviewRequests).where(eq(reviewRequests.id, id));
    return request;
  }


  async getReviewRequestsByDeal(dealId: number) {
    return await db.select().from(reviewRequests).where(eq(reviewRequests.dealId, dealId)).orderBy(desc(reviewRequests.createdAt));
  }


  async createReviewRequest(request: InsertReviewRequest) {
    const [created] = await db.insert(reviewRequests).values(request).returning();
    return created;
  }


  async updateReviewRequest(id: number, updates: Partial<InsertReviewRequest>) {
    const [updated] = await db.update(reviewRequests).set(updates).where(eq(reviewRequests.id, id)).returning();
    return updated;
  }


  async getTestimonialSubmissions(status?: string) {
    if (status) {
      return await db.select().from(testimonialSubmissions).where(eq(testimonialSubmissions.status, status)).orderBy(desc(testimonialSubmissions.createdAt));
    }
    return await db.select().from(testimonialSubmissions).orderBy(desc(testimonialSubmissions.createdAt));
  }


  async getTestimonialSubmission(id: number) {
    const [submission] = await db.select().from(testimonialSubmissions).where(eq(testimonialSubmissions.id, id));
    return submission;
  }


  async getPublishedTestimonialSubmissions() {
    return await db.select().from(testimonialSubmissions)
      .where(and(eq(testimonialSubmissions.status, "approved"), eq(testimonialSubmissions.publish, true)))
      .orderBy(desc(testimonialSubmissions.createdAt));
  }


  async createTestimonialSubmission(submission: InsertTestimonialSubmission) {
    const [created] = await db.insert(testimonialSubmissions).values(submission).returning();
    return created;
  }


  async updateTestimonialSubmission(id: number, updates: Partial<InsertTestimonialSubmission>) {
    const payload: any = { ...updates };
    if (updates.status && updates.status !== "pending") {
      payload.reviewedAt = new Date();
    }
    const [updated] = await db.update(testimonialSubmissions).set(payload).where(eq(testimonialSubmissions.id, id)).returning();
    return updated;
  }


  async getNpsResponses() {
    return db.select(getTableColumns(npsResponses)).from(npsResponses)
      .innerJoin(contacts, eq(npsResponses.contactId, contacts.id))
      .where(npsManagementReadScope())
      .orderBy(desc(npsResponses.createdAt), desc(npsResponses.id));
  }

  async getNpsResponse(id: number) {
    const [row] = await db.select().from(npsResponses).where(eq(npsResponses.id, id));
    return row;
  }

  async getNpsResponseByToken(token: string) {
    const [row] = await db.select().from(npsResponses).where(eq(npsResponses.token, token));
    return row;
  }

  async getNpsResponsesByContact(contactId: number) {
    return db.select().from(npsResponses).where(eq(npsResponses.contactId, contactId)).orderBy(desc(npsResponses.createdAt));
  }

  async createNpsResponse(response: InsertNpsResponse) {
    const [row] = await db.insert(npsResponses).values(response).returning();
    return row;
  }

  async updateNpsResponse(id: number, updates: Partial<InsertNpsResponse>) {
    const [row] = await db.update(npsResponses).set(updates).where(eq(npsResponses.id, id)).returning();
    return row;
  }

  async getNpsStats() {
    const result = await db.execute(sql`
      WITH scoped AS (
        SELECT ${npsResponses.score} AS score, ${npsResponses.submittedAt} AS submitted_at
        FROM ${npsResponses} INNER JOIN ${contacts}
          ON ${npsResponses.contactId} = ${contacts.id}
        WHERE ${npsManagementReadScope()}
      ), sample AS (
        SELECT count(*)::int AS total,
          count(*) FILTER (WHERE submitted_at IS NOT NULL)::int AS submitted,
          count(*) FILTER (WHERE submitted_at IS NOT NULL AND score BETWEEN 0 AND 10)::int AS scored,
          round(avg(score) FILTER (WHERE submitted_at IS NOT NULL AND score BETWEEN 0 AND 10), 1)::float8 AS "avgScore",
          count(*) FILTER (WHERE submitted_at IS NOT NULL AND score BETWEEN 9 AND 10)::int AS promoters,
          count(*) FILTER (WHERE submitted_at IS NOT NULL AND score BETWEEN 0 AND 6)::int AS detractors,
          count(*) FILTER (WHERE submitted_at IS NOT NULL AND score BETWEEN 7 AND 8)::int AS passives
        FROM scoped
      )
      SELECT *, submitted - scored AS "invalidSubmitted",
        CASE WHEN scored > 0 THEN round(100.0 * (promoters - detractors) / scored)::int ELSE NULL END AS "npsScore",
        to_char(statement_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"') AS "asOf"
      FROM sample`);
    const row = result.rows[0];
    return npsStatsReadSchema.parse({
      ...row, metadata: {
        source: "nps_responses", scope: "nonarchived_production_contact_surveys",
        period: "all_stored_observations_up_to_asOf", timezone: "UTC",
        asOf: row.asOf, snapshotConsistency: "single_statement",
        units: "survey_records_not_unique_merchants",
      },
    });
  }

  // ── Merchant Referrals ─────────────────────────────────────────────────────

  async getMerchantReferrals(referrerProfileId?: number) {
    if (referrerProfileId !== undefined) {
      return db.select().from(merchantReferrals).where(eq(merchantReferrals.referrerProfileId, referrerProfileId)).orderBy(desc(merchantReferrals.createdAt));
    }
    return db.select().from(merchantReferrals).orderBy(desc(merchantReferrals.createdAt));
  }

  async getMerchantReferral(id: number) {
    const [row] = await db.select().from(merchantReferrals).where(eq(merchantReferrals.id, id));
    return row;
  }

  async getMerchantReferralsByCode(code: string) {
    return db.select().from(merchantReferrals).where(eq(merchantReferrals.referralCode, code)).orderBy(desc(merchantReferrals.createdAt));
  }

  async createMerchantReferral(referral: InsertMerchantReferral) {
    const [row] = await db.insert(merchantReferrals).values(referral).returning();
    return row;
  }

  async updateMerchantReferral(id: number, updates: Partial<InsertMerchantReferral>) {
    const [row] = await db.update(merchantReferrals).set({ ...updates, updatedAt: new Date() }).where(eq(merchantReferrals.id, id)).returning();
    return row;
  }

  // ── Retention Campaign Configs ─────────────────────────────────────────────

  async getRetentionCampaignConfigs() {
    return db.select().from(retentionCampaignConfigs).orderBy(asc(retentionCampaignConfigs.alertType));
  }

  async getRetentionCampaignConfig(id: number) {
    const [row] = await db.select().from(retentionCampaignConfigs).where(eq(retentionCampaignConfigs.id, id));
    return row;
  }

  async getRetentionCampaignConfigByAlertType(alertType: string) {
    const [row] = await db.select().from(retentionCampaignConfigs).where(and(eq(retentionCampaignConfigs.alertType, alertType), eq(retentionCampaignConfigs.enabled, true)));
    return row;
  }

  async createRetentionCampaignConfig(config: InsertRetentionCampaignConfig) {
    const [row] = await db.insert(retentionCampaignConfigs).values(config).returning();
    return row;
  }

  async updateRetentionCampaignConfig(id: number, updates: Partial<InsertRetentionCampaignConfig>) {
    const [row] = await db.update(retentionCampaignConfigs).set({ ...updates, updatedAt: new Date() }).where(eq(retentionCampaignConfigs.id, id)).returning();
    return row;
  }

  async deleteRetentionCampaignConfig(id: number) {
    const result = await db.delete(retentionCampaignConfigs).where(eq(retentionCampaignConfigs.id, id));
    return (result.rowCount ?? 0) > 0;
  }

  // ── Residual Imports ──────────────────────────────────────────────────────
  }
  