// Auto-generated by storage split. Domain: sdr.
  // Methods are mixed into DatabaseStorage in server/storage.ts.
  import { db, pool } from "../db";
import {
  liveChats, liveChatMessages,
  type LiveChat, type InsertLiveChat, type LiveChatMessage, type InsertLiveChatMessage,
  contacts, companies, deals, tickets, tasks, documents, auditLogs, notifications, workflowRuns, workflows, rfis, users,
  chargebacks,
  type Chargeback, type InsertChargeback, type UpdateChargebackRequest,
  messageTemplates, collateralPackets, ghlActivityLog, slaConfigs,
  prospects, prospectLists, enrichmentJobs, campaigns, campaignSteps, outboundMessages, notes,
  emailLogs, callLogs, stageAutomationRules, followUpSequences, sequenceSteps, sequenceEnrollments,
  sunbizEntities, consentAuditLogs, calendarEvents,
  merchantApplications, merchantProfiles, equipmentOrders, agents, agentQuotas, agentMerchants, residualReports, merchantResiduals,
  healthAlerts, dealCompetitors, partners, referrals, commissionTiers, knowledgeBase, reviewRequests, testimonialSubmissions, onboardingSteps, midDailyStats,
  sdrMerchants, sdrMerchantContacts, sdrLeadState, sdrLeadEvents, sdrChannelAttempts, sdrComplianceState,
  sendingIdentities,
  leadDiscoveryJobs, leadDiscoveryResults,
  type SendingIdentity, type InsertSendingIdentity,
  businesses, businessAliases, businessLocations, leadSources, enrichmentRuns,
  type LeadDiscoveryJob, type InsertLeadDiscoveryJob,
  type LeadDiscoveryResult, type InsertLeadDiscoveryResult,
  type Business, type InsertBusiness, type UpdateBusinessRequest,
  type BusinessAlias, type InsertBusinessAlias,
  type BusinessLocation, type InsertBusinessLocation,
  type LeadSource, type InsertLeadSource,
  type EnrichmentRun, type InsertEnrichmentRun,
  type SdrMerchant, type InsertSdrMerchant,
  type SdrMerchantContact, type InsertSdrMerchantContact,
  type SdrLeadState, type InsertSdrLeadState,
  type SdrLeadEvent, type InsertSdrLeadEvent,
  type SdrChannelAttempt, type InsertSdrChannelAttempt,
  type SdrComplianceState, type InsertSdrComplianceState,
  type InsertContact, type UpdateContactRequest,
  type InsertCompany,
  type InsertDeal, type UpdateDealRequest,
  type InsertTicket, type UpdateTicketRequest,
  type InsertTask, type UpdateTaskRequest,
  type InsertDocument,
  type InsertAuditLog,
  type InsertNotification,
  type InsertWorkflow, type UpdateWorkflowRequest,
  type InsertWorkflowRun,
  type InsertRfi, type UpdateRfiRequest,
  type InsertMessageTemplate, type MessageTemplate,
  type InsertCollateralPacket,
  type InsertGhlActivityLog,
  type InsertSlaConfig,
  type Prospect, type InsertProspect, type UpdateProspectRequest,
  type InsertProspectList,
  type InsertEnrichmentJob,
  type InsertCampaign, type UpdateCampaignRequest,
  type InsertCampaignStep,
  type InsertOutboundMessage, type UpdateOutboundMessageRequest,
  type InsertNote,
  type InsertEmailLog, type InsertCallLog, type InsertStageAutomationRule, type InsertFollowUpSequence, type InsertSequenceStep, type InsertSequenceEnrollment,
  type InsertSunbizEntity, type UpdateSunbizEntityRequest, type SunbizEntity,
  type InsertMerchantApplication, type MerchantApplication,
  type InsertMerchantProfile, type MerchantProfile,
  type InsertEquipmentOrder, type EquipmentOrder,
  type InsertAgent, type Agent,
  type InsertAgentMerchant, type AgentMerchant,
  type InsertAgentQuota, type AgentQuota,
  type InsertResidualReport, type ResidualReport,
  type InsertMerchantResidual, type MerchantResidual,
  type InsertHealthAlert, type HealthAlert,
  type InsertDealCompetitor, type DealCompetitor,
  type InsertPartner, type Partner,
  type InsertReferral, type Referral,
  type InsertCommissionTier, type CommissionTier,
  type InsertKnowledgeBaseArticle, type KnowledgeBaseArticle,
  type InsertReviewRequest, type ReviewRequest,
  type InsertTestimonialSubmission, type TestimonialSubmission,
  type InsertOnboardingStep, type OnboardingStep,
  type InsertConsentAuditLog, type ConsentAuditLog,
  type CalendarEvent, type InsertCalendarEvent,
  systemSettings,
  dataDeleteRequests,
  type DataDeleteRequest, type InsertDataDeleteRequest,
  comments, ticketComments, contactCompanies, pipelineStages, notificationPreferences, savedFilters,
  type Comment, type InsertComment,
  type TicketComment, type InsertTicketComment,
  type ContactCompany, type InsertContactCompany,
  type PipelineStage, type InsertPipelineStage,
  type NotificationPreference, type InsertNotificationPreference,
  type SavedFilter, type InsertSavedFilter,
  csvImports, type CsvImport, type InsertCsvImport,
  generatedBlogPosts,
  type GeneratedBlogPost, type InsertGeneratedBlogPost,
  type UpdateSdrLeadState,
  ghlWorkflowMappings, type GhlWorkflowMapping,
  npsResponses, type NpsResponse, type InsertNpsResponse,
  merchantReferrals, type MerchantReferral, type InsertMerchantReferral,
  retentionCampaignConfigs, type RetentionCampaignConfig, type InsertRetentionCampaignConfig,
  type MidDailyStat, type InsertMidDailyStat,
  roleplaySessions, type RoleplaySession, type InsertRoleplaySession,
  roleplayExchanges, type RoleplayExchange, type InsertRoleplayExchange,
  leaderboardSettings, type LeaderboardSettings,
} from "@shared/schema";
import { eq, desc, and, lt, isNull, ne, sql, asc, gte, lte, inArray, notInArray, or, ilike, count } from "drizzle-orm";
  import { type PaginationParams, type PaginatedResult, normalizePagination } from "./_shared";

  export class SdrStorage {
    async getSdrMerchants(params?: PaginationParams) {
    const { limit, offset } = normalizePagination(params);
    const [totalResult] = await db.select({ count: count() }).from(sdrMerchants);
    const data = await db.select().from(sdrMerchants).orderBy(desc(sdrMerchants.createdAt)).limit(limit).offset(offset);
    return { data, total: totalResult.count, limit, offset };
  }


  async getSdrMerchant(id: number) {
    const [m] = await db.select().from(sdrMerchants).where(eq(sdrMerchants.id, id));
    return m;
  }


  async createSdrMerchant(data: InsertSdrMerchant) {
    const [m] = await db.insert(sdrMerchants).values(data).returning();
    return m;
  }


  async updateSdrMerchant(id: number, updates: Partial<InsertSdrMerchant>) {
    const [m] = await db.update(sdrMerchants).set({ ...updates, updatedAt: new Date() }).where(eq(sdrMerchants.id, id)).returning();
    return m;
  }


  async getSdrMerchantContacts(merchantId: number) {
    return db.select().from(sdrMerchantContacts).where(eq(sdrMerchantContacts.merchantId, merchantId));
  }


  async createSdrMerchantContact(data: InsertSdrMerchantContact) {
    const [c] = await db.insert(sdrMerchantContacts).values(data).returning();
    return c;
  }


  async getALeadQueue(): Promise<Array<SdrLeadState & { merchant: SdrMerchant | null }>> {
    const TERMINAL_STAGES = [
      "DISCARDED", "SUPPRESSED", "CONTACTED", "REPLIED",
      "CLOSED_WON", "PROMOTED_TO_CRM", "DEAD", "CONVERTED",
    ];
    const leads = await db
      .select()
      .from(sdrLeadState)
      .where(and(
        inArray(sdrLeadState.priorityBucket, ["A", "B"]),
        notInArray(sdrLeadState.stage, TERMINAL_STAGES),
        isNull(sdrLeadState.contactId),
      ))
      .orderBy(desc(sdrLeadState.priorityScore), desc(sdrLeadState.updatedAt))
      .limit(200);

    if (leads.length === 0) return [];

    const merchantIds = [...new Set(leads.map(l => l.merchantId))];
    const merchants = await db.select().from(sdrMerchants).where(inArray(sdrMerchants.id, merchantIds));
    const merchantMap = new Map(merchants.map(m => [m.id, m]));

    return leads.map(lead => ({ ...lead, merchant: merchantMap.get(lead.merchantId) ?? null }));
  }


  async getSdrLeadStates(filters?: { stage?: string; priorityBucket?: string; limit?: number }): Promise<SdrLeadState[]> {
    const conditions = [];
    if (filters?.stage) conditions.push(eq(sdrLeadState.stage, filters.stage));
    if (filters?.priorityBucket) conditions.push(eq(sdrLeadState.priorityBucket, filters.priorityBucket));
    const whereClause = conditions.length > 0 ? and(...conditions) : undefined;
    return db.select().from(sdrLeadState)
      .where(whereClause)
      .orderBy(desc(sdrLeadState.updatedAt))
      .limit(filters?.limit || 500);
  }


  async getSdrLeadState(id: number): Promise<SdrLeadState | undefined> {
    const [lead] = await db.select().from(sdrLeadState).where(eq(sdrLeadState.id, id));
    return lead;
  }


  async getSdrLeadStateByMerchant(merchantId: number): Promise<SdrLeadState | undefined> {
    const [s] = await db.select().from(sdrLeadState).where(eq(sdrLeadState.merchantId, merchantId));
    return s;
  }


  async getSdrLeadStateByContact(contactId: number): Promise<SdrLeadState | undefined> {
    const [lead] = await db.select().from(sdrLeadState).where(eq(sdrLeadState.contactId, contactId));
    return lead;
  }


  async createSdrLeadState(lead: InsertSdrLeadState): Promise<SdrLeadState> {
    const [created] = await db.insert(sdrLeadState).values(lead).returning();
    return created;
  }


  async upsertSdrLeadState(data: InsertSdrLeadState) {
    const existing = await this.getSdrLeadStateByMerchant(data.merchantId);
    const [s] = await db.insert(sdrLeadState)
      .values(data)
      .onConflictDoUpdate({
        target: sdrLeadState.merchantId,
        set: { ...data, updatedAt: new Date() },
      })
      .returning();

    const { onStageChange, onScoreChange } = await import("../services/sdr/ghl-sync-rules");
    if (existing) {
      if (data.currentStage && data.currentStage !== existing.currentStage) {
        onStageChange(data.merchantId, data.currentStage, existing.currentStage).catch(e => console.error("[SDR] stage sync error:", e));
      }
      const scoreChanged = (data.fitScore !== undefined && data.fitScore !== existing.fitScore) ||
        (data.revenueScore !== undefined && data.revenueScore !== existing.revenueScore) ||
        (data.reachabilityScore !== undefined && data.reachabilityScore !== existing.reachabilityScore) ||
        (data.priorityScore !== undefined && data.priorityScore !== existing.priorityScore);
      if (scoreChanged) {
        onScoreChange(data.merchantId, {
          fitScore: data.fitScore ?? undefined,
          revenueScore: data.revenueScore ?? undefined,
          reachabilityScore: data.reachabilityScore ?? undefined,
          priorityScore: data.priorityScore ?? undefined,
        }).catch(e => console.error("[SDR] score sync error:", e));
      }
    } else if (data.currentStage) {
      onStageChange(data.merchantId, data.currentStage).catch(e => console.error("[SDR] stage sync error:", e));
    }
    return s;
  }


  async updateSdrLeadState(id: number, updates: UpdateSdrLeadState): Promise<SdrLeadState | undefined> {
    const [updated] = await db.update(sdrLeadState).set({ ...updates, updatedAt: new Date() }).where(eq(sdrLeadState.id, id)).returning();
    return updated;
  }


  async getDueSdrLeads(limit?: number): Promise<SdrLeadState[]> {
    const now = new Date();
    return db.select().from(sdrLeadState)
      .where(and(
        lte(sdrLeadState.nextActionAt, now),
        sql`${sdrLeadState.stage} NOT IN ('DEAD', 'CONVERTED')`
      ))
      .orderBy(asc(sdrLeadState.nextActionAt))
      .limit(limit || 100);
  }


  async getSdrLeadEvents(leadStateId: number): Promise<SdrLeadEvent[]> {
    return db.select().from(sdrLeadEvents)
      .where(eq(sdrLeadEvents.leadStateId, leadStateId))
      .orderBy(desc(sdrLeadEvents.createdAt));
  }


  async createSdrLeadEvent(event: InsertSdrLeadEvent): Promise<SdrLeadEvent> {
    const [created] = await db.insert(sdrLeadEvents).values(event).returning();
    return created;
  }


  async getSdrChannelAttempts(leadStateId: number): Promise<SdrChannelAttempt[]> {
    return db.select().from(sdrChannelAttempts)
      .where(eq(sdrChannelAttempts.leadStateId, leadStateId))
      .orderBy(desc(sdrChannelAttempts.createdAt));
  }


  async createSdrChannelAttempt(attempt: InsertSdrChannelAttempt): Promise<SdrChannelAttempt> {
    const [created] = await db.insert(sdrChannelAttempts).values(attempt).returning();
    return created;
  }


  async getSdrComplianceState(merchantId: number) {
    const [c] = await db.select().from(sdrComplianceState).where(eq(sdrComplianceState.merchantId, merchantId));
    return c;
  }


  async upsertSdrComplianceState(data: InsertSdrComplianceState) {
    const existing = await this.getSdrComplianceState(data.merchantId!);
    if (existing) {
      const [c] = await db.update(sdrComplianceState).set({ ...data, updatedAt: new Date() }).where(eq(sdrComplianceState.merchantId, data.merchantId!)).returning();
      return c;
    }
    const [c] = await db.insert(sdrComplianceState).values(data).returning();
    return c;
  }


  async getSdrDashboardSummary() {
    const t0 = Date.now();
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    // Single SQL aggregation over sdrLeadState — no full-table fetch
    const [stateCounts] = await db.select({
      qualifiedToday: sql<number>`SUM(CASE WHEN (${sdrLeadState.stage} = 'QUALIFIED' OR ${sdrLeadState.currentStage} = 'QUALIFIED') AND ${sdrLeadState.updatedAt} >= ${today} THEN 1 ELSE 0 END)`,
      meetingSetToday: sql<number>`SUM(CASE WHEN ${sdrLeadState.stage} = 'MEETING_SET' AND ${sdrLeadState.updatedAt} >= ${today} THEN 1 ELSE 0 END)`,
      statementsToday: sql<number>`SUM(CASE WHEN (${sdrLeadState.stage} = 'STATEMENT_RECEIVED' OR ${sdrLeadState.currentStage} = 'STATEMENT_RECEIVED') AND ${sdrLeadState.updatedAt} >= ${today} THEN 1 ELSE 0 END)`,
      proposalsToday: sql<number>`SUM(CASE WHEN (${sdrLeadState.stage} = 'PROPOSAL_SENT' OR ${sdrLeadState.currentStage} = 'PROPOSAL_SENT') AND ${sdrLeadState.updatedAt} >= ${today} THEN 1 ELSE 0 END)`,
      closedWonToday: sql<number>`SUM(CASE WHEN ${sdrLeadState.stage} IN ('CLOSED_WON', 'BOARDED') AND ${sdrLeadState.updatedAt} >= ${today} THEN 1 ELSE 0 END)`,
      newDiscoveredToday: sql<number>`SUM(CASE WHEN ${sdrLeadState.stage} = 'DISCOVERED' AND ${sdrLeadState.createdAt} >= ${today} THEN 1 ELSE 0 END)`,
      humanOwnedCount: sql<number>`SUM(CASE WHEN ${sdrLeadState.assignedOwnerType} = 'human' OR ${sdrLeadState.ownerType} = 'human' THEN 1 ELSE 0 END)`,
    }).from(sdrLeadState);

    // Single SQL aggregation over today's events by event_type
    const eventCounts = await db.select({
      eventType: sdrLeadEvents.eventType,
      cnt: sql<number>`count(*)`,
    })
      .from(sdrLeadEvents)
      .where(gte(sdrLeadEvents.createdAt, today))
      .groupBy(sdrLeadEvents.eventType);

    const eventMap = new Map(eventCounts.map(e => [e.eventType, Number(e.cnt)]));
    const getEvent = (types: string[]) => types.reduce((sum, t) => sum + (eventMap.get(t) ?? 0), 0);

    // Count "new today" from stage_change events whose payloadJson.to === "DISCOVERED"
    // (matching original semantics — eventType is "stage_change", not a fabricated type)
    const [{ newFromStageChange }] = await db.select({
      newFromStageChange: sql<number>`count(*)`,
    })
      .from(sdrLeadEvents)
      .where(and(
        gte(sdrLeadEvents.createdAt, today),
        eq(sdrLeadEvents.eventType, "stage_change"),
        sql`${sdrLeadEvents.payloadJson}->>'to' = 'DISCOVERED'`,
      ));

    const contactedToday = getEvent(["message_sent", "call_made", "email_sent", "action_executed", "call_scheduled"]);
    const repliedToday = getEvent(["message_received", "reply_received", "sms_reply_received"]);
    const meetingsFromEvents = getEvent(["appointment_booked", "call_booked"]);

    const newToday = Number(newFromStageChange ?? 0) || Number(stateCounts?.newDiscoveredToday ?? 0);
    const meetingsToday = meetingsFromEvents || Number(stateCounts?.meetingSetToday ?? 0);

    const [{ total: totalMerchants }] = await db.select({ total: count() }).from(sdrMerchants);

    console.log(`[getSdrDashboardSummary] completed in ${Date.now() - t0}ms`);
    return {
      newToday,
      qualifiedToday: Number(stateCounts?.qualifiedToday ?? 0),
      contactedToday,
      repliedToday,
      meetingsToday,
      statementsToday: Number(stateCounts?.statementsToday ?? 0),
      proposalsToday: Number(stateCounts?.proposalsToday ?? 0),
      closedWonToday: Number(stateCounts?.closedWonToday ?? 0),
      humanOwnedCount: Number(stateCounts?.humanOwnedCount ?? 0),
      totalMerchants,
    };
  }


  async getSdrFunnelData() {
    const result = await db.select({
      stage: sdrLeadState.stage,
      count: sql<number>`count(*)`,
    }).from(sdrLeadState).groupBy(sdrLeadState.stage);

    const stageOrder = ["DISCOVERED", "ENRICHED", "CLASSIFIED", "QUALIFIED", "OUTREACH_EMAIL", "OUTREACH_SMS", "OUTREACH_CALL", "ENGAGED", "MEETING_SET", "STATEMENT_REQUESTED", "STATEMENT_RECEIVED", "PROPOSAL_SENT", "CLOSED_WON", "BOARDED", "TERMINAL_SHIPPED", "NURTURE", "NO_SHOW", "DEAD", "CONVERTED"];
    const sorted = result
      .map(r => ({ stage: r.stage, count: Number(r.count) }))
      .sort((a, b) => {
        const aIdx = stageOrder.indexOf(a.stage);
        const bIdx = stageOrder.indexOf(b.stage);
        return (aIdx === -1 ? 999 : aIdx) - (bIdx === -1 ? 999 : bIdx);
      });

    let prevCount = sorted.length > 0 ? sorted[0].count : 0;
    return sorted.map((s, idx) => {
      const conversionRate = idx > 0 && prevCount > 0 ? Math.round((s.count / prevCount) * 100) : undefined;
      const result = { ...s, conversionRate };
      prevCount = s.count > 0 ? s.count : prevCount;
      return result;
    });
  }


  async getSdrStuckLeads() {
    const cutoff = new Date(Date.now() - 48 * 60 * 60 * 1000);
    const stageAgeCutoff = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);

    const allLeads = await db.select({
      leadState: sdrLeadState,
      merchant: sdrMerchants,
    })
      .from(sdrLeadState)
      .innerJoin(sdrMerchants, eq(sdrLeadState.merchantId, sdrMerchants.id))
      .where(
        and(
          ne(sdrLeadState.stage, "DEAD"),
          ne(sdrLeadState.stage, "CONVERTED"),
          ne(sdrLeadState.stage, "TERMINAL_SHIPPED"),
        )
      )
      .limit(200);

    const overdue = allLeads
      .filter(s => s.leadState.nextActionAt && s.leadState.nextActionAt <= cutoff && s.leadState.stage !== "NURTURE" && s.leadState.stage !== "CLOSED_WON")
      .slice(0, 50);

    const waitingStatement = allLeads
      .filter(s => s.leadState.stage === "STATEMENT_REQUESTED" && s.leadState.statementRequestedAt && s.leadState.statementRequestedAt <= stageAgeCutoff)
      .slice(0, 20);

    const staleLeads = allLeads
      .filter(s => {
        const updatedAt = s.leadState.updatedAt || s.leadState.createdAt;
        return updatedAt && updatedAt <= stageAgeCutoff
          && !["NURTURE", "CLOSED_WON", "BOARDED", "TERMINAL_SHIPPED"].includes(s.leadState.stage || "");
      })
      .slice(0, 20);

    const complianceBlocked = await db.select({
      compliance: sdrComplianceState,
      merchant: sdrMerchants,
    })
      .from(sdrComplianceState)
      .innerJoin(sdrMerchants, eq(sdrComplianceState.merchantId, sdrMerchants.id))
      .where(
        or(
          eq(sdrComplianceState.dncBlock, true),
          eq(sdrComplianceState.complaintBlock, true),
          eq(sdrComplianceState.litigationBlock, true),
        )
      )
      .limit(50);

    function stageAgeDays(lead: typeof allLeads[0]["leadState"]): number {
      const ref = lead.updatedAt || lead.createdAt;
      if (!ref) return 0;
      return Math.floor((Date.now() - new Date(ref).getTime()) / (24 * 60 * 60 * 1000));
    }

    const seenMerchants = new Set<number>();
    const results: any[] = [];

    for (const s of overdue) {
      if (seenMerchants.has(s.merchant.id)) continue;
      seenMerchants.add(s.merchant.id);
      results.push({
        type: "overdue",
        leadId: s.leadState.id,
        merchantId: s.merchant.id,
        businessName: s.merchant.businessName,
        currentStage: s.leadState.stage || s.leadState.currentStage,
        nextActionAt: s.leadState.nextActionAt,
        reason: "Overdue next action",
        stageAgeDays: stageAgeDays(s.leadState),
        assignedOwnerType: s.leadState.assignedOwnerType,
      });
    }

    for (const s of waitingStatement) {
      if (seenMerchants.has(s.merchant.id)) continue;
      seenMerchants.add(s.merchant.id);
      results.push({
        type: "waiting_statement",
        leadId: s.leadState.id,
        merchantId: s.merchant.id,
        businessName: s.merchant.businessName,
        currentStage: s.leadState.stage || s.leadState.currentStage,
        nextActionAt: s.leadState.nextActionAt,
        reason: `Waiting for statement (${stageAgeDays(s.leadState)}d)`,
        stageAgeDays: stageAgeDays(s.leadState),
        assignedOwnerType: s.leadState.assignedOwnerType,
      });
    }

    for (const s of staleLeads) {
      if (seenMerchants.has(s.merchant.id)) continue;
      seenMerchants.add(s.merchant.id);
      results.push({
        type: "stage_age",
        leadId: s.leadState.id,
        merchantId: s.merchant.id,
        businessName: s.merchant.businessName,
        currentStage: s.leadState.stage || s.leadState.currentStage,
        nextActionAt: s.leadState.nextActionAt,
        reason: `Stale in ${s.leadState.stage || s.leadState.currentStage} for ${stageAgeDays(s.leadState)}d`,
        stageAgeDays: stageAgeDays(s.leadState),
        assignedOwnerType: s.leadState.assignedOwnerType,
      });
    }

    for (const c of complianceBlocked) {
      if (seenMerchants.has(c.merchant.id)) continue;
      seenMerchants.add(c.merchant.id);
      results.push({
        type: "compliance_blocked",
        leadId: null,
        merchantId: c.merchant.id,
        businessName: c.merchant.businessName,
        currentStage: null,
        nextActionAt: null,
        reason: c.compliance.dncBlock ? "DNC block" : c.compliance.complaintBlock ? "Complaint block" : "Litigation block",
        stageAgeDays: 0,
        assignedOwnerType: null,
      });
    }

    return results;
  }


  async getSdrActivityData() {
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    const attempts = await db.select().from(sdrChannelAttempts).where(gte(sdrChannelAttempts.createdAt, today));

    const emailsSent = attempts.filter(a => a.channel === "email").length;
    const smsSent = attempts.filter(a => a.channel === "sms").length;
    const callsMade = attempts.filter(a => a.channel === "call").length;
    const emailReplied = attempts.filter(a => a.channel === "email" && a.repliedAt).length;
    const smsReplied = attempts.filter(a => a.channel === "sms" && a.repliedAt).length;
    const optOuts = (await db.select().from(sdrLeadEvents)
      .where(and(gte(sdrLeadEvents.createdAt, today), eq(sdrLeadEvents.eventType, "opt_out")))
    ).length;

    const callsAnswered = attempts.filter(a => a.channel === "call" && a.repliedAt).length;

    return {
      emailsSent,
      smsSent,
      callsMade,
      emailReplyRate: emailsSent > 0 ? Math.round((emailReplied / emailsSent) * 100) : 0,
      smsReplyRate: smsSent > 0 ? Math.round((smsReplied / smsSent) * 100) : 0,
      optOutRate: (emailsSent + smsSent) > 0 ? Math.round((optOuts / (emailsSent + smsSent)) * 100) : 0,
      optOuts,
      noAnswerRate: callsMade > 0 ? Math.round(((callsMade - callsAnswered) / callsMade) * 100) : 0,
      emailDailyLimit: 200,
      smsDailyLimit: 100,
      callDailyLimit: 50,
    };
  }

  async getSendingIdentities(): Promise<SendingIdentity[]> {
    return await db.select().from(sendingIdentities).orderBy(asc(sendingIdentities.domain), asc(sendingIdentities.label));
  }


  async getSendingIdentity(id: number): Promise<SendingIdentity | undefined> {
    const [identity] = await db.select().from(sendingIdentities).where(eq(sendingIdentities.id, id));
    return identity;
  }


  async createSendingIdentity(data: InsertSendingIdentity): Promise<SendingIdentity> {
    const [identity] = await db.insert(sendingIdentities).values({
      ...data,
      warmupStartedAt: data.warmupStatus === "warming" ? new Date() : null,
    }).returning();
    return identity;
  }


  async updateSendingIdentity(id: number, updates: Partial<InsertSendingIdentity>): Promise<SendingIdentity | undefined> {
    const [identity] = await db.update(sendingIdentities)
      .set({ ...updates, updatedAt: new Date() })
      .where(eq(sendingIdentities.id, id))
      .returning();
    return identity;
  }


  async deleteSendingIdentity(id: number): Promise<boolean> {
    const result = await db.delete(sendingIdentities).where(eq(sendingIdentities.id, id)).returning();
    return result.length > 0;
  }


  async getLeadDiscoveryJobs(limit: number = 50): Promise<LeadDiscoveryJob[]> {
    return await db.select().from(leadDiscoveryJobs).orderBy(desc(leadDiscoveryJobs.createdAt)).limit(limit);
  }


  async getLeadDiscoveryJob(id: number): Promise<LeadDiscoveryJob | undefined> {
    const [job] = await db.select().from(leadDiscoveryJobs).where(eq(leadDiscoveryJobs.id, id));
    return job;
  }


  async createLeadDiscoveryJob(data: InsertLeadDiscoveryJob): Promise<LeadDiscoveryJob> {
    const [job] = await db.insert(leadDiscoveryJobs).values(data).returning();
    return job;
  }


  async updateLeadDiscoveryJob(id: number, updates: Partial<InsertLeadDiscoveryJob>): Promise<LeadDiscoveryJob | undefined> {
    const [job] = await db.update(leadDiscoveryJobs).set(updates).where(eq(leadDiscoveryJobs.id, id)).returning();
    return job;
  }


  async getLeadDiscoveryResults(jobId: number): Promise<LeadDiscoveryResult[]> {
    return await db.select().from(leadDiscoveryResults).where(eq(leadDiscoveryResults.jobId, jobId)).orderBy(desc(leadDiscoveryResults.createdAt));
  }


  async createLeadDiscoveryResult(data: InsertLeadDiscoveryResult): Promise<LeadDiscoveryResult> {
    const [result] = await db.insert(leadDiscoveryResults).values(data).returning();
    return result;
  }


  async createLeadDiscoveryResultsBulk(data: InsertLeadDiscoveryResult[]): Promise<LeadDiscoveryResult[]> {
    if (data.length === 0) return [];
    const batchSize = 100;
    const allResults: LeadDiscoveryResult[] = [];
    for (let i = 0; i < data.length; i += batchSize) {
      const batch = data.slice(i, i + batchSize);
      const results = await db.insert(leadDiscoveryResults).values(batch).returning();
      allResults.push(...results);
    }
    return allResults;
  }


  async getLeadDiscoveryStats(): Promise<any> {
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const weekAgo = new Date(today);
    weekAgo.setDate(weekAgo.getDate() - 7);

    const [todayStats] = await db.select({
      rawFound: sql<number>`COALESCE(SUM(${leadDiscoveryJobs.rawFound}), 0)`,
      newInserted: sql<number>`COALESCE(SUM(${leadDiscoveryJobs.newInserted}), 0)`,
      duplicatesSkipped: sql<number>`COALESCE(SUM(${leadDiscoveryJobs.duplicatesSkipped}), 0)`,
      enrichmentQueued: sql<number>`COALESCE(SUM(${leadDiscoveryJobs.enrichmentQueued}), 0)`,
      jobCount: sql<number>`COUNT(*)`,
    }).from(leadDiscoveryJobs).where(gte(leadDiscoveryJobs.createdAt, today));

    const [weekStats] = await db.select({
      rawFound: sql<number>`COALESCE(SUM(${leadDiscoveryJobs.rawFound}), 0)`,
      newInserted: sql<number>`COALESCE(SUM(${leadDiscoveryJobs.newInserted}), 0)`,
      duplicatesSkipped: sql<number>`COALESCE(SUM(${leadDiscoveryJobs.duplicatesSkipped}), 0)`,
      enrichmentQueued: sql<number>`COALESCE(SUM(${leadDiscoveryJobs.enrichmentQueued}), 0)`,
      jobCount: sql<number>`COUNT(*)`,
    }).from(leadDiscoveryJobs).where(gte(leadDiscoveryJobs.createdAt, weekAgo));

    const verticalBreakdown = await db.select({
      vertical: leadDiscoveryResults.vertical,
      count: sql<number>`COUNT(*)`,
      newCount: sql<number>`SUM(CASE WHEN ${leadDiscoveryResults.status} = 'inserted' THEN 1 ELSE 0 END)`,
    }).from(leadDiscoveryResults)
      .where(gte(leadDiscoveryResults.createdAt, today))
      .groupBy(leadDiscoveryResults.vertical);

    const metroBreakdown = await db.select({
      metro: leadDiscoveryResults.metro,
      count: sql<number>`COUNT(*)`,
      newCount: sql<number>`SUM(CASE WHEN ${leadDiscoveryResults.status} = 'inserted' THEN 1 ELSE 0 END)`,
    }).from(leadDiscoveryResults)
      .where(gte(leadDiscoveryResults.createdAt, today))
      .groupBy(leadDiscoveryResults.metro);

    const sourceBreakdown = await db.select({
      source: leadDiscoveryResults.source,
      count: sql<number>`COUNT(*)`,
      newCount: sql<number>`SUM(CASE WHEN ${leadDiscoveryResults.status} = 'inserted' THEN 1 ELSE 0 END)`,
    }).from(leadDiscoveryResults)
      .where(gte(leadDiscoveryResults.createdAt, today))
      .groupBy(leadDiscoveryResults.source);

    const todayRaw = Number(todayStats?.rawFound || 0);
    const todayDupes = Number(todayStats?.duplicatesSkipped || 0);
    const dedupRate = todayRaw > 0 ? Math.round((todayDupes / todayRaw) * 100) : 0;

    return {
      today: {
        rawFound: todayRaw,
        newInserted: Number(todayStats?.newInserted || 0),
        duplicatesSkipped: todayDupes,
        enrichmentQueued: Number(todayStats?.enrichmentQueued || 0),
        jobCount: Number(todayStats?.jobCount || 0),
        dedupRate,
      },
      week: {
        rawFound: Number(weekStats?.rawFound || 0),
        newInserted: Number(weekStats?.newInserted || 0),
        duplicatesSkipped: Number(weekStats?.duplicatesSkipped || 0),
        enrichmentQueued: Number(weekStats?.enrichmentQueued || 0),
        jobCount: Number(weekStats?.jobCount || 0),
      },
      byVertical: verticalBreakdown.map(v => ({
        vertical: v.vertical || "Unknown",
        count: Number(v.count),
        newCount: Number(v.newCount),
      })),
      byMetro: metroBreakdown.map(m => ({
        metro: m.metro || "Unknown",
        count: Number(m.count),
        newCount: Number(m.newCount),
      })),
      bySource: sourceBreakdown.map(s => ({
        source: s.source,
        count: Number(s.count),
        newCount: Number(s.newCount),
      })),
    };
  }


  async findSdrMerchantByDomain(domain: string): Promise<SdrMerchant | undefined> {
    const normalized = domain.replace(/^https?:\/\//i, "").replace(/\/$/, "").toLowerCase();
    if (!normalized) return undefined;
    const [match] = await db.select().from(sdrMerchants)
      .where(sql`LOWER(REGEXP_REPLACE(COALESCE(${sdrMerchants.domain}, ${sdrMerchants.website}), '^https?://', '', 'g')) = ${normalized}`)
      .limit(1);
    return match;
  }

  async findSdrMerchantByNameCity(businessName: string, city: string | null): Promise<SdrMerchant | undefined> {
    const normalizedName = businessName.toLowerCase().replace(/[^a-z0-9\s]/g, "").replace(/\s+/g, " ").trim();
    const conditions = [sql`LOWER(REGEXP_REPLACE(${sdrMerchants.businessName}, '[^a-zA-Z0-9\\s]', '', 'g')) = ${normalizedName}`];
    if (city) {
      conditions.push(sql`LOWER(${sdrMerchants.city}) = ${city.toLowerCase()}`);
    }
    const [match] = await db.select().from(sdrMerchants).where(and(...conditions)).limit(1);
    return match;
  }


  async getSdrMerchantsByCity(city: string): Promise<SdrMerchant[]> {
    return db.select().from(sdrMerchants).where(sql`LOWER(${sdrMerchants.city}) = ${city.toLowerCase()}`);
  }


  async getGhlWorkflowMappings(): Promise<GhlWorkflowMapping[]> {
    return db.select().from(ghlWorkflowMappings).orderBy(asc(ghlWorkflowMappings.sequenceName));
  }


  async upsertGhlWorkflowMapping(sequenceName: string, ghlWorkflowId: string | null, category?: string, description?: string): Promise<GhlWorkflowMapping> {
    const [existing] = await db.select().from(ghlWorkflowMappings).where(eq(ghlWorkflowMappings.sequenceName, sequenceName));
    if (existing) {
      const [updated] = await db.update(ghlWorkflowMappings)
        .set({ ghlWorkflowId, category: category || existing.category, description: description || existing.description, updatedAt: new Date() })
        .where(eq(ghlWorkflowMappings.sequenceName, sequenceName))
        .returning();
      return updated;
    } else {
      const [created] = await db.insert(ghlWorkflowMappings)
        .values({ sequenceName, ghlWorkflowId, category: category || null, description: description || null })
        .returning();
      return created;
    }
  }


  async getGhlWorkflowIdBySequenceName(sequenceName: string): Promise<string | null> {
    const [row] = await db.select({ ghlWorkflowId: ghlWorkflowMappings.ghlWorkflowId })
      .from(ghlWorkflowMappings)
      .where(eq(ghlWorkflowMappings.sequenceName, sequenceName));
    return row?.ghlWorkflowId || null;
  }

  // ── Live Chat ────────────────────────────────────────────────────────────────
  }
  