// Auto-generated by storage split. Domain: sunbiz.
  // Methods are mixed into DatabaseStorage in server/storage.ts.
  import { db, pool } from "../db";
import {
  liveChats, liveChatMessages,
  type LiveChat, type InsertLiveChat, type LiveChatMessage, type InsertLiveChatMessage,
  contacts, companies, deals, tickets, tasks, documents, auditLogs, notifications, workflowRuns, workflows, rfis, users,
  chargebacks,
  type Chargeback, type InsertChargeback, type UpdateChargebackRequest,
  messageTemplates, collateralPackets, ghlActivityLog, slaConfigs,
  prospects, prospectLists, enrichmentJobs, campaigns, campaignSteps, outboundMessages, notes,
  emailLogs, callLogs, stageAutomationRules, followUpSequences, sequenceSteps, sequenceEnrollments,
  sunbizEntities, consentAuditLogs, calendarEvents,
  merchantApplications, merchantProfiles, equipmentOrders, agents, agentQuotas, agentMerchants, residualReports, merchantResiduals,
  healthAlerts, dealCompetitors, partners, referrals, commissionTiers, knowledgeBase, reviewRequests, testimonialSubmissions, onboardingSteps, midDailyStats,
  sdrMerchants, sdrMerchantContacts, sdrLeadState, sdrLeadEvents, sdrChannelAttempts, sdrComplianceState,
  sendingIdentities,
  leadDiscoveryJobs, leadDiscoveryResults,
  type SendingIdentity, type InsertSendingIdentity,
  businesses, businessAliases, businessLocations, leadSources, enrichmentRuns,
  type LeadDiscoveryJob, type InsertLeadDiscoveryJob,
  type LeadDiscoveryResult, type InsertLeadDiscoveryResult,
  type Business, type InsertBusiness, type UpdateBusinessRequest,
  type BusinessAlias, type InsertBusinessAlias,
  type BusinessLocation, type InsertBusinessLocation,
  type LeadSource, type InsertLeadSource,
  type EnrichmentRun, type InsertEnrichmentRun,
  type SdrMerchant, type InsertSdrMerchant,
  type SdrMerchantContact, type InsertSdrMerchantContact,
  type SdrLeadState, type InsertSdrLeadState,
  type SdrLeadEvent, type InsertSdrLeadEvent,
  type SdrChannelAttempt, type InsertSdrChannelAttempt,
  type SdrComplianceState, type InsertSdrComplianceState,
  type InsertContact, type UpdateContactRequest,
  type InsertCompany,
  type InsertDeal, type UpdateDealRequest,
  type InsertTicket, type UpdateTicketRequest,
  type InsertTask, type UpdateTaskRequest,
  type InsertDocument,
  type InsertAuditLog,
  type InsertNotification,
  type InsertWorkflow, type UpdateWorkflowRequest,
  type InsertWorkflowRun,
  type InsertRfi, type UpdateRfiRequest,
  type InsertMessageTemplate, type MessageTemplate,
  type InsertCollateralPacket,
  type InsertGhlActivityLog,
  type InsertSlaConfig,
  type Prospect, type InsertProspect, type UpdateProspectRequest,
  type InsertProspectList,
  type InsertEnrichmentJob,
  type InsertCampaign, type UpdateCampaignRequest,
  type InsertCampaignStep,
  type InsertOutboundMessage, type UpdateOutboundMessageRequest,
  type InsertNote,
  type InsertEmailLog, type InsertCallLog, type InsertStageAutomationRule, type InsertFollowUpSequence, type InsertSequenceStep, type InsertSequenceEnrollment,
  type InsertSunbizEntity, type UpdateSunbizEntityRequest, type SunbizEntity,
  type InsertMerchantApplication, type MerchantApplication,
  type InsertMerchantProfile, type MerchantProfile,
  type InsertEquipmentOrder, type EquipmentOrder,
  type InsertAgent, type Agent,
  type InsertAgentMerchant, type AgentMerchant,
  type InsertAgentQuota, type AgentQuota,
  type InsertResidualReport, type ResidualReport,
  type InsertMerchantResidual, type MerchantResidual,
  type InsertHealthAlert, type HealthAlert,
  type InsertDealCompetitor, type DealCompetitor,
  type InsertPartner, type Partner,
  type InsertReferral, type Referral,
  type InsertCommissionTier, type CommissionTier,
  type InsertKnowledgeBaseArticle, type KnowledgeBaseArticle,
  type InsertReviewRequest, type ReviewRequest,
  type InsertTestimonialSubmission, type TestimonialSubmission,
  type InsertOnboardingStep, type OnboardingStep,
  type InsertConsentAuditLog, type ConsentAuditLog,
  type CalendarEvent, type InsertCalendarEvent,
  systemSettings,
  dataDeleteRequests,
  type DataDeleteRequest, type InsertDataDeleteRequest,
  comments, ticketComments, contactCompanies, pipelineStages, notificationPreferences, savedFilters,
  type Comment, type InsertComment,
  type TicketComment, type InsertTicketComment,
  type ContactCompany, type InsertContactCompany,
  type PipelineStage, type InsertPipelineStage,
  type NotificationPreference, type InsertNotificationPreference,
  type SavedFilter, type InsertSavedFilter,
  csvImports, type CsvImport, type InsertCsvImport,
  generatedBlogPosts,
  type GeneratedBlogPost, type InsertGeneratedBlogPost,
  type UpdateSdrLeadState,
  ghlWorkflowMappings, type GhlWorkflowMapping,
  npsResponses, type NpsResponse, type InsertNpsResponse,
  merchantReferrals, type MerchantReferral, type InsertMerchantReferral,
  retentionCampaignConfigs, type RetentionCampaignConfig, type InsertRetentionCampaignConfig,
  type MidDailyStat, type InsertMidDailyStat,
  roleplaySessions, type RoleplaySession, type InsertRoleplaySession,
  roleplayExchanges, type RoleplayExchange, type InsertRoleplayExchange,
  leaderboardSettings, type LeaderboardSettings,
} from "@shared/schema";
import { eq, desc, and, lt, isNull, ne, sql, asc, gte, lte, inArray, or, ilike, count } from "drizzle-orm";
  import { type PaginationParams, type PaginatedResult, normalizePagination } from "./_shared";

  export class SunbizStorage {
    async getSunbizEntities(listId?: number, params?: PaginationParams) {
    const { limit, offset } = normalizePagination(params);
    const condition = listId ? eq(sunbizEntities.listId, listId) : undefined;
    const [totalResult] = await db.select({ count: count() }).from(sunbizEntities).where(condition);
    const data = await db.select().from(sunbizEntities).where(condition).orderBy(desc(sunbizEntities.createdAt)).limit(limit).offset(offset);
    return { data, total: totalResult.count, limit, offset };
  }


  async getSunbizEntity(id: number) {
    const [entity] = await db.select().from(sunbizEntities).where(eq(sunbizEntities.id, id));
    return entity;
  }


  async getSunbizEntityByFiling(filingNumber: string) {
    const [entity] = await db.select().from(sunbizEntities).where(eq(sunbizEntities.filingNumber, filingNumber));
    return entity;
  }


  async createSunbizEntity(entity: InsertSunbizEntity) {
    const [created] = await db.insert(sunbizEntities).values(entity).returning();
    return created;
  }


  async createSunbizEntitiesBulk(entities: InsertSunbizEntity[]) {
    if (entities.length === 0) return [];
    const created = await db.insert(sunbizEntities).values(entities).returning();
    return created;
  }


  async updateSunbizEntity(id: number, updates: UpdateSunbizEntityRequest) {
    const [updated] = await db.update(sunbizEntities).set({ ...updates, updatedAt: new Date() }).where(eq(sunbizEntities.id, id)).returning();
    return updated;
  }


  async getSunbizEntitiesByStatus(status: string, limit?: number) {
    if (limit) {
      return await db.select().from(sunbizEntities).where(eq(sunbizEntities.enrichmentStatus, status)).orderBy(sunbizEntities.id).limit(limit);
    }
    return await db.select().from(sunbizEntities).where(eq(sunbizEntities.enrichmentStatus, status)).orderBy(desc(sunbizEntities.createdAt));
  }


  async searchSunbizEntitiesByNameCity(name: string, city?: string): Promise<SunbizEntity[]> {
    const cleanName = name.replace(/\b(LLC|INC|CORP|CORPORATION|COMPANY|CO|LTD|LP|LLP|PLLC)\b\.*/gi, "").trim();
    if (!cleanName) return [];
    const pattern = `%${cleanName}%`;
    if (city) {
      return await db.select().from(sunbizEntities)
        .where(and(
          or(
            ilike(sunbizEntities.entityName, pattern),
            ilike(sunbizEntities.dba, pattern)
          ),
          ilike(sunbizEntities.principalCity, city)
        ))
        .orderBy(desc(sunbizEntities.enrichmentStatus))
        .limit(5);
    }
    return await db.select().from(sunbizEntities)
      .where(or(
        ilike(sunbizEntities.entityName, pattern),
        ilike(sunbizEntities.dba, pattern)
      ))
      .orderBy(desc(sunbizEntities.enrichmentStatus))
      .limit(5);
  }


  async updateSunbizEntityByFilingNumber(filingNumber: string, updates: UpdateSunbizEntityRequest) {
    const [updated] = await db.update(sunbizEntities)
      .set({ ...updates, updatedAt: new Date() })
      .where(eq(sunbizEntities.filingNumber, filingNumber))
      .returning();
    return updated;
  }


  async bulkUpdateSunbizEntitiesByFiling(updates: Array<{ filingNumber: string; data: UpdateSunbizEntityRequest }>) {
    let updatedCount = 0;
    for (const { filingNumber, data } of updates) {
      try {
        const result = await db.update(sunbizEntities)
          .set({ ...data, updatedAt: new Date() })
          .where(eq(sunbizEntities.filingNumber, filingNumber));
        if (result.rowCount && result.rowCount > 0) updatedCount++;
      } catch { }
    }
    return updatedCount;
  }


  async getExistingFilingNumbers(): Promise<Set<string>> {
    const results = await db.select({ filingNumber: sunbizEntities.filingNumber }).from(sunbizEntities).where(sql`filing_number IS NOT NULL`);
    return new Set(results.map(r => r.filingNumber!).filter(Boolean));
  }


  async bulkUpsertSunbizEntities(records: Array<{
    filingNumber: string;
    entityName: string;
    feiEinNumber?: string;
    entityType?: string;
    entityStatus?: string;
    filingDate?: string;
    lastEvent?: string;
    principalAddress?: string;
    principalCity?: string;
    principalState?: string;
    principalZip?: string;
    mailingAddress?: string;
    registeredAgentName?: string;
    registeredAgentAddress?: string;
    officers?: any;
    ownerName?: string;
    enrichmentData?: any;
    listId?: number;
    source?: string;
  }>): Promise<{ inserted: number; updated: number }> {
    if (records.length === 0) return { inserted: 0, updated: 0 };

    const COLS = 22;
    const params: any[] = [];
    const valueGroups: string[] = [];

    for (let i = 0; i < records.length; i++) {
      const r = records[i];
      const base = i * COLS;
      params.push(
        r.filingNumber, r.entityName, r.feiEinNumber || null, r.entityType || null,
        r.entityStatus || null, r.filingDate || null, r.lastEvent || null,
        r.principalAddress || null, r.principalCity || null, r.principalState || 'FL', r.principalZip || null,
        r.mailingAddress || null, r.registeredAgentName || null, r.registeredAgentAddress || null,
        r.officers ? JSON.stringify(r.officers) : null, r.ownerName || null,
        r.enrichmentData ? JSON.stringify(r.enrichmentData) : null,
        r.listId || null, r.source || 'cordata', 'pending', new Date(), new Date()
      );
      const placeholders = Array.from({ length: COLS }, (_, j) => {
        const idx = base + j + 1;
        if (j === 14 || j === 16) return `$${idx}::jsonb`;
        return `$${idx}`;
      }).join(', ');
      valueGroups.push(`(${placeholders})`);
    }

    const queryText = `
      INSERT INTO sunbiz_entities (
        filing_number, entity_name, fei_ein_number, entity_type,
        entity_status, filing_date, last_event,
        principal_address, principal_city, principal_state, principal_zip,
        mailing_address, registered_agent_name, registered_agent_address,
        officers, owner_name, enrichment_data,
        list_id, source, enrichment_status, created_at, updated_at
      ) VALUES ${valueGroups.join(', ')}
      ON CONFLICT (filing_number) DO UPDATE SET
        entity_name = COALESCE(EXCLUDED.entity_name, sunbiz_entities.entity_name),
        fei_ein_number = COALESCE(EXCLUDED.fei_ein_number, sunbiz_entities.fei_ein_number),
        entity_type = COALESCE(EXCLUDED.entity_type, sunbiz_entities.entity_type),
        entity_status = COALESCE(EXCLUDED.entity_status, sunbiz_entities.entity_status),
        last_event = COALESCE(EXCLUDED.last_event, sunbiz_entities.last_event),
        principal_address = COALESCE(EXCLUDED.principal_address, sunbiz_entities.principal_address),
        principal_city = COALESCE(EXCLUDED.principal_city, sunbiz_entities.principal_city),
        principal_state = COALESCE(EXCLUDED.principal_state, sunbiz_entities.principal_state),
        principal_zip = COALESCE(EXCLUDED.principal_zip, sunbiz_entities.principal_zip),
        mailing_address = COALESCE(EXCLUDED.mailing_address, sunbiz_entities.mailing_address),
        registered_agent_name = COALESCE(EXCLUDED.registered_agent_name, sunbiz_entities.registered_agent_name),
        registered_agent_address = COALESCE(EXCLUDED.registered_agent_address, sunbiz_entities.registered_agent_address),
        officers = COALESCE(EXCLUDED.officers, sunbiz_entities.officers),
        owner_name = COALESCE(EXCLUDED.owner_name, sunbiz_entities.owner_name),
        enrichment_data = COALESCE(EXCLUDED.enrichment_data, sunbiz_entities.enrichment_data),
        updated_at = NOW()
    `;

    const client = await pool.connect();
    try {
      await client.query('SET statement_timeout = 120000');
      const result = await client.query(queryText, params);
      const totalAffected = result.rowCount || 0;
      return { inserted: totalAffected, updated: 0 };
    } finally {
      client.release();
    }
  }


  async getSunbizEntityCount(): Promise<number> {
    const [result] = await db.select({ count: sql<number>`count(*)::int` }).from(sunbizEntities);
    return result?.count || 0;
  }


  async getSunbizEntitiesNeedingEnrichment(limit: number = 200) {
    return await db.select().from(sunbizEntities)
      .where(sql`enrichment_status IN ('classified', 'pending', 'raw')
        AND (score = 'hot' OR score = 'warm')
        AND entity_status = 'Active'`)
      .orderBy(sql`
        CASE WHEN score = 'hot' THEN 0 ELSE 1 END,
        CASE WHEN vertical IN ('Restaurant', 'Retail', 'Healthcare', 'Salon/Spa', 'Auto', 'Food/Beverage', 'Fitness/Recreation') THEN 0 ELSE 1 END,
        CASE WHEN enrichment_status = 'classified' THEN 0 ELSE 1 END,
        id`)
      .limit(limit);
  }


  async getSunbizEntitiesForAIClassification(limit: number = 25) {
    return await db.select().from(sunbizEntities)
      .where(sql`(enrichment_status = 'pending' OR enrichment_status = 'raw' OR enrichment_status IS NULL)
        AND (vertical IS NULL OR vertical = '' OR vertical = 'Other')
        AND entity_status = 'Active'
        AND score != 'unqualified'`)
      .orderBy(sql`id`)
      .limit(limit);
  }


  async getSunbizEnrichmentDashboard(): Promise<{
    total: number; active: number;
    classified: number; unclassified: number;
    withEmail: number; withPhone: number; withAddress: number; withOwner: number;
    hot: number; warm: number; cold: number; unqualified: number;
    enriched: number; processing: number; failed: number;
    readyForOutreach: number;
    verticals: Record<string, { total: number; withContact: number }>;
  }> {
    const result = await db.execute(sql`
      SELECT
        COUNT(*)::int as total,
        COUNT(*) FILTER (WHERE entity_status = 'Active')::int as active,
        COUNT(*) FILTER (WHERE vertical IS NOT NULL AND vertical != '' AND vertical != 'Other')::int as classified,
        COUNT(*) FILTER (WHERE vertical IS NULL OR vertical = '' OR vertical = 'Other')::int as unclassified,
        COUNT(*) FILTER (WHERE email IS NOT NULL AND email != '')::int as with_email,
        COUNT(*) FILTER (WHERE phone IS NOT NULL AND phone != '')::int as with_phone,
        COUNT(*) FILTER (WHERE principal_address IS NOT NULL AND principal_address != '')::int as with_address,
        COUNT(*) FILTER (WHERE owner_name IS NOT NULL AND owner_name != '')::int as with_owner,
        COUNT(*) FILTER (WHERE score = 'hot')::int as hot,
        COUNT(*) FILTER (WHERE score = 'warm')::int as warm,
        COUNT(*) FILTER (WHERE score = 'cold')::int as cold,
        COUNT(*) FILTER (WHERE score = 'unqualified')::int as unqualified,
        COUNT(*) FILTER (WHERE enrichment_status = 'enriched')::int as enriched,
        COUNT(*) FILTER (WHERE enrichment_status = 'processing')::int as processing,
        COUNT(*) FILTER (WHERE enrichment_status = 'failed')::int as failed,
        COUNT(*) FILTER (WHERE (score = 'hot' OR score = 'warm') AND email IS NOT NULL AND email != '' AND phone IS NOT NULL AND phone != '')::int as ready_for_outreach
      FROM sunbiz_entities
    `);
    const row = ((result as any).rows || [])[0] || {};

    const vertResult = await db.execute(sql`
      SELECT
        COALESCE(vertical, 'Unclassified') as v,
        COUNT(*)::int as total,
        COUNT(*) FILTER (WHERE (email IS NOT NULL AND email != '') OR (phone IS NOT NULL AND phone != ''))::int as with_contact
      FROM sunbiz_entities
      WHERE entity_status = 'Active'
      GROUP BY COALESCE(vertical, 'Unclassified')
      ORDER BY total DESC
    `);
    const verticals: Record<string, { total: number; withContact: number }> = {};
    for (const vr of (vertResult as any).rows || []) {
      verticals[vr.v] = { total: Number(vr.total), withContact: Number(vr.with_contact) };
    }

    return {
      total: Number(row.total) || 0,
      active: Number(row.active) || 0,
      classified: Number(row.classified) || 0,
      unclassified: Number(row.unclassified) || 0,
      withEmail: Number(row.with_email) || 0,
      withPhone: Number(row.with_phone) || 0,
      withAddress: Number(row.with_address) || 0,
      withOwner: Number(row.with_owner) || 0,
      hot: Number(row.hot) || 0,
      warm: Number(row.warm) || 0,
      cold: Number(row.cold) || 0,
      unqualified: Number(row.unqualified) || 0,
      enriched: Number(row.enriched) || 0,
      processing: Number(row.processing) || 0,
      failed: Number(row.failed) || 0,
      readyForOutreach: Number(row.ready_for_outreach) || 0,
      verticals,
    };
  }


  async getSunbizDuplicates(limit: number = 100): Promise<Array<{ entityName: string; count: number; ids: number[] }>> {
    const result = await db.execute(sql`
      SELECT LOWER(entity_name) as entity_name, COUNT(*)::int as cnt, array_agg(id ORDER BY id) as ids
      FROM sunbiz_entities
      WHERE entity_status = 'Active'
      GROUP BY LOWER(entity_name)
      HAVING COUNT(*) > 1
      ORDER BY cnt DESC
      LIMIT ${limit}
    `);
    return ((result as any).rows || []).map((r: any) => ({
      entityName: r.entity_name,
      count: Number(r.cnt),
      ids: r.ids,
    }));
  }


  async mergeSunbizDuplicates(keepId: number, mergeIds: number[]): Promise<boolean> {
    const keeper = await this.getSunbizEntity(keepId);
    if (!keeper) return false;

    for (const mergeId of mergeIds) {
      if (mergeId === keepId) continue;
      const dup = await this.getSunbizEntity(mergeId);
      if (!dup) continue;

      const updates: Record<string, any> = {};
      if (!keeper.email && dup.email) updates.email = dup.email;
      if (!keeper.phone && dup.phone) updates.phone = dup.phone;
      if (!keeper.website && dup.website) updates.website = dup.website;
      if (!keeper.ownerName && dup.ownerName) updates.ownerName = dup.ownerName;
      if (!keeper.ownerEmail && dup.ownerEmail) updates.ownerEmail = dup.ownerEmail;
      if (!keeper.ownerPhone && dup.ownerPhone) updates.ownerPhone = dup.ownerPhone;
      if ((!keeper.vertical || keeper.vertical === 'Other') && dup.vertical && dup.vertical !== 'Other') {
        updates.vertical = dup.vertical;
        updates.score = dup.score;
      }

      if (Object.keys(updates).length > 0) {
        await this.updateSunbizEntity(keepId, updates);
      }

      await db.update(sunbizEntities).set({ enrichmentStatus: 'merged', notes: `Merged into ${keepId}` } as any).where(eq(sunbizEntities.id, mergeId));
    }
    return true;
  }


  async resetStuckProcessingEntities(): Promise<number> {
    const result = await db.execute(sql`
      UPDATE sunbiz_entities
      SET enrichment_status = 'classified'
      WHERE enrichment_status = 'processing'
        AND updated_at < NOW() - INTERVAL '30 minutes'
    `);
    return (result as any).rowCount || 0;
  }


  async getSunbizAggregateStats(): Promise<{
    total: number; enriched: number; pending: number; withEmail: number; withPhone: number;
    hot: number; warm: number; cold: number; unqualified: number; classified: number; pendingPromotion: number;
  }> {
    const result = await db.execute(sql`
      SELECT
        COUNT(*)::int as total,
        COUNT(*) FILTER (WHERE enrichment_status = 'enriched')::int as enriched,
        COUNT(*) FILTER (WHERE enrichment_status = 'pending')::int as pending,
        COUNT(*) FILTER (WHERE email IS NOT NULL)::int as with_email,
        COUNT(*) FILTER (WHERE phone IS NOT NULL)::int as with_phone,
        COUNT(*) FILTER (WHERE score = 'hot')::int as hot,
        COUNT(*) FILTER (WHERE score = 'warm')::int as warm,
        COUNT(*) FILTER (WHERE score = 'cold')::int as cold,
        COUNT(*) FILTER (WHERE score = 'unqualified')::int as unqualified,
        COUNT(*) FILTER (WHERE vertical IS NOT NULL AND vertical != 'Other')::int as classified,
        COUNT(*) FILTER (WHERE (score = 'hot' OR score = 'warm') AND email IS NOT NULL AND prospect_id IS NULL)::int as pending_promotion
      FROM sunbiz_entities
    `);
    const row = ((result as any).rows || [])[0] || {};
    return {
      total: Number(row.total) || 0, enriched: Number(row.enriched) || 0, pending: Number(row.pending) || 0,
      withEmail: Number(row.with_email) || 0, withPhone: Number(row.with_phone) || 0,
      hot: Number(row.hot) || 0, warm: Number(row.warm) || 0, cold: Number(row.cold) || 0,
      unqualified: Number(row.unqualified) || 0, classified: Number(row.classified) || 0,
      pendingPromotion: Number(row.pending_promotion) || 0,
    };
  }


  async getSunbizVerticalBreakdown(): Promise<Record<string, number>> {
    const result = await db.execute(sql`
      SELECT COALESCE(vertical, 'Unclassified') as v, COUNT(*)::int as c
      FROM sunbiz_entities GROUP BY COALESCE(vertical, 'Unclassified') ORDER BY c DESC
    `);
    const breakdown: Record<string, number> = {};
    for (const row of (result as any).rows || []) {
      breakdown[row.v] = Number(row.c);
    }
    return breakdown;
  }


  async getContactAggregateStats(): Promise<{ total: number; fromSunbiz: number; newLeads: number; syncedToGhl: number }> {
    const result = await db.execute(sql`
      SELECT
        COUNT(*)::int as total,
        COUNT(*) FILTER (WHERE referral_source = 'sunbiz_enrichment' OR 'sunbiz' = ANY(tags))::int as from_sunbiz,
        COUNT(*) FILTER (WHERE status = 'New')::int as new_leads,
        COUNT(*) FILTER (WHERE ghl_contact_id IS NOT NULL)::int as synced_to_ghl
      FROM contacts WHERE archived_at IS NULL
    `);
    const row = ((result as any).rows || [])[0] || {};
    return { total: Number(row.total) || 0, fromSunbiz: Number(row.from_sunbiz) || 0, newLeads: Number(row.new_leads) || 0, syncedToGhl: Number(row.synced_to_ghl) || 0 };
  }


  async getDealAggregateStats(): Promise<{ total: number; fromSunbiz: number; newLead: number; contacted: number; qualified: number; won: number }> {
    const result = await db.execute(sql`
      SELECT
        COUNT(*)::int as total,
        COUNT(*) FILTER (WHERE lead_source = 'sunbiz_enrichment' OR notes LIKE '%Sunbiz%')::int as from_sunbiz,
        COUNT(*) FILTER (WHERE stage = 'New Lead')::int as new_lead,
        COUNT(*) FILTER (WHERE stage = 'Contacted')::int as contacted,
        COUNT(*) FILTER (WHERE stage = 'Qualified')::int as qualified,
        COUNT(*) FILTER (WHERE stage = 'Won' OR stage = 'Closed Won')::int as won
      FROM deals WHERE archived_at IS NULL
    `);
    const row = ((result as any).rows || [])[0] || {};
    return { total: Number(row.total) || 0, fromSunbiz: Number(row.from_sunbiz) || 0, newLead: Number(row.new_lead) || 0, contacted: Number(row.contacted) || 0, qualified: Number(row.qualified) || 0, won: Number(row.won) || 0 };
  }


  async getProspectAggregateStats(): Promise<{ total: number; withEmail: number; converted: number; qualified: number }> {
    const result = await db.execute(sql`
      SELECT
        COUNT(*)::int as total,
        COUNT(*) FILTER (WHERE email IS NOT NULL)::int as with_email,
        COUNT(*) FILTER (WHERE status = 'converted')::int as converted,
        COUNT(*) FILTER (WHERE qualification_score IN ('A', 'B'))::int as qualified
      FROM prospects
    `);
    const row = ((result as any).rows || [])[0] || {};
    return { total: Number(row.total) || 0, withEmail: Number(row.with_email) || 0, converted: Number(row.converted) || 0, qualified: Number(row.qualified) || 0 };
  }


  async getSunbizStats(listId?: number) {
    const condition = listId ? sql`list_id = ${listId}` : sql`1=1`;
    const result = await db.execute(sql`
      SELECT
        COUNT(*)::int as total,
        COUNT(*) FILTER (WHERE enrichment_status = 'enriched')::int as enriched,
        COUNT(*) FILTER (WHERE enrichment_status = 'pending')::int as pending,
        COUNT(*) FILTER (WHERE email IS NOT NULL OR owner_email IS NOT NULL)::int as with_email,
        COUNT(*) FILTER (WHERE phone IS NOT NULL OR owner_phone IS NOT NULL)::int as with_phone,
        COUNT(*) FILTER (WHERE website IS NOT NULL)::int as with_website
      FROM sunbiz_entities
      WHERE ${condition}
    `);
    const rows = (result as any).rows || [];
    const row = rows[0] || {};
    return {
      total: Number(row.total) || 0,
      enriched: Number(row.enriched) || 0,
      pending: Number(row.pending) || 0,
      withEmail: Number(row.with_email) || 0,
      withPhone: Number(row.with_phone) || 0,
      withWebsite: Number(row.with_website) || 0,
    };
  }
  }
  