// Auto-generated by storage split. Domain: tasks.
  // Methods are mixed into DatabaseStorage in server/storage.ts.
  import { db, pool } from "../db";
import type { InternalTaskInsert } from "../types/task-types";
import {
  liveChats, liveChatMessages,
  type LiveChat, type InsertLiveChat, type LiveChatMessage, type InsertLiveChatMessage,
  contacts, companies, deals, tickets, tasks, documents, auditLogs, notifications, workflowRuns, workflows, rfis, users,
  chargebacks,
  type Chargeback, type InsertChargeback, type UpdateChargebackRequest,
  messageTemplates, collateralPackets, ghlActivityLog, slaConfigs,
  prospects, prospectLists, enrichmentJobs, campaigns, campaignSteps, outboundMessages, notes,
  emailLogs, callLogs, stageAutomationRules, followUpSequences, sequenceSteps, sequenceEnrollments,
  sunbizEntities, consentAuditLogs, calendarEvents,
  merchantApplications, merchantProfiles, equipmentOrders, agents, agentQuotas, agentMerchants, residualReports, merchantResiduals,
  healthAlerts, dealCompetitors, partners, referrals, commissionTiers, knowledgeBase, reviewRequests, testimonialSubmissions, onboardingSteps, midDailyStats,
  sdrMerchants, sdrMerchantContacts, sdrLeadState, sdrLeadEvents, sdrChannelAttempts, sdrComplianceState,
  sendingIdentities,
  leadDiscoveryJobs, leadDiscoveryResults,
  type SendingIdentity, type InsertSendingIdentity,
  businesses, businessAliases, businessLocations, leadSources, enrichmentRuns,
  type LeadDiscoveryJob, type InsertLeadDiscoveryJob,
  type LeadDiscoveryResult, type InsertLeadDiscoveryResult,
  type Business, type InsertBusiness, type UpdateBusinessRequest,
  type BusinessAlias, type InsertBusinessAlias,
  type BusinessLocation, type InsertBusinessLocation,
  type LeadSource, type InsertLeadSource,
  type EnrichmentRun, type InsertEnrichmentRun,
  type SdrMerchant, type InsertSdrMerchant,
  type SdrMerchantContact, type InsertSdrMerchantContact,
  type SdrLeadState, type InsertSdrLeadState,
  type SdrLeadEvent, type InsertSdrLeadEvent,
  type SdrChannelAttempt, type InsertSdrChannelAttempt,
  type SdrComplianceState, type InsertSdrComplianceState,
  type InsertContact, type UpdateContactRequest,
  type InsertCompany,
  type InsertDeal, type UpdateDealRequest,
  type InsertTicket, type UpdateTicketRequest,
  type InsertTask, type UpdateTaskRequest,

  type InsertDocument,
  type InsertAuditLog,
  type InsertNotification,
  type InsertWorkflow, type UpdateWorkflowRequest,
  type InsertWorkflowRun,
  type InsertRfi, type UpdateRfiRequest,
  type InsertMessageTemplate, type MessageTemplate,
  type InsertCollateralPacket,
  type InsertGhlActivityLog,
  type InsertSlaConfig,
  type Prospect, type InsertProspect, type UpdateProspectRequest,
  type InsertProspectList,
  type InsertEnrichmentJob,
  type InsertCampaign, type UpdateCampaignRequest,
  type InsertCampaignStep,
  type InsertOutboundMessage, type UpdateOutboundMessageRequest,
  type InsertNote,
  type InsertEmailLog, type InsertCallLog, type InsertStageAutomationRule, type InsertFollowUpSequence, type InsertSequenceStep, type InsertSequenceEnrollment,
  type InsertSunbizEntity, type UpdateSunbizEntityRequest, type SunbizEntity,
  type InsertMerchantApplication, type MerchantApplication,
  type InsertMerchantProfile, type MerchantProfile,
  type InsertEquipmentOrder, type EquipmentOrder,
  type InsertAgent, type Agent,
  type InsertAgentMerchant, type AgentMerchant,
  type InsertAgentQuota, type AgentQuota,
  type InsertResidualReport, type ResidualReport,
  type InsertMerchantResidual, type MerchantResidual,
  type InsertHealthAlert, type HealthAlert,
  type InsertDealCompetitor, type DealCompetitor,
  type InsertPartner, type Partner,
  type InsertReferral, type Referral,
  type InsertCommissionTier, type CommissionTier,
  type InsertKnowledgeBaseArticle, type KnowledgeBaseArticle,
  type InsertReviewRequest, type ReviewRequest,
  type InsertTestimonialSubmission, type TestimonialSubmission,
  type InsertOnboardingStep, type OnboardingStep,
  type InsertConsentAuditLog, type ConsentAuditLog,
  type CalendarEvent, type InsertCalendarEvent,
  systemSettings,
  dataDeleteRequests,
  type DataDeleteRequest, type InsertDataDeleteRequest,
  comments, ticketComments, contactCompanies, pipelineStages, notificationPreferences, savedFilters,
  type Comment, type InsertComment,
  type TicketComment, type InsertTicketComment,
  type ContactCompany, type InsertContactCompany,
  type PipelineStage, type InsertPipelineStage,
  type NotificationPreference, type InsertNotificationPreference,
  type SavedFilter, type InsertSavedFilter,
  csvImports, type CsvImport, type InsertCsvImport,
  generatedBlogPosts,
  type GeneratedBlogPost, type InsertGeneratedBlogPost,
  type UpdateSdrLeadState,
  ghlWorkflowMappings, type GhlWorkflowMapping,
  npsResponses, type NpsResponse, type InsertNpsResponse,
  merchantReferrals, type MerchantReferral, type InsertMerchantReferral,
  retentionCampaignConfigs, type RetentionCampaignConfig, type InsertRetentionCampaignConfig,
  type MidDailyStat, type InsertMidDailyStat,
  roleplaySessions, type RoleplaySession, type InsertRoleplaySession,
  roleplayExchanges, type RoleplayExchange, type InsertRoleplayExchange,
  leaderboardSettings, type LeaderboardSettings,
} from "@shared/schema";
import { eq, desc, and, lt, isNull, ne, sql, asc, gte, lte, inArray, or, ilike, count } from "drizzle-orm";
  import { type PaginationParams, type PaginatedResult, normalizePagination } from "./_shared";

  export class TasksStorage {
    async getTasks(opts?: { limit?: number; offset?: number }) {
    let query = db.select().from(tasks).where(isNull(tasks.deletedAt)).orderBy(desc(tasks.createdAt)) as any;
    if (opts?.limit) query = query.limit(opts.limit);
    if (opts?.offset) query = query.offset(opts.offset);
    return await query;
  }

  async getTasksByDeal(dealId: number) {
    return db.select().from(tasks).where(and(eq(tasks.dealId, dealId), isNull(tasks.deletedAt))).orderBy(asc(tasks.createdAt));
  }

  async getTaskById(id: number) {
    const [task] = await db.select().from(tasks).where(eq(tasks.id, id));
    return task ?? null;
  }


  async createTask(insertTask: InternalTaskInsert) {
    const [task] = await db.insert(tasks).values(insertTask as typeof tasks.$inferInsert).returning();
    return task;
  }

  async updateTask(id: number, updates: UpdateTaskRequest) {
    const ALLOWED_KEYS = [
      'dealId', 'contactId', 'ticketId', 'title', 'description',
      'assignedTo', 'dueDate', 'status', 'priority', 'completedAt',
      'ghlTaskId', 'deletedAt',
    ] as const;
    const safeUpdates: Record<string, unknown> = {};
    for (const key of ALLOWED_KEYS) {
      if (key in updates) {
        safeUpdates[key] = (updates as Record<string, unknown>)[key];
      }
    }
    type AllowedKey = typeof ALLOWED_KEYS[number];
    const typed: Partial<Pick<typeof tasks.$inferInsert, AllowedKey>> = {};
    for (const key of ALLOWED_KEYS) {
      if (key in safeUpdates) {
        const v = safeUpdates[key];
        if ((key === "dueDate" || key === "completedAt" || key === "deletedAt") && typeof v === "string") {
          (typed as Record<string, unknown>)[key] = new Date(v);
        } else {
          (typed as Record<string, unknown>)[key] = v;
        }
      }
    }
    const [updated] = await db.update(tasks).set(typed).where(eq(tasks.id, id)).returning();
    return updated;
  }

  async createStallingDealFollowUpTask(
    payload: Omit<InternalTaskInsert, 'source' | 'automationKey'>,
  ): Promise<{ task: typeof tasks.$inferSelect | null; created: boolean }> {
    const insertValues = {
      ...payload,
      source: 'sla' as const,
      automationKey: 'stalling-deal-follow-up' as const,
    } as typeof tasks.$inferInsert;

    // Use INSERT ... ON CONFLICT (deal_id, automation_key) WHERE <partial-index-predicate> DO NOTHING
    // via raw SQL so the conflict target exactly matches the partial unique index definition.
    // Drizzle's onConflictDoNothing({ targetWhere }) does not reliably emit the WHERE clause
    // needed to match a partial index in PostgreSQL.
    try {
      const result = await db.execute(sql`
        INSERT INTO tasks (
          deal_id, contact_id, ticket_id, title, description, assigned_to,
          due_date, status, priority, completed_at, ghl_task_id, deleted_at,
          source, automation_key
        )
        VALUES (
          ${insertValues.dealId ?? null},
          ${insertValues.contactId ?? null},
          ${insertValues.ticketId ?? null},
          ${insertValues.title},
          ${insertValues.description ?? null},
          ${insertValues.assignedTo ?? null},
          ${insertValues.dueDate ?? null},
          ${(insertValues.status as string) ?? 'pending'},
          ${(insertValues.priority as string) ?? 'normal'},
          ${insertValues.completedAt ?? null},
          ${insertValues.ghlTaskId ?? null},
          ${insertValues.deletedAt ?? null},
          'sla',
          'stalling-deal-follow-up'
        )
        ON CONFLICT (deal_id, automation_key)
        WHERE deleted_at IS NULL
          AND completed_at IS NULL
          AND deal_id IS NOT NULL
          AND source = 'sla'
          AND automation_key = 'stalling-deal-follow-up'
        DO NOTHING
        RETURNING *
      `);
      const rows = (result as any).rows ?? result;
      const task = Array.isArray(rows) && rows.length > 0
        ? (rows[0] as typeof tasks.$inferSelect)
        : null;
      return { task, created: task !== null };
    } catch (err: any) {
      // The ON CONFLICT ... DO NOTHING in the SQL above silently handles the
      // targeted partial-index conflict (returns empty RETURNING) without raising
      // an exception. Any exception that reaches this catch is therefore a
      // non-targeted DB error (different unique constraint, FK violation, network
      // error, etc.) and must be rethrown.
      throw err;
    }
  }


  async bulkAssignTasks(taskIds: number[], assignedTo: string): Promise<void> {
    await db.update(tasks).set({ assignedTo }).where(inArray(tasks.id, taskIds));
  }


  async getTaskByGhlTaskId(ghlTaskId: string) {
    const [task] = await db.select().from(tasks).where(eq(tasks.ghlTaskId, ghlTaskId));
    return task;
  }

  async softDeleteTask(id: number): Promise<void> {
    await db.update(tasks).set({ deletedAt: new Date() }).where(eq(tasks.id, id));
  }

  async bulkSoftDeleteTasks(ids: number[]): Promise<number> {
    const unique = [...new Set(ids.filter(id => Number.isInteger(id) && id > 0))];
    if (unique.length === 0) return 0;
    const CHUNK_SIZE = 500;
    let totalDeleted = 0;
    const now = new Date();
    for (let i = 0; i < unique.length; i += CHUNK_SIZE) {
      const chunk = unique.slice(i, i + CHUNK_SIZE);
      const result = await db
        .update(tasks)
        .set({ deletedAt: now })
        .where(and(inArray(tasks.id, chunk), isNull(tasks.deletedAt)))
        .returning({ id: tasks.id });
      totalDeleted += result.length;
    }
    return totalDeleted;
  }

  async deleteTask(id: number): Promise<void> {
    await db.delete(tasks).where(eq(tasks.id, id));
  }

  }
  